In [1]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import kennard_stone as ks
pd.options.plotting.backend = 'plotly'  # setting plotly as the backend for pandas plotting

# Add parent directory to sys.path so local module 'synthetic' can be imported
import sys
from pathlib import Path # for path manipulations
# Move three levels up from current working directory to reach workspace root
workspace_root = Path.cwd().parent.parent.parent.resolve() 
smx_dir = workspace_root / 'smx'  # Path to smx folder
if str(smx_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(smx_dir)) # insert at the start of sys.path to prioritize local modules

# Loading a soil spectral dataset based on X-ray fluorescence (XRF)
data_complete = pd.read_csv(f'{workspace_root}/real_datasets/xrf/forage.csv', sep=';') # local copy of Toledo 2022 dataset (os ... indica para omitir o caminho longo)
data = data_complete.loc[:, '1.4':'20.81']

# Split dataset by class and create calibration/prediction sets using Kennard-Stone (as in original pipeline)
data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.loc[:, '1.4':'20.81'], test_size=0.30)  # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.loc[:, '1.4':'20.81'], test_size=0.30)  # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)

Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True)  # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0])  # target for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0])  # target for prediction set

# preprocessings
import preprocessings as prepr  # preprocessing methods for XRF data

Xcalclass_prep, mean_calclass, mean_calclass_poisson  = prepr.poisson(Xcalclass, mc=True)
Xpredclass_prep = ((Xpredclass/np.sqrt(mean_calclass)) - mean_calclass_poisson)

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-26 16:45:21,665 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-26 16:45:21,671 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-26 16:45:21,697 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-26 16:45:21,726 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [2]:
from modeling import mlp_optimized

mlp_model = mlp_optimized(Xcalclass_prep, ycalclass, Xpredclass_prep, ypredclass, 
                          aim='classification', 
                          hidden_layer_sizes=(64,32),
                          activation='tanh',
                          learning_rate='adaptive',
                          max_iter=10,
                          random_state=1)
mlp_model[0]

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(

,Model,Accuracy Cal,Sensitivity Cal,Specificity Cal,CM Cal,Accuracy Pred,Sensitivity Pred,Specificity Pred,CM Pred
0,MLP,0.985185,0.978947,1.0,"[[40, 0], [2, 93]]",1.0,1.0,1.0,"[[18, 0], [0, 42]]"

## Definição das Zonas Espectrais

In [3]:
# establishing spectral cuts based on expert knowledge of XRF spectra
spectral_cuts = [
('Al', 1.40, 1.63),
('Si', 1.63, 1.86),
('P', 1.86, 2.16),
('S', 2.16, 2.44),
('Rh L + Ar', 2.44, 3.10),
('K', 3.10, 3.46),
('Ca ka', 3.46, 3.86),
('Ca kb', 3.86, 4.37),
('Ti ka', 4.37, 4.66),
('Ti kb', 4.66, 5.08),
('background1', 5.08, 5.72),
('Mn', 5.72, 6.10),
('Fe ka', 6.10, 6.76),
('Fe kb', 6.76, 7.20),
('Ni', 7.20, 7.69),
('Cu', 7.69, 8.45),
('Zn', 8.45, 8.81),
('background2', 8.81, 13.10),
('sum Fe' , 13.10, 13.63),
('background3', 13.63, 18.0),
('Compton scattering', 18.0, 19.70),
('Rayleight scattering', 19.70, 20.80)
]

## SHAP

In [4]:
shap_global_importance = pd.read_csv('shap_forage.csv', sep=';') # loading previously saved shap_unique_df
# vamos gerar uma nova coluna em shap_global_importance com o nome da zona espectral correspondente de acordo com a lista spectral_cuts
energy_to_zone_shap = {}
for zone_name, start, end in spectral_cuts:
    for i in shap_global_importance['energy']:
        i_float = float(i)
        if start <= i_float <= end:
            energy_to_zone_shap[i] = zone_name
shap_global_importance['Zone'] = shap_global_importance['energy'].map(energy_to_zone_shap)

# agora vamos filtrar shap_global_importance para manter apenas as zonas espectrais únicas com maior SHAP score
shap_unique_df = shap_global_importance.sort_values(by='Mean_Abs_SHAP', ascending=False).reset_index(drop=True)
shap_unique_df = shap_unique_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
shap_unique_df

    energy  Mean_Abs_SHAP                  Zone
0     3.70       0.034479                 Ca ka
1     6.40       0.030021                 Fe ka
2     3.36       0.020017                     K
3     1.74       0.008024                    Si
4     4.00       0.006471                 Ca kb
5     4.50       0.004159                 Ti ka
6     2.56       0.002085             Rh L + Ar
7    17.43       0.000544           background3
8     5.92       0.000510                    Mn
9    10.55       0.000498           background2
10    2.00       0.000441                     P
11   18.35       0.000407    Compton scattering
12   13.39       0.000406                sum Fe
13    7.00       0.000330                 Fe kb
14    2.32       0.000226                     S
15    7.24       0.000096                    Ni
16    4.92       0.000025                 Ti kb
17    1.40       0.000000                    Al
18   19.71       0.000000  Rayleight scattering
19    5.64       0.000000           background1
20    7.73       0.000000                    Cu
21    8.53       0.000000                    Zn
22   20.81       0.000000                   NaN

## Funções de Agregação por PCA

Aqui implementamos as funções para agregar zonas espectrais usando PCA com 1 componente principal.

In [5]:
import explaining as exp

# Extração das zonas espectrais
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_scores_df, pca_info_dict = exp.aggregate_spectral_zones_pca(spectral_zones_class) # apca aggregation
print(f"\nScores DataFrame shape: {zone_scores_df.shape}")

Zone 'Al': VE = 92.81%, dim = 12 variables
Zone 'Si': VE = 99.42%, dim = 12 variables
Zone 'P': VE = 94.16%, dim = 16 variables
Zone 'S': VE = 89.31%, dim = 15 variables
Zone 'Rh L + Ar': VE = 95.85%, dim = 34 variables
Zone 'K': VE = 98.44%, dim = 19 variables
Zone 'Ca ka': VE = 89.46%, dim = 21 variables
Zone 'Ca kb': VE = 96.25%, dim = 26 variables
Zone 'Ti ka': VE = 98.15%, dim = 15 variables
Zone 'Ti kb': VE = 76.25%, dim = 22 variables
Zone 'background1': VE = 66.63%, dim = 33 variables
Zone 'Mn': VE = 94.16%, dim = 20 variables
Zone 'Fe ka': VE = 99.38%, dim = 34 variables
Zone 'Fe kb': VE = 94.04%, dim = 23 variables
Zone 'Ni': VE = 77.76%, dim = 25 variables
Zone 'Cu': VE = 84.25%, dim = 39 variables
Zone 'Zn': VE = 82.20%, dim = 19 variables
Zone 'background2': VE = 86.56%, dim = 215 variables
Zone 'sum Fe': VE = 88.47%, dim = 27 variables
Zone 'background3': VE = 87.92%, dim = 219 variables
Zone 'Compton scattering': VE = 88.73%, dim = 85 variables
Zone 'Rayleight scattering': VE = 84.44%, dim = 55 variables

Scores DataFrame shape: (135, 22)

In [6]:
y_pred = mlp_model[4]['MLP'].values # using the continuous predictions from SVM, extracting as 1D array
predicates_quantiles = exp.predicates_by_quantiles(zone_scores_df, [0.2, 0.4, 0.6, 0.8])
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_scores_df,
    y_predicted_numeric=y_pred
)

In [7]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_cov = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE

y_pred = pd.Series(mlp_model[4]['MLP'].values) # using the continuous predictions from SVM, extracting as 1D array

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist
    
    # Calcular MI
    cov_results_dict_seed = exp.calculate_predicate_metrics(
        bags_result=bags_result_seed,
        metric='covariance', # covariance ou mutual_information
        threshold=0.01, # threshold para cortar predicados irrelevantes
        n_neighbors=5
    )
    
    # Salvar no dicionário principal
    all_results_cov[seed] = {
        'bags_result': bags_result_seed,
        'cov_results_dict': cov_results_dict_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graph(
        bags_result=all_results_cov[seed]['bags_result'],
        predicate_ranking_dict=all_results_cov[seed]['cov_results_dict'],
        metric_column='Covariance',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )
    # Armazenar grafo
    graphs_by_seed[seed] = DG

# Calcular LRC usando a função pronta do explaining.py
lrc_cov_by_seed = {}
for seed in random_seeds:
    DG = graphs_by_seed[seed]
    lrc_cov_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_cov_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_cov_by_seed[seed] = lrc_cov_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_cov_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_cov_df_seed = lrc_cov_by_seed[seed].rename(columns={'Node': f'Predicate_Cov_Seed_{seed}'})
    lrc_cov_all_seeds_df = pd.concat([lrc_cov_all_seeds_df, lrc_cov_df_seed[[f'Predicate_Cov_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_cov_unique_by_seed = {}
for seed, lrc_df in lrc_cov_by_seed.items():
    lrc_cov_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_cov_unique_df = lrc_cov_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_cov_unique_by_seed[seed] = lrc_cov_unique_df

lrc_cov_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_2 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_3 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_4 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_5 | Samples: Yes | Predicates: No (All) | Valid: 133 | Discarded: 43
Bag_6 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_7 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_8 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_9 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_10 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Computing Covariance for Predicates
Metric: covariance
Threshold: 0.01

======================================================================
Processando semente: 1
======================================================================

Bag_1 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_2 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_3 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_4 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_5 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_6 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_7 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_8 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_9 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_10 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Computing Covariance for Predicates
Metric: covariance
Threshold: 0.01

======================================================================
Processando semente: 2
======================================================================

Bag_1 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_2 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_3 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_4 | Samples: Yes | Predicates: No (All) | Valid: 133 | Discarded: 43
Bag_5 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_6 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_7 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_8 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_9 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_10 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Computing Covariance for Predicates
Metric: covariance
Threshold: 0.01

======================================================================
Processando semente: 3
======================================================================

Bag_1 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_2 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_3 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_4 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_5 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_6 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_7 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_8 | Samples: Yes | Predicates: No (All) | Valid: 133 | Discarded: 43
Bag_9 | Samples: Yes | Predicates: No (All) | Valid: 133 | Discarded: 43
Bag_10 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Computing Covariance for Predicates
Metric: covariance
Threshold: 0.01

======================================================================
Processando Grafo - Semente: 0
======================================================================


Total bidirectional pairs found: 101
Removed: Si > -1.67 -> K > -6.69 (1.1759) | Kept: K > -6.69 -> Si > -1.67 (1.2063)
Removed: Si > -2.51 -> Ca ka <= 3.95 (2.3506) | Kept: Ca ka <= 3.95 -> Si > -2.51 (4.5494)
Removed: Si > -2.51 -> Si > -1.67 (4.7914) | Kept: Si > -1.67 -> Si > -2.51 (5.8676)
Removed: K <= 6.26 -> Si > -1.67 (1.2224) | Kept: Si > -1.67 -> K <= 6.26 (4.6818)
Removed: Ca ka <= 1.77 -> K <= 6.26 (0.8722) | Kept: K <= 6.26 -> Ca ka <= 1.77 (6.4170)
Removed: K > -1.46 -> Ca ka <= 1.77 (2.9502) | Kept: Ca ka <= 1.77 -> K > -1.46 (4.3745)
Removed: Si > -0.72 -> K > -1.46 (1.7586) | Kept: K > -1.46 -> Si > -0.72 (2.8194)
Removed: Ca ka > -4.65 -> Si > -0.72 (1.9960) | Kept: Si > -0.72 -> Ca ka > -4.65 (4.0344)
Removed: Ti ka > -0.70 -> Ca kb <= 1.57 (0.5143) | Kept: Ca kb <= 1.57 -> Ti ka > -0.70 (1.4595)
Removed: Fe kb > -0.91 -> Ca kb <= 1.57 (0.5157) | Kept: Ca kb <= 1.57 -> Fe kb > -0.91 (0.9543)
Removed: Fe kb > -0.44 -> Ca kb <= 1.57 (0.4483) | Kept: Ca kb <= 1.57 -> Fe kb > -0.44 (0.4654)
Removed: Fe kb > -0.63 -> Ti ka > -0.86 (1.0042) | Kept: Ti ka > -0.86 -> Fe kb > -0.63 (1.0466)
Removed: Fe kb > -0.91 -> Rh L + Ar > -0.77 (0.3976) | Kept: Rh L + Ar > -0.77 -> Fe kb > -0.91 (0.4051)
Removed: Fe kb > -0.91 -> Fe kb > -0.44 (0.3959) | Kept: Fe kb > -0.44 -> Fe kb > -0.91 (0.4815)
Removed: K <= 2.15 -> Rh L + Ar > -0.77 (0.7424) | Kept: Rh L + Ar > -0.77 -> K <= 2.15 (0.8769)
Removed: Si <= 3.71 -> Rh L + Ar > -0.77 (0.5158) | Kept: Rh L + Ar > -0.77 -> Si <= 3.71 (0.6758)
Removed: Rh L + Ar > -0.77 -> Rh L + Ar > -0.16 (0.3707) | Kept: Rh L + Ar > -0.16 -> Rh L + Ar > -0.77 (0.4329)
Removed: K <= 2.15 -> Ca kb <= 0.62 (0.4177) | Kept: Ca kb <= 0.62 -> K <= 2.15 (0.7535)
Removed: Rh L + Ar > -0.16 -> Ti ka > -0.52 (0.4576) | Kept: Ti ka > -0.52 -> Rh L + Ar > -0.16 (0.8558)
Removed: Rh L + Ar > -1.66 -> Ti ka > -0.52 (0.4218) | Kept: Ti ka > -0.52 -> Rh L + Ar > -1.66 (0.4424)
Removed: Ti ka > -0.52 -> Si <= 3.71 (0.4361) | Kept: Si <= 3.71 -> Ti ka > -0.52 (0.9343)
Removed: background3 > 0.14 -> Rh L + Ar > -0.16 (0.2584) | Kept: Rh L + Ar > -0.16 -> background3 > 0.14 (0.6101)
Removed: Si <= 3.71 -> Ca kb <= 0.62 (0.3886) | Kept: Ca kb <= 0.62 -> Si <= 3.71 (0.3897)
Removed: Rh L + Ar > -1.66 -> Ca kb <= 0.62 (0.4054) | Kept: Ca kb <= 0.62 -> Rh L + Ar > -1.66 (0.7322)
Removed: background3 > 0.14 -> Rh L + Ar > -1.66 (0.3116) | Kept: Rh L + Ar > -1.66 -> background3 > 0.14 (1.0385)
Removed: Rh L + Ar > -1.66 -> Fe kb > -0.44 (0.4228) | Kept: Fe kb > -0.44 -> Rh L + Ar > -1.66 (0.4345)
Removed: background3 > -0.62 -> Rh L + Ar > -1.66 (0.2402) | Kept: Rh L + Ar > -1.66 -> background3 > -0.62 (0.3122)
Removed: Ca kb > -1.81 -> background3 > 0.14 (0.2617) | Kept: background3 > 0.14 -> Ca kb > -1.81 (0.3363)
Removed: K > 2.15 -> background3 > 0.14 (0.3888) | Kept: background3 > 0.14 -> K > 2.15 (0.5919)
Removed: background3 > -0.62 -> Ca kb > -1.81 (0.7847) | Kept: Ca kb > -1.81 -> background3 > -0.62 (1.0733)
Removed: Ca kb > -1.81 -> K > 2.15 (0.2629) | Kept: K > 2.15 -> Ca kb > -1.81 (0.8943)
Removed: Compton scattering > 0.05 -> Fe ka <= 1.10 (0.1745) | Kept: Fe ka <= 1.10 -> Compton scattering > 0.05 (0.7577)
Removed: Ca kb <= -0.59 -> Fe ka <= 1.10 (0.2011) | Kept: Fe ka <= 1.10 -> Ca kb <= -0.59 (0.3969)
Removed: Compton scattering > -0.40 -> Fe ka <= 1.10 (0.1757) | Kept: Fe ka <= 1.10 -> Compton scattering > -0.40 (0.2533)
Removed: Fe ka <= 1.10 -> background3 > -1.28 (0.2541) | Kept: background3 > -1.28 -> Fe ka <= 1.10 (0.4507)
Removed: Compton scattering > -0.40 -> Compton scattering > 0.05 (0.5073) | Kept: Compton scattering > 0.05 -> Compton scattering > -0.40 (0.8482)
Removed: Ca kb <= -0.59 -> Compton scattering > 0.05 (0.2019) | Kept: Compton scattering > 0.05 -> Ca kb <= -0.59 (0.2149)
Removed: Ca kb <= -0.59 -> Compton scattering > -0.40 (0.1857) | Kept: Compton scattering > -0.40 -> Ca kb <= -0.59 (0.1893)
Removed: Compton scattering > -0.88 -> Ca kb <= -0.59 (0.3470) | Kept: Ca kb <= -0.59 -> Compton scattering > -0.88 (0.3955)
Removed: Compton scattering > -0.88 -> K <= -1.46 (0.1565) | Kept: K <= -1.46 -> Compton scattering > -0.88 (0.1792)
Removed: Al > -0.68 -> K <= -1.46 (0.1457) | Kept: K <= -1.46 -> Al > -0.68 (0.1738)
Removed: Rayleight scattering > -0.50 -> K <= -1.46 (0.1104) | Kept: K <= -1.46 -> Rayleight scattering > -0.50 (0.2866)
Removed: K <= -1.46 -> Rayleight scattering > -0.24 (0.1594) | Kept: Rayleight scattering > -0.24 -> K <= -1.46 (0.2731)
Removed: Rayleight scattering > 0.03 -> Rayleight scattering > -0.24 (0.2221) | Kept: Rayleight scattering > -0.24 -> Rayleight scattering > 0.03 (0.2524)
Removed: Rayleight scattering > 0.03 -> Al > -0.68 (0.1441) | Kept: Al > -0.68 -> Rayleight scattering > 0.03 (0.2935)
Removed: Rayleight scattering > 0.03 -> sum Fe > 0.07 (0.1151) | Kept: sum Fe > 0.07 -> Rayleight scattering > 0.03 (0.1496)
Removed: sum Fe > -0.28 -> Al <= 0.62 (0.0978) | Kept: Al <= 0.62 -> sum Fe > -0.28 (0.1072)
Removed: sum Fe > 0.07 -> sum Fe > -0.28 (0.1620) | Kept: sum Fe > -0.28 -> sum Fe > 0.07 (0.2963)
Removed: Al > -0.68 -> sum Fe > -0.28 (0.1566) | Kept: sum Fe > -0.28 -> Al > -0.68 (0.4308)
Removed: Ca ka > -1.50 -> Rayleight scattering > -0.24 (0.1331) | Kept: Rayleight scattering > -0.24 -> Ca ka > -1.50 (0.2671)
Removed: sum Fe > 0.07 -> Ca ka > -1.50 (0.1337) | Kept: Ca ka > -1.50 -> sum Fe > 0.07 (0.2810)
Removed: Ca ka > -1.50 -> Al > -0.68 (0.1365) | Kept: Al > -0.68 -> Ca ka > -1.50 (0.1478)
Removed: Rayleight scattering > -0.50 -> Al > -0.19 (0.1006) | Kept: Al > -0.19 -> Rayleight scattering > -0.50 (0.2143)
Removed: Ti kb > -0.32 -> Rayleight scattering > -0.50 (0.0744) | Kept: Rayleight scattering > -0.50 -> Ti kb > -0.32 (0.1016)
Removed: Al > -0.19 -> sum Fe > -0.60 (0.1075) | Kept: sum Fe > -0.60 -> Al > -0.19 (0.3351)
Removed: Ti kb > -0.32 -> Al <= 0.62 (0.1720) | Kept: Al <= 0.62 -> Ti kb > -0.32 (0.3247)
Removed: Ti kb > -0.32 -> P > 0.08 (0.0868) | Kept: P > 0.08 -> Ti kb > -0.32 (0.1025)
Removed: P > 0.08 -> P > -0.59 (0.0626) | Kept: P > -0.59 -> P > 0.08 (0.1237)
Removed: background2 > 0.35 -> background2 > -0.51 (0.0741) | Kept: background2 > -0.51 -> background2 > 0.35 (0.1835)
Removed: background2 <= -0.51 -> background2 > 0.35 (0.0195) | Kept: background2 > 0.35 -> background2 <= -0.51 (0.0638)
Removed: Cu <= -0.12 -> background2 > 0.35 (0.0383) | Kept: background2 > 0.35 -> Cu <= -0.12 (0.0528)
Removed: background2 <= -0.51 -> P > -0.59 (0.0680) | Kept: P > -0.59 -> background2 <= -0.51 (0.1560)
Removed: background2 <= -0.51 -> Ti kb > 0.03 (0.0719) | Kept: Ti kb > 0.03 -> background2 <= -0.51 (0.1398)
Removed: Ti kb > -0.14 -> background2 > -1.35 (0.0724) | Kept: background2 > -1.35 -> Ti kb > -0.14 (0.1828)
Removed: Ti kb > 0.03 -> Ti kb > -0.14 (0.0585) | Kept: Ti kb > -0.14 -> Ti kb > 0.03 (0.2258)
Removed: Mn <= 1.01 -> Ti ka <= 0.53 (0.0518) | Kept: Ti ka <= 0.53 -> Mn <= 1.01 (0.0561)
Removed: P <= 0.08 -> P <= -0.59 (0.0608) | Kept: P <= -0.59 -> P <= 0.08 (0.0671)
Removed: Ca kb > -0.59 -> P <= -0.59 (0.0538) | Kept: P <= -0.59 -> Ca kb > -0.59 (0.0578)
Removed: sum Fe <= -0.28 -> P <= -0.59 (0.0391) | Kept: P <= -0.59 -> sum Fe <= -0.28 (0.0513)
Removed: P <= 1.06 -> sum Fe <= -0.28 (0.0952) | Kept: sum Fe <= -0.28 -> P <= 1.06 (0.1039)
Removed: P <= 1.06 -> Ni > -0.14 (0.0324) | Kept: Ni > -0.14 -> P <= 1.06 (0.0353)
Removed: Cu <= -0.12 -> background3 <= -0.62 (0.0486) | Kept: background3 <= -0.62 -> Cu <= -0.12 (0.0870)
Removed: Ni > -0.14 -> Fe kb <= 0.33 (0.0413) | Kept: Fe kb <= 0.33 -> Ni > -0.14 (0.0445)
Removed: S <= -0.27 -> Fe kb <= 0.33 (0.0429) | Kept: Fe kb <= 0.33 -> S <= -0.27 (0.0434)
Removed: Ni > -0.14 -> Compton scattering <= -0.40 (0.0266) | Kept: Compton scattering <= -0.40 -> Ni > -0.14 (0.0440)
Removed: S <= 0.55 -> Ca ka > 1.77 (0.0301) | Kept: Ca ka > 1.77 -> S <= 0.55 (0.0346)
Removed: S <= 0.55 -> Ni <= -0.14 (0.0244) | Kept: Ni <= -0.14 -> S <= 0.55 (0.0272)
Removed: Rayleight scattering <= -0.24 -> Cu <= 0.09 (0.0267) | Kept: Cu <= 0.09 -> Rayleight scattering <= -0.24 (0.0347)
Removed: S <= -0.27 -> Al > 0.19 (0.0323) | Kept: Al > 0.19 -> S <= -0.27 (0.0365)
Removed: Ni <= -0.14 -> S <= -0.27 (0.0200) | Kept: S <= -0.27 -> Ni <= -0.14 (0.0344)
Removed: background1 > 0.11 -> Zn <= 0.34 (0.0211) | Kept: Zn <= 0.34 -> background1 > 0.11 (0.0230)
Removed: background1 > 0.11 -> Zn <= 0.10 (0.0149) | Kept: Zn <= 0.10 -> background1 > 0.11 (0.0268)
Removed: background1 > 0.11 -> Cu > -0.55 (0.0160) | Kept: Cu > -0.55 -> background1 > 0.11 (0.0196)
Removed: background2 <= 0.35 -> S <= 0.09 (0.0266) | Kept: S <= 0.09 -> background2 <= 0.35 (0.0661)
Removed: Ti kb <= 0.20 -> Al <= -0.19 (0.0135) | Kept: Al <= -0.19 -> Ti kb <= 0.20 (0.0176)
Removed: background1 <= 0.30 -> Al <= 0.19 (0.0144) | Kept: Al <= 0.19 -> background1 <= 0.30 (0.0255)
Removed: Mn > -0.41 -> Ca kb > 0.62 (0.0121) | Kept: Ca kb > 0.62 -> Mn > -0.41 (0.0124)
Removed: background1 <= 0.30 -> Zn <= 0.34 (0.0187) | Kept: Zn <= 0.34 -> background1 <= 0.30 (0.0339)
Removed: Ni > -0.60 -> Al > 0.19 (0.0148) | Kept: Al > 0.19 -> Ni > -0.60 (0.0255)
Removed: Rayleight scattering <= 0.03 -> Rh L + Ar <= 1.37 (0.0116) | Kept: Rh L + Ar <= 1.37 -> Rayleight scattering <= 0.03 (0.0140)
Removed: Zn <= 0.10 -> background1 <= 0.30 (0.0159) | Kept: background1 <= 0.30 -> Zn <= 0.10 (0.0341)
Removed: Zn <= -0.11 -> Ni > 0.13 (0.0106) | Kept: Ni > 0.13 -> Zn <= -0.11 (0.0146)
Removed: sum Fe <= 0.07 -> Si <= -0.72 (0.0218) | Kept: Si <= -0.72 -> sum Fe <= 0.07 (0.0468)
Removed: Zn > 0.10 -> Ni <= -0.14 (0.0090) | Kept: Ni <= -0.14 -> Zn > 0.10 (0.0094)
Removed: background1 <= -0.08 -> background3 <= 1.47 (0.0089) | Kept: background3 <= 1.47 -> background1 <= -0.08 (0.0132)
Removed: Rayleight scattering <= 0.03 -> Ca kb > 0.62 (0.0111) | Kept: Ca kb > 0.62 -> Rayleight scattering <= 0.03 (0.0155)
Removed: Si <= -1.67 -> Ca kb > 0.62 (0.0145) | Kept: Ca kb > 0.62 -> Si <= -1.67 (0.0153)
Removed: background1 > -0.08 -> Cu > -0.55 (0.0109) | Kept: Cu > -0.55 -> background1 > -0.08 (0.0135)
Removed: background1 > -0.08 -> Cu <= 0.56 (0.0098) | Kept: Cu <= 0.56 -> background1 > -0.08 (0.0160)
Removed: Cu <= 0.56 -> Zn > -0.11 (0.0122) | Kept: Zn > -0.11 -> Cu <= 0.56 (0.0158)
Removed: background1 <= 0.11 -> background3 <= 1.47 (0.0093) | Kept: background3 <= 1.47 -> background1 <= 0.11 (0.0110)

======================================================================
CONSTRUCTED GRAPH SUMMARY
======================================================================
Initial edges: 840 | Removed: 101
Predicate nodes: 125
Metric: Covariance
Weighting by explained variance: ENABLED

======================================================================
Processando Grafo - Semente: 1
======================================================================


Total bidirectional pairs found: 118
Removed: Fe ka > -2.26 -> Fe ka > -3.74 (2.2748) | Kept: Fe ka > -3.74 -> Fe ka > -2.26 (19.5113)
Removed: Si > -1.67 -> Ca ka <= 3.95 (1.1802) | Kept: Ca ka <= 3.95 -> Si > -1.67 (4.3919)
Removed: Si > -1.67 -> Si > -2.51 (4.6611) | Kept: Si > -2.51 -> Si > -1.67 (5.8484)
Removed: K <= 6.26 -> Si > -2.51 (1.1614) | Kept: Si > -2.51 -> K <= 6.26 (3.3814)
Removed: K > -1.46 -> K <= 6.26 (2.9027) | Kept: K <= 6.26 -> K > -1.46 (3.0178)
Removed: Ca ka <= 1.77 -> K <= 6.26 (0.8842) | Kept: K <= 6.26 -> Ca ka <= 1.77 (5.1109)
Removed: Ca ka <= 1.77 -> K > -1.46 (2.6207) | Kept: K > -1.46 -> Ca ka <= 1.77 (2.8436)
Removed: Si > -0.72 -> K > -1.46 (0.7928) | Kept: K > -1.46 -> Si > -0.72 (2.7072)
Removed: Ca kb <= 1.57 -> Rh L + Ar > -0.77 (0.4853) | Kept: Rh L + Ar > -0.77 -> Ca kb <= 1.57 (0.4866)
Removed: Ca kb <= 1.57 -> Ti ka > -0.70 (0.4624) | Kept: Ti ka > -0.70 -> Ca kb <= 1.57 (0.5398)
Removed: Rh L + Ar > -0.77 -> Rh L + Ar > -0.16 (1.2309) | Kept: Rh L + Ar > -0.16 -> Rh L + Ar > -0.77 (1.2550)
Removed: Rh L + Ar > -0.77 -> Si <= 3.71 (0.4833) | Kept: Si <= 3.71 -> Rh L + Ar > -0.77 (0.4921)
Removed: Ca kb <= 0.62 -> Rh L + Ar > -0.77 (0.3864) | Kept: Rh L + Ar > -0.77 -> Ca kb <= 0.62 (0.3993)
Removed: Rh L + Ar > -0.77 -> K <= 2.15 (0.3191) | Kept: K <= 2.15 -> Rh L + Ar > -0.77 (0.3384)
Removed: Fe kb > -0.44 -> Rh L + Ar > -0.16 (0.4214) | Kept: Rh L + Ar > -0.16 -> Fe kb > -0.44 (0.7955)
Removed: K <= 2.15 -> Rh L + Ar > -1.66 (0.3301) | Kept: Rh L + Ar > -1.66 -> K <= 2.15 (0.8580)
Removed: background3 > 0.14 -> K <= 2.15 (0.3088) | Kept: K <= 2.15 -> background3 > 0.14 (0.3270)
Removed: Ca ka <= -1.50 -> Ti ka > -0.86 (0.4145) | Kept: Ti ka > -0.86 -> Ca ka <= -1.50 (0.4275)
Removed: Fe kb > -0.63 -> Ti ka > -0.86 (1.5593) | Kept: Ti ka > -0.86 -> Fe kb > -0.63 (2.5282)
Removed: Ti ka > -0.52 -> Ca ka <= -1.50 (0.4725) | Kept: Ca ka <= -1.50 -> Ti ka > -0.52 (0.7997)
Removed: Ca kb <= 0.62 -> Ca ka <= -1.50 (0.3836) | Kept: Ca ka <= -1.50 -> Ca kb <= 0.62 (1.2542)
Removed: Ca ka <= -1.50 -> K > 2.15 (0.3450) | Kept: K > 2.15 -> Ca ka <= -1.50 (0.4854)
Removed: Ti ka > -0.52 -> Fe kb > -0.63 (0.4227) | Kept: Fe kb > -0.63 -> Ti ka > -0.52 (0.5164)
Removed: Fe kb > -0.44 -> Ti ka > -0.52 (0.4336) | Kept: Ti ka > -0.52 -> Fe kb > -0.44 (1.8183)
Removed: Ti ka > -0.52 -> Ca kb <= 0.62 (0.3900) | Kept: Ca kb <= 0.62 -> Ti ka > -0.52 (0.3917)
Removed: Si <= 3.71 -> Ca kb <= 0.62 (0.7940) | Kept: Ca kb <= 0.62 -> Si <= 3.71 (1.1463)
Removed: background3 > 0.14 -> Si <= 3.71 (0.2655) | Kept: Si <= 3.71 -> background3 > 0.14 (0.3868)
Removed: Ca kb <= 0.62 -> Fe kb > -0.44 (0.3674) | Kept: Fe kb > -0.44 -> Ca kb <= 0.62 (0.4064)
Removed: background3 > 0.14 -> Ca kb > -1.81 (0.5535) | Kept: Ca kb > -1.81 -> background3 > 0.14 (0.5611)
Removed: background3 > -0.62 -> Ca kb > -1.81 (0.7705) | Kept: Ca kb > -1.81 -> background3 > -0.62 (1.0700)
Removed: background3 > 0.14 -> K > 2.15 (1.1044) | Kept: K > 2.15 -> background3 > 0.14 (1.3997)
Removed: background3 > -0.62 -> Fe ka <= 1.10 (0.2148) | Kept: Fe ka <= 1.10 -> background3 > -0.62 (0.4741)
Removed: Compton scattering > 0.05 -> Fe ka <= 1.10 (0.1986) | Kept: Fe ka <= 1.10 -> Compton scattering > 0.05 (0.2413)
Removed: Fe ka <= 1.10 -> background3 > -1.28 (0.2022) | Kept: background3 > -1.28 -> Fe ka <= 1.10 (0.6505)
Removed: Fe ka <= 1.10 -> Compton scattering > -0.40 (0.2463) | Kept: Compton scattering > -0.40 -> Fe ka <= 1.10 (0.3807)
Removed: Ca kb <= -0.59 -> Compton scattering > 0.05 (0.1968) | Kept: Compton scattering > 0.05 -> Ca kb <= -0.59 (0.3498)
Removed: Compton scattering > -0.40 -> Compton scattering > 0.05 (0.4170) | Kept: Compton scattering > 0.05 -> Compton scattering > -0.40 (1.1837)
Removed: Compton scattering > -0.88 -> Ca kb <= -0.59 (0.3605) | Kept: Ca kb <= -0.59 -> Compton scattering > -0.88 (0.3905)
Removed: sum Fe > -0.28 -> Ca kb <= -0.59 (0.1494) | Kept: Ca kb <= -0.59 -> sum Fe > -0.28 (0.1880)
Removed: Ca ka > -1.50 -> K <= -1.46 (0.0778) | Kept: K <= -1.46 -> Ca ka > -1.50 (0.1275)
Removed: background3 > -1.28 -> Compton scattering > -0.40 (0.2193) | Kept: Compton scattering > -0.40 -> background3 > -1.28 (0.7207)
Removed: Al > -0.68 -> Compton scattering > -0.88 (0.1384) | Kept: Compton scattering > -0.88 -> Al > -0.68 (0.2998)
Removed: sum Fe > -0.28 -> Al > -0.68 (0.1483) | Kept: Al > -0.68 -> sum Fe > -0.28 (0.3082)
Removed: Rayleight scattering > -0.24 -> Al > -0.68 (0.1454) | Kept: Al > -0.68 -> Rayleight scattering > -0.24 (0.4505)
Removed: sum Fe > 0.07 -> Al > -0.68 (0.1415) | Kept: Al > -0.68 -> sum Fe > 0.07 (0.2838)
Removed: Compton scattering > -0.88 -> Ca ka > -1.50 (0.1203) | Kept: Ca ka > -1.50 -> Compton scattering > -0.88 (0.1352)
Removed: Compton scattering > -0.88 -> Rayleight scattering > 0.03 (0.1164) | Kept: Rayleight scattering > 0.03 -> Compton scattering > -0.88 (0.2499)
Removed: Ca ka > -1.50 -> sum Fe > -0.28 (0.1207) | Kept: sum Fe > -0.28 -> Ca ka > -1.50 (0.1400)
Removed: Ca ka > -1.50 -> sum Fe > 0.07 (0.1307) | Kept: sum Fe > 0.07 -> Ca ka > -1.50 (0.1332)

,Predicate_Cov_Seed_0,Predicate_Cov_Seed_1,Predicate_Cov_Seed_2,Predicate_Cov_Seed_3
0,Fe ka > -3.05,Fe ka > -3.05,Fe ka > -3.05,Fe ka > -3.05
1,Fe ka > -3.74,Fe ka > -3.74,Fe ka > -3.74,Fe ka > -3.74
2,Fe ka > -2.26,Fe ka > -2.26,Fe ka > -2.26,Fe ka > -2.26
3,K > -6.69,K > -6.69,K > -6.69,K > -6.69
4,Ca ka <= 3.95,Ca ka <= 3.95,Ca ka <= 3.95,Ca ka <= 3.95
...,...,...,...,...
124,Zn > -0.37,Class_A,sum Fe <= 0.62,Zn > 0.10
125,Class_A,Class_B,background2 <= 1.51,Zn <= -0.11
126,Class_B,NaN,Class_A,Fe ka <= -3.05
127,NaN,NaN,Class_B,Class_A
128,NaN,NaN,NaN,Class_B

In [8]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_cov_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_cov = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_cov = lrc_summed_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_cov = lrc_summed_df_cov.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
#lrc_summed_unique_df_cov = lrc_summed_unique_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_cov

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Fe ka > -3.05,21.730280,Fe ka,-3.05,>
1,K > -6.69,11.048593,K,-6.69,>
2,Ca ka <= 3.95,8.618784,Ca ka,3.95,<=
3,Si > -2.51,7.521654,Si,-2.51,>
4,Ti ka > -0.70,2.030123,Ti ka,-0.70,>
5,Fe kb > -0.63,1.836228,Fe kb,-0.63,>
6,Ca kb <= 1.57,1.566439,Ca kb,1.57,<=
7,Rh L + Ar > -0.77,1.434719,Rh L + Ar,-0.77,>
8,background3 > 0.14,1.241904,background3,0.14,>
9,Compton scattering > -0.40,0.975374,Compton scattering,-0.40,>
10,Al > -0.68,0.655427,Al,-0.68,>
11,Rayleight scattering > 0.03,0.649024,Rayleight scattering,0.03,>
12,sum Fe > 0.07,0.573064,sum Fe,0.07,>
13,P > -1.23,0.460184,P,-1.23,>
14,Ti kb > -0.14,0.453927,Ti kb,-0.14,>
15,background2 <= -0.51,0.442148,background2,-0.51,<=
16,Mn > 0.23,0.427096,Mn,0.23,>
17,Cu <= -0.12,0.337172,Cu,-0.12,<=
18,S <= 0.55,0.323362,S,0.55,<=
19,Ni <= 0.13,0.309545,Ni,0.13,<=
20,Zn <= -0.37,0.298782,Zn,-0.37,<=
21,background1 > 0.11,0.265277,background1,0.11,>
22,Class_B,0.000000,None,None,None

In [9]:
# Criar zone_sums_df para dados NÃO pré-processados (Xcalclass)
spectral_zones_original = exp.extract_spectral_zones(Xcalclass, spectral_cuts)
zones_original = exp.aggregate_spectral_zones_pca(spectral_zones_original) # apca aggregation

# Aplicar o mapeamento
lrc_summed_df_cov_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_cov,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_cov_natural

Zone 'Al': VE = 95.14%, dim = 12 variables
Zone 'Si': VE = 99.71%, dim = 12 variables
Zone 'P': VE = 97.48%, dim = 16 variables
Zone 'S': VE = 93.90%, dim = 15 variables
Zone 'Rh L + Ar': VE = 96.86%, dim = 34 variables
Zone 'K': VE = 99.17%, dim = 19 variables
Zone 'Ca ka': VE = 93.72%, dim = 21 variables
Zone 'Ca kb': VE = 98.07%, dim = 26 variables
Zone 'Ti ka': VE = 98.49%, dim = 15 variables
Zone 'Ti kb': VE = 76.99%, dim = 22 variables
Zone 'background1': VE = 66.94%, dim = 33 variables
Zone 'Mn': VE = 95.57%, dim = 20 variables
Zone 'Fe ka': VE = 99.73%, dim = 34 variables
Zone 'Fe kb': VE = 94.82%, dim = 23 variables
Zone 'Ni': VE = 79.28%, dim = 25 variables
Zone 'Cu': VE = 84.38%, dim = 39 variables
Zone 'Zn': VE = 82.21%, dim = 19 variables
Zone 'background2': VE = 86.54%, dim = 215 variables
Zone 'sum Fe': VE = 88.64%, dim = 27 variables
Zone 'background3': VE = 87.63%, dim = 219 variables
Zone 'Compton scattering': VE = 89.25%, dim = 85 variables
Zone 'Rayleight scattering': VE = 84.76%, dim = 55 variables

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,Fe ka > -3.05,21.730280,Fe ka,-3.05,>,-11.993967,102.0,0.012499,Fe ka > -11.993967
1,Fe ka > -3.74,18.176011,Fe ka,-3.74,>,-14.394181,68.0,0.017162,Fe ka > -14.394181
2,Fe ka > -2.26,14.346492,Fe ka,-2.26,>,-8.585461,77.0,0.009247,Fe ka > -8.585461
3,K > -6.69,11.048593,K,-6.69,>,-65.671272,79.0,0.023761,K > -65.671272
4,Ca ka <= 3.95,8.618784,Ca ka,3.95,<=,24.763583,89.0,0.045885,Ca ka <= 24.763583
...,...,...,...,...,...,...,...,...,...
125,Zn > 0.10,0.221977,Zn,0.10,>,0.231960,7.0,0.000820,Zn > 0.231960
126,background1 <= -0.08,0.215201,background1,-0.08,<=,-0.162772,3.0,0.007259,background1 <= -0.162772
127,Rayleight scattering <= 0.53,0.198331,Rayleight scattering,0.53,<=,0.681638,73.0,0.012780,Rayleight scattering <= 0.681638
128,Class_B,0.000000,None,None,None,NaN,NaN,NaN,None
129,Class_A,0.000000,None,None,None,NaN,NaN,NaN,None

## Reconstrução de Thresholds Multivariados

Agora vamos pegar os thresholds dos predicados mais importantes e reconstruí-los como espectros completos.

In [10]:
import plotly.graph_objects as go

n = 0
zone_name = lrc_summed_df_cov_natural.iloc[n]['Zone']
threshold_score = float(lrc_summed_df_cov_natural.iloc[n]['Threshold_Natural'])  # Corrigido: usa n em vez de 7

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
print(f"  - Range de energias: {threshold_spectrum.index[0]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_cov_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona 'Fe ka':
  - Dimensão: 34 variáveis espectrais
  - Range de energias: 6.1 - 6.76
  - Variância explicada pela PC1: 99.73%

In [11]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = exp.calculate_predicate_perturbation(
        estimator=mlp_model[3],
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        #perturbation_value=0,
        perturbation_mode='median', # valores entre 'mean' ou 'min'
        stats_source='full', # full indica usar todas as amostras para calcular estatísticas enquanto que 'fold' usa apenas as amostras do fold atual
        #metric='mean_abs_diff',   # Média com sinal (pode ser negativo)
        aim='classification',
        metric='probability_shift', 
        verbose=True
    )

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graph(
        bags_result=all_results_pert[seed]['bags_result'],
        predicate_ranking_dict=all_results_pert[seed]['pert_results_dict'],
        metric_column='Perturbation',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )

    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_2 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_3 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_4 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_5 | Samples: Yes | Predicates: No (All) | Valid: 133 | Discarded: 43
Bag_6 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_7 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_8 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_9 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_10 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
======================================================================
PERTURBATION IMPORTANCE FOR PREDICATES
======================================================================
Task type (aim): classification
Perturbation mode: median
Statistics source: full
Metric: probability_shift
Total folds: 10


[Bag_1] Processing 132 predicates...
  Predicate: Al > -0.68 (n=87)
    Zone: 12 columns
    Importance: 0.002615
  Predicate: Al <= -0.19 (n=43)
    Zone: 12 columns
    Importance: 0.002210
  Predicate: Al > -0.19 (n=65)
    Zone: 12 columns
    Importance: 0.002820
  Predicate: Al <= 0.19 (n=67)
    Zone: 12 columns
    Importance: 0.001781
  Predicate: Al > 0.19 (n=41)
    Zone: 12 columns
    Importance: 0.003878
  Predicate: Al <= 0.62 (n=87)
    Zone: 12 columns
    Importance: 0.002238
  Predicate: Si > -2.51 (n=83)
    Zone: 12 columns
    Importance: 0.008912
  Predicate: Si <= -1.67 (n=45)
    Zone: 12 columns
    Importance: 0.015585
  Predicate: Si > -1.67 (n=63)
    Zone: 12 columns
    Importance: 0.009223
  Predicate: Si <= -0.72 (n=65)
    Zone: 12 columns
    Importance: 0.011166
  Predicate: Si > -0.72 (n=43)
    Zone: 12 columns
    Importance: 0.012944
  Predicate: Si <= 3.71 (n=85)
    Zone: 12 columns
    Importance: 0.011602
  Predicate: P > -1.23 (n=88)
    Zone: 16 columns
    Importance: 0.004711
  Predicate: P <= -0.59 (n=42)
    Zone: 16 columns
    Importance: 0.005494
  Predicate: P > -0.59 (n=66)
    Zone: 16 columns
    Importance: 0.005002
  Predicate: P <= 0.08 (n=63)
    Zone: 16 columns
    Importance: 0.004158
  Predicate: P > 0.08 (n=45)
    Zone: 16 columns
    Importance: 0.006642
  Predicate: P <= 1.06 (n=84)
    Zone: 16 columns
    Importance: 0.004323
  Predicate: S > -0.55 (n=86)
    Zone: 15 columns
    Importance: 0.006967
  Predicate: S <= -0.27 (n=43)
    Zone: 15 columns
    Importance: 0.004163
  Predicate: S > -0.27 (n=65)
    Zone: 15 columns
    Importance: 0.008611
  Predicate: S <= 0.09 (n=62)
    Zone: 15 columns
    Importance: 0.003226
  Predicate: S > 0.09 (n=46)
    Zone: 15 columns
    Importance: 0.011711
  Predicate: S <= 0.55 (n=84)
    Zone: 15 columns
    Importance: 0.004165
  Predicate: Rh L + Ar > -1.66 (n=90)
    Zone: 34 columns
    Importance: 0.006357
  Predicate: Rh L + Ar <= -0.77 (n=37)
    Zone: 34 columns
    Importance: 0.007506
  Predicate: Rh L + Ar > -0.77 (n=71)
    Zone: 34 columns
    Importance: 0.006913
  Predicate: Rh L + Ar <= -0.16 (n=63)
    Zone: 34 columns
    Importance: 0.005086
  Predicate: Rh L + Ar > -0.16 (n=45)
    Zone: 34 columns
    Importance: 0.009959
  Predicate: Rh L + Ar <= 1.37 (n=89)
    Zone: 34 columns
    Importance: 0.005983
  Predicate: K > -6.69 (n=87)
    Zone: 19 columns
    Importance: 0.027684
  Predicate: K <= -1.46 (n=42)
    Zone: 19 columns
    Importance: 0.032802
  Predicate: K > -1.46 (n=66)
    Zone: 19 columns
    Importance: 0.027200
  Predicate: K <= 2.15 (n=66)
    Zone: 19 columns
    Importance: 0.024225
  Predicate: K > 2.15 (n=42)
    Zone: 19 columns
    Importance: 0.037478
  Predicate: K <= 6.26 (n=86)
    Zone: 19 columns
    Importance: 0.025062
  Predicate: Ca ka > -4.65 (n=86)
    Zone: 21 columns
    Importance: 0.031481
  Predicate: Ca ka <= -1.50 (n=44)
    Zone: 21 columns
    Importance: 0.041004
  Predicate: Ca ka > -1.50 (n=64)
    Zone: 21 columns
    Importance: 0.026524
  Predicate: Ca ka <= 1.77 (n=67)
    Zone: 21 columns
    Importance: 0.031893
  Predicate: Ca ka > 1.77 (n=41)
    Zone: 21 columns
    Importance: 0.033290
  Predicate: Ca ka <= 3.95 (n=87)
    Zone: 21 columns
    Importance: 0.030717
  Predicate: Ca kb > -1.81 (n=86)
    Zone: 26 columns
    Importance: 0.009046
  Predicate: Ca kb <= -0.59 (n=45)
    Zone: 26 columns
    Importance: 0.012815
  Predicate: Ca kb > -0.59 (n=63)
    Zone: 26 columns
    Importance: 0.006080
  Predicate: Ca kb <= 0.62 (n=66)
    Zone: 26 columns
    Importance: 0.010258
  Predicate: Ca kb > 0.62 (n=42)
    Zone: 26 columns
    Importance: 0.006731
  Predicate: Ca kb <= 1.57 (n=87)
    Zone: 26 columns
    Importance: 0.009310
  Predicate: Ti ka > -0.86 (n=87)
    Zone: 15 columns
    Importance: 0.003676
  Predicate: Ti ka <= -0.70 (n=44)
    Zone: 15 columns
    Importance: 0.008756
  Predicate: Ti ka > -0.70 (n=64)
    Zone: 15 columns
    Importance: 0.003404
  Predicate: Ti ka <= -0.52 (n=63)
    Zone: 15 columns
    Importance: 0.006443
  Predicate: Ti ka > -0.52 (n=45)
    Zone: 15 columns
    Importance: 0.004383
  Predicate: Ti ka <= 0.53 (n=87)
    Zone: 15 columns
    Importance: 0.005718
  Predicate: Ti kb > -0.32 (n=88)
    Zone: 22 columns
    Importance: 0.001724
  Predicate: Ti kb <= -0.14 (n=45)
    Zone: 22 columns
    Importance: 0.006045
  Predicate: Ti kb > -0.14 (n=63)
    Zone: 22 columns
    Importance: 0.001461
  Predicate: Ti kb <= 0.03 (n=66)
    Zone: 22 columns
    Importance: 0.004402
  Predicate: Ti kb > 0.03 (n=42)
    Zone: 22 columns
    Importance: 0.001751
  Predicate: Ti kb <= 0.20 (n=86)
    Zone: 22 columns
    Importance: 0.003851
  Predicate: background1 > -0.26 (n=90)
    Zone: 33 columns
    Importance: 0.001563
  Predicate: background1 <= -0.08 (n=43)
    Zone: 33 columns
    Importance: 0.002978
  Predicate: background1 > -0.08 (n=65)
    Zone: 33 columns
    Importance: 0.001544
  Predicate: background1 <= 0.11 (n=70)
    Zone: 33 columns
    Importance: 0.002073
  Predicate: background1 > 0.11 (n=38)
    Zone: 33 columns
    Importance: 0.002192
  Predicate: background1 <= 0.30 (n=91)
    Zone: 33 columns
    Importance: 0.001914
  Predicate: Mn > -1.22 (n=88)
    Zone: 20 columns
    Importance: 0.005754
  Predicate: Mn <= -0.41 (n=43)
    Zone: 20 columns
    Importance: 0.013083
  Predicate: Mn > -0.41 (n=65)
    Zone: 20 columns
    Importance: 0.005554
  Predicate: Mn <= 0.23 (n=67)
    Zone: 20 columns
    Importance: 0.009011
  Predicate: Mn > 0.23 (n=41)
    Zone: 20 columns
    Importance: 0.007801
  Predicate: Mn <= 1.01 (n=90)
    Zone: 20 columns
    Importance: 0.008069
  Predicate: Fe ka > -3.74 (n=86)
    Zone: 34 columns
    Importance: 0.013193
  Predicate: Fe ka <= -3.05 (n=44)
    Zone: 34 columns
    Importance: 0.020970
  Predicate: Fe ka > -3.05 (n=64)
    Zone: 34 columns
    Importance: 0.014450
  Predicate: Fe ka <= -2.26 (n=63)
    Zone: 34 columns
    Importance: 0.016134
  Predicate: Fe ka > -2.26 (n=45)
    Zone: 34 columns
    Importance: 0.018467
  Predicate: Fe ka <= 1.10 (n=87)
    Zone: 34 columns
    Importance: 0.015249
  Predicate: Fe kb > -0.91 (n=87)
    Zone: 23 columns
    Importance: 0.002361
  Predicate: Fe kb <= -0.63 (n=41)
    Zone: 23 columns
    Importance: 0.005824
  Predicate: Fe kb > -0.63 (n=67)
    Zone: 23 columns
    Importance: 0.002272
  Predicate: Fe kb <= -0.44 (n=66)
    Zone: 23 columns
    Importance: 0.004157
  Predicate: Fe kb > -0.44 (n=42)
    Zone: 23 columns
    Importance: 0.002778
  Predicate: Fe kb <= 0.33 (n=87)
    Zone: 23 columns
    Importance: 0.004181
  Predicate: Ni > -0.60 (n=88)
    Zone: 25 columns
    Importance: 0.003641
  Predicate: Ni <= -0.14 (n=44)
    Zone: 25 columns
    Importance: 0.002244
  Predicate: Ni > -0.14 (n=64)
    Zone: 25 columns
    Importance: 0.004245
  Predicate: Ni <= 0.13 (n=64)
    Zone: 25 columns
    Importance: 0.002548
  Predicate: Ni > 0.13 (n=44)
    Zone: 25 columns
    Importance: 0.004712
  Predicate: Ni <= 0.59 (n=90)
    Zone: 25 columns
    Importance: 0.002618
  Predicate: Cu > -0.55 (n=89)
    Zone: 39 columns
    Importance: 0.004339
  Predicate: Cu <= -0.12 (n=44)
    Zone: 39 columns
    Importance: 0.004386
  Predicate: Cu > -0.12 (n=64)
    Zone: 39 columns
    Importance: 0.004690
  Predicate: Cu <= 0.09 (n=64)
    Zone: 39 columns
    Importance: 0.003235
  Predicate: Cu > 0.09 (n=44)
    Zone: 39 columns
    Importance: 0.006502
  Predicate: Cu <= 0.56 (n=92)
    Zone: 39 columns
    Importance: 0.003515
  Predicate: Zn > -0.37 (n=87)
    Zone: 19 columns
    Importance: 0.000517
  Predicate: Zn <= -0.11 (n=41)
    Zone: 19 columns
    Importance: 0.001044
  Predicate: Zn > -0.11 (n=67)
    Zone: 19 columns
    Importance: 0.000472
  Predicate: Zn <= 0.10 (n=66)
    Zone: 19 columns
    Importance: 0.000835
  Predicate: Zn > 0.10 (n=42)
    Zone: 19 columns
    Importance: 0.000460
  Predicate: Zn <= 0.34 (n=90)
    Zone: 19 columns
    Importance: 0.000691
  Predicate: background2 > -1.35 (n=88)
    Zone: 215 columns
    Importance: 0.006488
  Predicate: background2 <= -0.51 (n=45)
    Zone: 215 columns
    Importance: 0.005068
  Predicate: background2 > -0.51 (n=63)
    Zone: 215 columns
    Importance: 0.007744
  Predicate: background2 <= 0.35 (n=67)
    Zone: 215 columns
    Importance: 0.004651
  Predicate: background2 > 0.35 (n=41)
    Zone: 215 columns
    Importance: 0.009862
  Predicate: background2 <= 1.51 (n=89)
    Zone: 215 columns
    Importance: 0.004928
  Predicate: sum Fe > -0.60 (n=89)
    Zone: 27 columns
    Importance: 0.003629
  Predicate: sum Fe <= -0.28 (n=44)
    Zone: 27 columns
    Importance: 0.004814
  Predicate: sum Fe > -0.28 (n=64)
    Zone: 27 columns
    Importance: 0.003794
  Predicate: sum Fe <= 0.07 (n=69)
    Zone: 27 columns
    Importance: 0.003563
  Predicate: sum Fe > 0.07 (n=39)
    Zone: 27 columns
    Importance: 0.005353
  Predicate: sum Fe <= 0.62 (n=89)
    Zone: 27 columns
    Importance: 0.003720
  Predicate: background3 > -1.28 (n=88)
    Zone: 219 columns
    Importance: 0.008639
  Predicate: background3 <= -0.62 (n=42)
    Zone: 219 columns
    Importance: 0.010590
  Predicate: background3 > -0.62 (n=66)
    Zone: 219 columns
    Importance: 0.008894
  Predicate: background3 <= 0.14 (n=67)
    Zone: 219 columns
    Importance: 0.007588
  Predicate: background3 > 0.14 (n=41)
    Zone: 219 columns
    Importance: 0.012766
  Predicate: background3 <= 1.47 (n=90)
    Zone: 219 columns
    Importance: 0.008326
  Predicate: Compton scattering > -0.88 (n=86)
    Zone: 85 columns
    Importance: 0.003321
  Predicate: Compton scattering <= -0.40 (n=42)
    Zone: 85 columns
    Importance: 0.003546
  Predicate: Compton scattering > -0.40 (n=66)
    Zone: 85 columns
    Importance: 0.003256
  Predicate: Compton scattering <= 0.05 (n=68)
    Zone: 85 columns
    Importance: 0.002888
  Predicate: Compton scattering > 0.05 (n=40)
    Zone: 85 columns
    Importance: 0.004186
  Predicate: Compton scattering <= 0.87 (n=88)
    Zone: 85 columns
    Importance: 0.003317
  Predicate: Rayleight scattering > -0.50 (n=88)
    Zone: 55 columns
    Importance: 0.001375
  Predicate: Rayleight scattering <= -0.24 (n=43)
    Zone: 55 columns
    Importance: 0.001829
  Predicate: Rayleight scattering > -0.24 (n=65)
    Zone: 55 columns
    Importance: 0.001057
  Predicate: Rayleight scattering <= 0.03 (n=67)
    Zone: 55 columns
    Importance: 0.001370
  Predicate: Rayleight scattering > 0.03 (n=41)
    Zone: 55 columns
    Importance: 0.001357
  Predicate: Rayleight scattering <= 0.53 (n=89)
    Zone: 55 columns
    Importance: 0.001427

[Bag_2] Processing 132 predicates...
  Predicate: Al > -0.68 (n=84)
    Zone: 12 columns
    Importance: 0.003287
  Predicate: Al <= -0.19 (n=46)
    Zone: 12 columns
    Importance: 0.002358
  Predicate: Al > -0.19 (n=62)
    Zone: 12 columns
    Importance: 0.003679
  Predicate: Al <= 0.19 (n=66)
    Zone: 12 columns
    Importance: 0.001969
  Predicate: Al > 0.19 (n=42)
    Zone: 12 columns
    Importance: 0.004919
  Predicate: Al <= 0.62 (n=86)
    Zone: 12 columns
    Importance: 0.002427
  Predicate: Si > -2.51 (n=83)
    Zone: 12 columns
    Importance: 0.008147
  Predicate: Si <= -1.67 (n=47)
    Zone: 12 columns
    Importance: 0.015960
  Predicate: Si > -1.67 (n=61)
    Zone: 12 columns
    Importance: 0.008435
  Predicate: Si <= -0.72 (n=68)
    Zone: 12 columns
    Importance: 0.011412
  Predicate: Si > -0.72 (n=40)
    Zone: 12 columns
    Importance: 0.012216
  Predicate: Si <= 3.71 (n=87)
    Zone: 12 columns
    Importance: 0.011689
  Predicate: P > -1.23 (n=84)
    Zone: 16 columns
    Importance: 0.004983
  Predicate: P <= -0.59 (n=44)
    Zone: 16 columns
    Importance: 0.005675
  Predicate: P > -0.59 (n=64)
    Zone: 16 columns
    Importance: 0.005278
  Predicate: P <= 0.08 (n=65)
    Zone: 16 columns
    Importance: 0.004392
  Predicate: P > 0.08 (n=43)
    Zone: 16 columns
    Importance: 0.007022
  Predicate: P <= 1.06 (n=87)
    Zone: 16 columns
    Importance: 0.004687
  Predicate: S > -0.55 (n=87)
    Zone: 15 columns
    Importance: 0.007959
  Predicate: S <= -0.27 (n=44)
    Zone: 15 columns
    Importance: 0.003909
  Predicate: S > -0.27 (n=64)
    Zone: 15 columns
    Importance: 0.010078
  Predicate: S <= 0.09 (n=66)
    Zone: 15 columns
    Importance: 0.002931
  Predicate: S > 0.09 (n=42)
    Zone: 15 columns
    Importance: 0.014847
  Predicate: S <= 0.55 (n=87)
    Zone: 15 columns
    Importance: 0.003852
  Predicate: Rh L + Ar > -1.66 (n=88)
    Zone: 34 columns
    Importance: 0.007509
  Predicate: Rh L + Ar <= -0.77 (n=42)
    Zone: 34 columns
    Importance: 0.006861
  Predicate: Rh L + Ar > -0.77 (n=66)
    Zone: 34 columns
    Importance: 0.008648
  Predicate: Rh L + Ar <= -0.16 (n=67)
    Zone: 34 columns
    Importance: 0.004933
  Predicate: Rh L + Ar > -0.16 (n=41)
    Zone: 34 columns
    Importance: 0.012888
  Predicate: Rh L + Ar <= 1.37 (n=90)
    Zone: 34 columns
    Importance: 0.005964
  Predicate: K > -6.69 (n=85)
    Zone: 19 columns
    Importance: 0.034851
  Predicate: K <= -1.46 (n=45)
    Zone: 19 columns
    Importance: 0.037180
  Predicate: K > -1.46 (n=63)
    Zone: 19 columns
    Importance: 0.036149
  Predicate: K <= 2.15 (n=64)
    Zone: 19 columns
    Importance: 0.028893
  Predicate: K > 2.15 (n=44)
    Zone: 19 columns
    Importance: 0.047758
  Predicate: K <= 6.26 (n=87)
    Zone: 19 columns
    Importance: 0.028152
  Predicate: Ca ka > -4.65 (n=89)
    Zone: 21 columns
    Importance: 0.032784
  Predicate: Ca ka <= -1.50 (n=41)
    Zone: 21 columns
    Importance: 0.048204
  Predicate: Ca ka > -1.50 (n=67)
    Zone: 21 columns
    Importance: 0.027077
  Predicate: Ca ka <= 1.77 (n=67)
    Zone: 21 columns
    Importance: 0.035483
  Predicate: Ca ka > 1.77 (n=41)
    Zone: 21 columns
    Importance: 0.034467
  Predicate: Ca ka <= 3.95 (n=87)
    Zone: 21 columns
    Importance: 0.033334
  Predicate: Ca kb > -1.81 (n=89)
    Zone: 26 columns
    Importance: 0.009225
  Predicate: Ca kb <= -0.59 (n=41)
    Zone: 26 columns
    Importance: 0.014655
  Predicate: Ca kb > -0.59 (n=67)
    Zone: 26 columns
    Importance: 0.005925
  Predicate: Ca kb <= 0.62 (n=66)
    Zone: 26 columns
    Importance: 0.010887
  Predicate: Ca kb > 0.62 (n=42)
    Zone: 26 columns
    Importance: 0.006650
  Predicate: Ca kb <= 1.57 (n=87)
    Zone: 26 columns
    Importance: 0.009613
  Predicate: Ti ka > -0.86 (n=84)
    Zone: 15 columns
    Importance: 0.003200
  Predicate: Ti ka <= -0.70 (n=45)
    Zone: 15 columns
    Importance: 0.009931
  Predicate: Ti ka > -0.70 (n=63)
    Zone: 15 columns
    Importance: 0.002739
  Predicate: Ti ka <= -0.52 (n=67)
    Zone: 15 columns
    Importance: 0.007012
  Predicate: Ti ka > -0.52 (n=41)
    Zone: 15 columns
    Importance: 0.003650
  Predicate: Ti ka <= 0.53 (n=88)
    Zone: 15 columns
    Importance: 0.006146
  Predicate: Ti kb > -0.32 (n=84)
    Zone: 22 columns
    Importance: 0.001706
  Predicate: Ti kb <= -0.14 (n=44)
    Zone: 22 columns
    Importance: 0.007625
  Predicate: Ti kb > -0.14 (n=64)
    Zone: 22 columns
    Importance: 0.001393
  Predicate: Ti kb <= 0.03 (n=65)
    Zone: 22 columns
    Importance: 0.005423
  Predicate: Ti kb > 0.03 (n=43)
    Zone: 22 columns
    Importance: 0.001678
  Predicate: Ti kb <= 0.20 (n=86)
    Zone: 22 columns
    Importance: 0.004578
  Predicate: background1 > -0.26 (n=89)
    Zone: 33 columns
    Importance: 0.001551
  Predicate: background1 <= -0.08 (n=44)
    Zone: 33 columns
    Importance: 0.003675
  Predicate: background1 > -0.08 (n=64)
    Zone: 33 columns
    Importance: 0.001511
  Predicate: background1 <= 0.11 (n=65)
    Zone: 33 columns
    Importance: 0.002690
  Predicate: background1 > 0.11 (n=43)
    Zone: 33 columns
    Importance: 0.001943
  Predicate: background1 <= 0.30 (n=84)
    Zone: 33 columns
    Importance: 0.002313
  Predicate: Mn > -1.22 (n=85)
    Zone: 20 columns
    Importance: 0.006377
  Predicate: Mn <= -0.41 (n=42)
    Zone: 20 columns
    Importance: 0.017757
  Predicate: Mn > -0.41 (n=66)
    Zone: 20 columns
    Importance: 0.005801
  Predicate: Mn <= 0.23 (n=66)
    Zone: 20 columns
    Importance: 0.011888
  Predicate: Mn > 0.23 (n=42)
    Zone: 20 columns
    Importance: 0.008191
  Predicate: Mn <= 1.01 (n=86)
    Zone: 20 columns
    Importance: 0.010436
  Predicate: Fe ka > -3.74 (n=85)
    Zone: 34 columns
    Importance: 0.011860
  Predicate: Fe ka <= -3.05 (n=45)
    Zone: 34 columns
    Importance: 0.021880
  Predicate: Fe ka > -3.05 (n=63)
    Zone: 34 columns
    Importance: 0.012664
  Predicate: Fe ka <= -2.26 (n=68)
    Zone: 34 columns
    Importance: 0.016476
  Predicate: Fe ka > -2.26 (n=40)
    Zone: 34 columns
    Importance: 0.016553
  Predicate: Fe ka <= 1.10 (n=89)
    Zone: 34 columns
    Importance: 0.015626
  Predicate: Fe kb > -0.91 (n=87)
    Zone: 23 columns
    Importance: 0.002370
  Predicate: Fe kb <= -0.63 (n=41)
    Zone: 23 columns
    Importance: 0.007384
  Predicate: Fe kb > -0.63 (n=67)
    Zone: 23 columns
    Importance: 0.002199
  Predicate: Fe kb <= -0.44 (n=64)
    Zone: 23 columns
    Importance: 0.005256
  Predicate: Fe kb > -0.44 (n=44)
    Zone: 23 columns
    Importance: 0.002583
  Predicate: Fe kb <= 0.33 (n=89)
    Zone: 23 columns
    Importance: 0.004849
  Predicate: Ni > -0.60 (n=87)
    Zone: 25 columns
    Importance: 0.003542
  Predicate: Ni <= -0.14 (n=42)
    Zone: 25 columns
    Importance: 0.002948
  Predicate: Ni > -0.14 (n=66)
    Zone: 25 columns
    Importance: 0.004029
  Predicate: Ni <= 0.13 (n=62)
    Zone: 25 columns
    Importance: 0.002936
  Predicate: Ni > 0.13 (n=46)
    Zone: 25 columns
    Importance: 0.004516
  Predicate: Ni <= 0.59 (n=86)
    Zone: 25 columns
    Importance: 0.002974
  Predicate: Cu > -0.55 (n=88)
    Zone: 39 columns
    Importance: 0.004486
  Predicate: Cu <= -0.12 (n=41)
    Zone: 39 columns
    Importance: 0.005943
  Predicate: Cu > -0.12 (n=67)
    Zone: 39 columns
    Importance: 0.004726
  Predicate: Cu <= 0.09 (n=61)
    Zone: 39 columns
    Importance: 0.004209
  Predicate: Cu > 0.09 (n=47)
    Zone: 39 columns
    Importance: 0.006459
  Predicate: Cu <= 0.56 (n=87)
    Zone: 39 columns
    Importance: 0.004303
  Predicate: Zn > -0.37 (n=87)
    Zone: 19 columns
    Importance: 0.000538
  Predicate: Zn <= -0.11 (n=42)
    Zone: 19 columns
    Importance: 0.001187
  Predicate: Zn > -0.11 (n=66)
    Zone: 19 columns
    Importance: 0.000521
  Predicate: Zn <= 0.10 (n=62)
    Zone: 19 columns
    Importance: 0.000974
  Predicate: Zn > 0.10 (n=46)
    Zone: 19 columns
    Importance: 0.000518
  Predicate: Zn <= 0.34 (n=87)

,Predicate_pert_Seed_0,Predicate_pert_Seed_1,Predicate_pert_Seed_2,Predicate_pert_Seed_3
0,K > 2.15,K > 2.15,Ca ka <= -1.50,Ca ka <= -1.50
1,K <= -1.46,Ca ka <= -1.50,K > 2.15,K > -1.46
2,Ca ka <= 1.77,K <= -1.46,Ca ka <= 1.77,Ca ka > 1.77
3,K > -1.46,Ca ka > -4.65,K > -1.46,K > 2.15
4,Ca ka <= -1.50,K > -1.46,Ca ka > 1.77,K > -6.69
...,...,...,...,...
131,Zn > -0.11,Zn > 0.10,Zn > 0.10,Zn > -0.37
132,Zn > 0.10,Class_A,Zn > -0.11,Zn > -0.11
133,Class_A,Class_B,Class_A,Zn > 0.10
134,Class_B,NaN,Class_B,Class_A
135,NaN,NaN,NaN,Class_B

In [12]:
all_results_pert[0]['pert_results_dict']['Bag_1']

          Predicate  Perturbation
0    Ca ka <= -1.50      0.041004
1          K > 2.15      0.037478
2      Ca ka > 1.77      0.033290
3        K <= -1.46      0.032802
4     Ca ka <= 1.77      0.031893
..              ...           ...
127      Zn <= 0.10      0.000835
128      Zn <= 0.34      0.000691
129      Zn > -0.37      0.000517
130      Zn > -0.11      0.000472
131       Zn > 0.10      0.000460

[132 rows x 2 columns]

In [13]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_pert_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_pert = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_pert = lrc_summed_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_pert = lrc_summed_df_pert.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_pert = lrc_summed_unique_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_pert

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,K > 2.15,6.785412,K,2.15,>
1,Ca ka <= -1.50,6.421293,Ca ka,-1.50,<=
2,Fe ka <= -3.05,2.173922,Fe ka,-3.05,<=
3,Si <= -1.67,1.540259,Si,-1.67,<=
4,Mn <= -0.41,1.296415,Mn,-0.41,<=
5,Ca kb <= -0.59,1.240538,Ca kb,-0.59,<=
6,S > 0.55,1.198419,S,0.55,>
7,background3 > 0.14,1.116352,background3,0.14,>
8,Rh L + Ar > -0.16,0.996417,Rh L + Ar,-0.16,>
9,Fe kb <= -0.91,0.958183,Fe kb,-0.91,<=
10,Ti ka <= -0.70,0.943714,Ti ka,-0.70,<=
11,Ti kb <= -0.14,0.786772,Ti kb,-0.14,<=
12,P > 0.08,0.750388,P,0.08,>
13,background2 > 0.35,0.739173,background2,0.35,>
14,sum Fe <= -0.28,0.674562,sum Fe,-0.28,<=
15,Cu <= -0.12,0.627001,Cu,-0.12,<=
16,Al > 0.19,0.578907,Al,0.19,>
17,Compton scattering > 0.05,0.546140,Compton scattering,0.05,>
18,Ni > 0.13,0.536082,Ni,0.13,>
19,background1 <= -0.08,0.473766,background1,-0.08,<=
20,Rayleight scattering <= -0.24,0.428634,Rayleight scattering,-0.24,<=
21,Zn <= -0.37,0.391027,Zn,-0.37,<=
22,Class_A,0.000000,None,None,None

In [14]:
# Aplicar o mapeamento
lrc_summed_df_pert_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_pert,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_pert_natural

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,K > 2.15,6.785412,K,2.15,>,20.676485,90.0,0.022977,K > 20.676485
1,Ca ka <= -1.50,6.421293,Ca ka,-1.50,<=,-9.476439,94.0,0.083086,Ca ka <= -9.476439
2,K > -1.46,5.136089,K,-1.46,>,-12.506148,111.0,0.014010,K > -12.506148
3,Ca ka <= 1.77,4.949388,Ca ka,1.77,<=,11.953266,82.0,0.013408,Ca ka <= 11.953266
4,K <= -1.46,4.860323,K,-1.46,<=,-12.506148,111.0,0.014010,K <= -12.506148
...,...,...,...,...,...,...,...,...,...
132,Zn > -0.37,0.004708,Zn,-0.37,>,-0.825949,38.0,0.000121,Zn > -0.825949
133,Zn > -0.11,0.002687,Zn,-0.11,>,-0.257461,132.0,0.004205,Zn > -0.257461
134,Zn > 0.10,0.001628,Zn,0.10,>,0.231960,7.0,0.000820,Zn > 0.231960
135,Class_A,0.000000,None,None,None,NaN,NaN,NaN,None
136,Class_B,0.000000,None,None,None,NaN,NaN,NaN,None

In [15]:
import plotly.graph_objects as go

n = 0
zone_name = lrc_summed_df_pert_natural.iloc[n]['Zone'] # o n indica a linha do dataframe lrc_summed_df_pert_natural que queremos acessar para pegar o nome da zona espectral (coluna 'Zone')
threshold_score = float(lrc_summed_df_pert_natural.iloc[n]['Threshold_Natural']) # o iloc acessa a linha n e a coluna 'Threshold_Natural' para pegar o valor do threshold já mapeado para o espaço natural (não pré-processado)

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
#print(f"  - Range de energias: {threshold_spectrum.index[n]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_pert_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona 'K':
  - Dimensão: 19 variáveis espectrais
  - Variância explicada pela PC1: 99.17%

In [16]:
# Permutation importance baseado em mudança nas probabilidades previstas (predict_proba)
# Medimos a média da diferença absoluta entre as probabilidades originais e as probabilidades
# obtidas após permutar cada variável. Isso fornece uma métrica contínua de importância.
n_repeats = 10
rng = np.random.RandomState(42)
# Probabilidades base (classe 'B' mapeada para 1)
baseline_proba = mlp_model[3].predict_proba(Xcalclass_prep)[:, 1]
importance_list = []
X_arr = Xcalclass_prep.copy()
for col in Xcalclass_prep.columns:
    diffs = []
    for _ in range(n_repeats):
        X_perm = X_arr.copy()
        X_perm[col] = rng.permutation(X_perm[col].values)
        perm_proba = mlp_model[3].predict_proba(X_perm)[:, 1]
        diffs.append(np.mean(np.abs(baseline_proba - perm_proba)))
    importance_list.append(np.mean(diffs))

permutation_df = pd.DataFrame({
    'energy': Xcalclass_prep.columns,
    'Permutation_importance_proba': importance_list
})
permutation_df.sort_values(by='Permutation_importance_proba', ascending=False, inplace=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in permutation_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
permutation_df['Zone'] = permutation_df['energy'].map(energy_to_zone_vip)
permutation_unique_df = permutation_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
permutation_unique_df = permutation_unique_df.sort_values(by='Permutation_importance_proba', ascending=False)
permutation_unique_df

   energy  Permutation_importance_proba                  Zone
0    3.36                      0.011790                     K
1     6.4                      0.010076                 Fe ka
2    3.66                      0.009841                 Ca ka
3    1.74                      0.004149                    Si
4       4                      0.004139                 Ca kb
5     4.5                      0.004036                 Ti ka
6       2                      0.003172                     P
7    5.86                      0.003121                    Mn
8    2.62                      0.003010             Rh L + Ar
9    7.08                      0.001923                 Fe kb
10   2.34                      0.001810                     S
11   7.24                      0.001607                    Ni
12   1.58                      0.001161                    Al
13  13.39                      0.001096                sum Fe
14  17.23                      0.001008           background3
15  11.99                      0.000999           background2
16   4.94                      0.000955                 Ti kb
17   7.85                      0.000923                    Cu
18  19.59                      0.000897    Compton scattering
19   8.65                      0.000704                    Zn
20  19.85                      0.000633  Rayleight scattering
21   5.42                      0.000513           background1
22  20.81                      0.000066                   NaN

In [17]:
import numpy as np

max_len = max(
    len(shap_unique_df['Zone']),
    len(permutation_unique_df['Zone']),
    len(lrc_summed_unique_df_pert['Zone']),
    len(lrc_summed_unique_df_cov['Zone'])
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'Shap': pad_list(shap_unique_df['Zone'], max_len),
    'Permutation' : pad_list(permutation_unique_df['Zone'], max_len),
    'LRC_perturbation' : pad_list(lrc_summed_unique_df_pert['Zone'], max_len),
    'LRC_covariance' : pad_list(lrc_summed_unique_df_cov['Zone'], max_len),
})

features_importance.to_csv('feature_importance.csv', index=False, sep=';')
features_importance

,Shap,Permutation,LRC_perturbation,LRC_covariance
0,Ca ka,K,K,Fe ka
1,Fe ka,Fe ka,Ca ka,K
2,K,Ca ka,Fe ka,Ca ka
3,Si,Si,Si,Si
4,Ca kb,Ca kb,Mn,Ti ka
5,Ti ka,Ti ka,Ca kb,Fe kb
6,Rh L + Ar,P,S,Ca kb
7,background3,Mn,background3,Rh L + Ar
8,Mn,Rh L + Ar,Rh L + Ar,background3
9,background2,Fe kb,Fe kb,Compton scattering
10,P,S,Ti ka,Al
11,Compton scattering,Ni,Ti kb,Rayleight scattering
12,sum Fe,Al,P,sum Fe
13,Fe kb,sum Fe,background2,P
14,S,background3,sum Fe,Ti kb
15,Ni,background2,Cu,background2
16,Ti kb,Ti kb,Al,Mn
17,Al,Cu,Compton scattering,Cu
18,Rayleight scattering,Compton scattering,Ni,S
19,background1,Zn,background1,Ni
20,Cu,Rayleight scattering,Rayleight scattering,Zn
21,Zn,background1,Zn,background1
22,NaN,NaN,None,None

In [18]:
import rbo
rbo_comparison = pd.DataFrame(columns=['Method_1', 'Method_2', 'RBO_Score'])
methods = features_importance.columns.tolist()
for i in range(len(methods)):
    for j in range(i + 1, len(methods)):
        method_1 = methods[i]
        method_2 = methods[j]
        # Remove None values from the lists
        list_1 = [x for x in features_importance[method_1].tolist() if x is not None]
        list_2 = [x for x in features_importance[method_2].tolist() if x is not None]
        # Truncate both lists to the same length (minimum of both)
        min_len = min(len(list_1), len(list_2))
        list_1_trunc = list_1[:min_len]
        list_2_trunc = list_2[:min_len]
        rbo_score = rbo.RankingSimilarity(list_1_trunc, list_2_trunc).rbo(p=0.7, k=10)
        rbo_comparison = pd.concat([rbo_comparison, pd.DataFrame({
            'Method_1': [method_1],
            'Method_2': [method_2],
            'RBO_Score': [rbo_score]
        })], ignore_index=True)
rbo_comparison.sort_values(by='RBO_Score', ascending=False, inplace=True)
rbo_comparison.to_csv('rbo_rank.csv', index=False, sep=';')
rbo_comparison

C:\Users\Usuario\AppData\Local\Temp\ipykernel_13228\3097109587.py:16: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

           Method_1          Method_2  RBO_Score
3       Permutation  LRC_perturbation   0.821418
4       Permutation    LRC_covariance   0.631460
0              Shap       Permutation   0.551191
2              Shap    LRC_covariance   0.531470
1              Shap  LRC_perturbation   0.523339
5  LRC_perturbation    LRC_covariance   0.509926

In [19]:
lrc_summed_df_cov_natural.to_csv('lrc_cov_natural.csv', index=False, sep=';')
lrc_summed_df_pert_natural.to_csv('lrc_pert_natural.csv', index=False, sep=';')