In [1]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import kennard_stone as ks
pd.options.plotting.backend = 'plotly'  # setting plotly as the backend for pandas plotting

# Add parent directory to sys.path so local module 'synthetic' can be imported
import sys
from pathlib import Path # for path manipulations
# Move three levels up from current working directory to reach workspace root
workspace_root = Path.cwd().parent.parent.parent.resolve() 
smx_dir = workspace_root / 'smx'  # Path to smx folder
if str(smx_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(smx_dir)) # insert at the start of sys.path to prioritize local modules

# Loading a soil spectral dataset based on X-ray fluorescence (XRF)
data_complete = pd.read_csv(f'{workspace_root}/real_datasets/xrf/forage.csv', sep=';') # local copy of Toledo 2022 dataset (os ... indica para omitir o caminho longo)
data = data_complete.loc[:, '1.4':'20.81']

# Split dataset by class and create calibration/prediction sets using Kennard-Stone (as in original pipeline)
data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.loc[:, '1.4':'20.81'], test_size=0.30)  # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.loc[:, '1.4':'20.81'], test_size=0.30)  # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)

Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True)  # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0])  # target for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0])  # target for prediction set

# preprocessings
import preprocessings as prepr  # preprocessing methods for XRF data

Xcalclass_prep, mean_calclass, mean_calclass_poisson  = prepr.poisson(Xcalclass, mc=True)
Xpredclass_prep = ((Xpredclass/np.sqrt(mean_calclass)) - mean_calclass_poisson)

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-26 14:02:40,084 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-26 14:02:40,090 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-26 14:02:40,104 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-26 14:02:40,130 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [2]:
from modeling import pls_optimized

plsda_results = pls_optimized(
    Xcalclass_prep, 
    ycalclass,
    LVmax=3,
    Xpred=Xpredclass_prep,
    ypred=ypredclass,
    aim='classification',
    cv=10
)

# Convenience references used later
pls_model = plsda_results[3]               # fitted PLS model
vip_scores_mat = plsda_results[4]          # VIP scores matrix (features × LV)
y_pred_cont = plsda_results[5].iloc[:, -1] # continuous predictions for Xcalclass (used for MI/Cov)

# plotando o vip scores rapidamente
vip_scores_mat.T.plot()

## Definição das Zonas Espectrais

In [3]:
spectral_cuts = [
('Al', 1.40, 1.63),
('Si', 1.63, 1.86),
('P', 1.86, 2.16),
('S', 2.16, 2.44),
('Rh L + Ar', 2.44, 3.10),
('K', 3.10, 3.46),
('Ca ka', 3.46, 3.86),
('Ca kb', 3.86, 4.37),
('Ti ka', 4.37, 4.66),
('Ti kb', 4.66, 5.08),
('background1', 5.08, 5.72),
('Mn', 5.72, 6.10),
('Fe ka', 6.10, 6.76),
('Fe kb', 6.76, 7.20),
('Ni', 7.20, 7.69),
('Cu', 7.69, 8.45),
('Zn', 8.45, 8.81),
('background2', 8.81, 13.10),
('sum Fe' , 13.10, 13.63),
('background3', 13.63, 18.0),
('Compton scattering', 18.0, 19.70),
('Rayleight scattering', 19.70, 20.81)
]

## VIP, Regression Coefficients e SHAP (como no original)

In [4]:
# VIP scores por energia
vip_scores_df = pd.DataFrame({
    'energy': vip_scores_mat.T.index,
    'VIP_Score': vip_scores_mat.T.iloc[:,0].values
})
vip_scores_df = vip_scores_df.sort_values(by='VIP_Score', ascending=False).reset_index(drop=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in vip_scores_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
vip_scores_df['Zone'] = vip_scores_df['energy'].map(energy_to_zone_vip)
vip_scores_unique_df = vip_scores_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
vip_scores_unique_df = vip_scores_unique_df.sort_values(by='VIP_Score', ascending=False).reset_index(drop=True)

# Coeficientes de regressão do PLS
reg_vet = pd.DataFrame(pls_model.coef_, columns=pls_model.feature_names_in_).T
reg_vet.insert(0, 'energy', reg_vet.index)
reg_vet = reg_vet.reset_index(drop=True)
reg_vet.columns = ['energy','Reg_coef']
reg_vet['Abs_Reg_coef'] = reg_vet['Reg_coef'].abs()
reg_vet = reg_vet.sort_values(by='Abs_Reg_coef', ascending=False).reset_index(drop=True)
energy_to_zone_reg = {}
for zone_name, start, end in spectral_cuts:
    for e in reg_vet['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_reg[e] = zone_name
reg_vet['Zone'] = reg_vet['energy'].map(energy_to_zone_reg)
reg_vet_unique_df = reg_vet.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
reg_vet_unique_df = reg_vet_unique_df.sort_values(by='Abs_Reg_coef', ascending=False).reset_index(drop=True)

In [5]:
shap_global_importance = pd.read_csv('shap_forage.csv', sep=';') # loading previously saved shap_unique_df

# vamos gerar uma nova coluna em shap_global_importance com o nome da zona espectral correspondente de acordo com a lista spectral_cuts
energy_to_zone_shap = {}
for zone_name, start, end in spectral_cuts:
    for i in shap_global_importance['energy']:
        i_float = float(i)
        if start <= i_float <= end:
            energy_to_zone_shap[i] = zone_name
shap_global_importance['Zone'] = shap_global_importance['energy'].map(energy_to_zone_shap)

# agora vamos filtrar shap_global_importance para manter apenas as zonas espectrais únicas com maior SHAP score
shap_unique_df = shap_global_importance.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
shap_unique_df = shap_unique_df.sort_values(by='Mean_Abs_SHAP', ascending=False).reset_index(drop=True)
shap_unique_df

    energy  Mean_Abs_SHAP                  Zone
0     1.74       0.047022                    Si
1     3.70       0.041039                 Ca ka
2     2.62       0.001321             Rh L + Ar
3     3.28       0.001253                     K
4     4.04       0.000292                 Ca kb
5     6.44       0.000022                 Fe ka
6     5.08       0.000000           background1
7     7.69       0.000000                    Cu
8     7.36       0.000000                    Ni
9     6.76       0.000000                 Fe kb
10    2.14       0.000000                     P
11    5.72       0.000000                    Mn
12    4.42       0.000000                 Ti ka
13    2.24       0.000000                     S
14    5.00       0.000000                 Ti kb
15    1.60       0.000000                    Al
16   20.25       0.000000  Rayleight scattering
17   19.07       0.000000    Compton scattering
18   13.47       0.000000                sum Fe
19   12.09       0.000000           background2
20   14.49       0.000000           background3
21    8.55       0.000000                    Zn

## Funções de Agregação por PCA

Aqui implementamos as funções para agregar zonas espectrais usando PCA com 1 componente principal.

In [6]:
import explaining as exp

# Extração das zonas espectrais
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_scores_df, pca_info_dict = exp.aggregate_spectral_zones_pca(spectral_zones_class) # apca aggregation
print(f"\nScores DataFrame shape: {zone_scores_df.shape}")

Zone 'Al': VE = 92.81%, dim = 12 variables
Zone 'Si': VE = 99.42%, dim = 12 variables
Zone 'P': VE = 94.16%, dim = 16 variables
Zone 'S': VE = 89.31%, dim = 15 variables
Zone 'Rh L + Ar': VE = 95.85%, dim = 34 variables
Zone 'K': VE = 98.44%, dim = 19 variables
Zone 'Ca ka': VE = 89.46%, dim = 21 variables
Zone 'Ca kb': VE = 96.25%, dim = 26 variables
Zone 'Ti ka': VE = 98.15%, dim = 15 variables
Zone 'Ti kb': VE = 76.25%, dim = 22 variables
Zone 'background1': VE = 66.63%, dim = 33 variables
Zone 'Mn': VE = 94.16%, dim = 20 variables
Zone 'Fe ka': VE = 99.38%, dim = 34 variables
Zone 'Fe kb': VE = 94.04%, dim = 23 variables
Zone 'Ni': VE = 77.76%, dim = 25 variables
Zone 'Cu': VE = 84.25%, dim = 39 variables
Zone 'Zn': VE = 82.20%, dim = 19 variables
Zone 'background2': VE = 86.56%, dim = 215 variables
Zone 'sum Fe': VE = 88.47%, dim = 27 variables
Zone 'background3': VE = 87.92%, dim = 219 variables
Zone 'Compton scattering': VE = 88.73%, dim = 85 variables
Zone 'Rayleight scattering': VE = 84.40%, dim = 56 variables

Scores DataFrame shape: (135, 22)

In [7]:
predicates_quantiles = exp.predicates_by_quantiles(zone_scores_df, [0.2, 0.4, 0.6, 0.8])
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_scores_df,
    y_predicted_numeric=y_pred_cont
)

In [9]:
# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_cov = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_pred_conticted_numeric = pd.Series(y_pred_cont) # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred_conticted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist
    
    # Calcular MI
    cov_results_dict_seed = exp.calculate_predicate_metrics(
        bags_result=bags_result_seed,
        metric='covariance', # covariance ou mutual_information
        threshold=0.01, # threshold para cortar predicados irrelevantes
        n_neighbors=5
    )
    
    # Salvar no dicionário principal
    all_results_cov[seed] = {
        'bags_result': bags_result_seed,
        'cov_results_dict': cov_results_dict_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graph(
        bags_result=all_results_cov[seed]['bags_result'],
        predicate_ranking_dict=all_results_cov[seed]['cov_results_dict'],
        metric_column='Covariance',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )
    # Armazenar grafo
    graphs_by_seed[seed] = DG

# Calcular LRC usando a função pronta do explaining.py
lrc_cov_by_seed = {}
for seed in random_seeds:
    DG = graphs_by_seed[seed]
    lrc_cov_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_cov_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_cov_by_seed[seed] = lrc_cov_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_cov_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_cov_df_seed = lrc_cov_by_seed[seed].rename(columns={'Node': f'Predicate_Cov_Seed_{seed}'})
    lrc_cov_all_seeds_df = pd.concat([lrc_cov_all_seeds_df, lrc_cov_df_seed[[f'Predicate_Cov_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_cov_unique_by_seed = {}
for seed, lrc_df in lrc_cov_by_seed.items():
    lrc_cov_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_cov_unique_df = lrc_cov_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_cov_unique_by_seed[seed] = lrc_cov_unique_df

lrc_cov_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_2 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_3 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_4 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_5 | Samples: Yes | Predicates: No (All) | Valid: 133 | Discarded: 43
Bag_6 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_7 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_8 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_9 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_10 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Computing Covariance for Predicates
Metric: covariance
Threshold: 0.01

======================================================================
Processando semente: 1
======================================================================

Bag_1 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_2 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_3 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_4 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_5 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_6 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_7 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_8 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_9 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_10 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Computing Covariance for Predicates
Metric: covariance
Threshold: 0.01

======================================================================
Processando semente: 2
======================================================================

Bag_1 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_2 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_3 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_4 | Samples: Yes | Predicates: No (All) | Valid: 133 | Discarded: 43
Bag_5 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_6 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_7 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_8 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_9 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_10 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Computing Covariance for Predicates
Metric: covariance
Threshold: 0.01

======================================================================
Processando semente: 3
======================================================================

Bag_1 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_2 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_3 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_4 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_5 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_6 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_7 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_8 | Samples: Yes | Predicates: No (All) | Valid: 134 | Discarded: 42
Bag_9 | Samples: Yes | Predicates: No (All) | Valid: 133 | Discarded: 43
Bag_10 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Computing Covariance for Predicates
Metric: covariance
Threshold: 0.01

======================================================================
Processando Grafo - Semente: 0
======================================================================


Total bidirectional pairs found: 109
Removed: Fe ka > -2.26 -> Fe ka > -3.74 (7.6013) | Kept: Fe ka > -3.74 -> Fe ka > -2.26 (17.2010)
Removed: Si > -2.51 -> Ca ka <= 3.95 (3.6906) | Kept: Ca ka <= 3.95 -> Si > -2.51 (4.6227)
Removed: Si > -2.51 -> K <= 6.26 (1.1843) | Kept: K <= 6.26 -> Si > -2.51 (1.2409)
Removed: Si > -1.67 -> Si > -2.51 (3.6752) | Kept: Si > -2.51 -> Si > -1.67 (6.2927)
Removed: Ca ka <= 3.95 -> Si > -1.67 (1.1032) | Kept: Si > -1.67 -> Ca ka <= 3.95 (2.4698)
Removed: Ca ka <= 3.95 -> K > -6.69 (1.1466) | Kept: K > -6.69 -> Ca ka <= 3.95 (4.0051)
Removed: K > -6.69 -> Si > -1.67 (2.4717) | Kept: Si > -1.67 -> K > -6.69 (2.4912)
Removed: K <= 6.26 -> K > -6.69 (1.1310) | Kept: K > -6.69 -> K <= 6.26 (2.4148)
Removed: K <= 6.26 -> K > -1.46 (1.9964) | Kept: K > -1.46 -> K <= 6.26 (2.0269)
Removed: Ca ka <= 1.77 -> K <= 6.26 (0.8970) | Kept: K <= 6.26 -> Ca ka <= 1.77 (4.1190)
Removed: Ca ka <= 1.77 -> K > -1.46 (0.9096) | Kept: K > -1.46 -> Ca ka <= 1.77 (0.9566)
Removed: K > -1.46 -> Si > -0.72 (1.7799) | Kept: Si > -0.72 -> K > -1.46 (2.5521)
Removed: K > -1.46 -> Ca ka > -4.65 (0.9097) | Kept: Ca ka > -4.65 -> K > -1.46 (1.6513)
Removed: Ca ka > -4.65 -> Ca ka <= 1.77 (0.8220) | Kept: Ca ka <= 1.77 -> Ca ka > -4.65 (5.2115)
Removed: Si > -0.72 -> Ca ka > -4.65 (0.8655) | Kept: Ca ka > -4.65 -> Si > -0.72 (4.0692)
Removed: Ti ka > -0.70 -> Si > -0.72 (0.6908) | Kept: Si > -0.72 -> Ti ka > -0.70 (3.8783)
Removed: Ca ka <= -1.50 -> Ca kb <= 1.57 (0.4529) | Kept: Ca kb <= 1.57 -> Ca ka <= -1.50 (1.4452)
Removed: Ca kb <= 1.57 -> Si <= 3.71 (0.9964) | Kept: Si <= 3.71 -> Ca kb <= 1.57 (1.0203)
Removed: Fe kb > -0.63 -> Ti ka > -0.86 (1.1562) | Kept: Ti ka > -0.86 -> Fe kb > -0.63 (1.6052)
Removed: Fe kb > -0.63 -> Rh L + Ar > -0.16 (0.4701) | Kept: Rh L + Ar > -0.16 -> Fe kb > -0.63 (0.6454)
Removed: Fe kb > -0.44 -> Fe kb > -0.63 (0.4514) | Kept: Fe kb > -0.63 -> Fe kb > -0.44 (1.6950)
Removed: K <= 2.15 -> Rh L + Ar > -0.16 (0.4273) | Kept: Rh L + Ar > -0.16 -> K <= 2.15 (1.0133)
Removed: Rh L + Ar > -0.77 -> Rh L + Ar > -0.16 (0.4159) | Kept: Rh L + Ar > -0.16 -> Rh L + Ar > -0.77 (0.8891)
Removed: Si <= 3.71 -> Rh L + Ar > -0.16 (0.3388) | Kept: Rh L + Ar > -0.16 -> Si <= 3.71 (0.5113)
Removed: K <= 2.15 -> Rh L + Ar > -0.77 (0.9868) | Kept: Rh L + Ar > -0.77 -> K <= 2.15 (1.0074)
Removed: background3 > 0.14 -> K <= 2.15 (0.3145) | Kept: K <= 2.15 -> background3 > 0.14 (0.4235)
Removed: Ti ka > -0.52 -> Fe kb > -0.91 (0.4654) | Kept: Fe kb > -0.91 -> Ti ka > -0.52 (1.0866)
Removed: Ti ka > -0.52 -> Fe kb > -0.44 (1.0349) | Kept: Fe kb > -0.44 -> Ti ka > -0.52 (1.0983)
Removed: Ca ka <= -1.50 -> Rh L + Ar > -0.77 (0.4169) | Kept: Rh L + Ar > -0.77 -> Ca ka <= -1.50 (0.4606)
Removed: Rh L + Ar > -1.66 -> Ca ka <= -1.50 (0.4469) | Kept: Ca ka <= -1.50 -> Rh L + Ar > -1.66 (0.8358)
Removed: Ca ka <= -1.50 -> Si <= 3.71 (0.4379) | Kept: Si <= 3.71 -> Ca ka <= -1.50 (0.4773)
Removed: Si <= 3.71 -> Rh L + Ar > -0.77 (0.4450) | Kept: Rh L + Ar > -0.77 -> Si <= 3.71 (0.8765)
Removed: background3 > 0.14 -> Ca kb > -1.81 (0.3400) | Kept: Ca kb > -1.81 -> background3 > 0.14 (0.7282)
Removed: background3 > 0.14 -> Ca kb <= 0.62 (0.3575) | Kept: Ca kb <= 0.62 -> background3 > 0.14 (0.8020)
Removed: Ca ka > -1.50 -> background3 > 0.14 (0.3158) | Kept: background3 > 0.14 -> Ca ka > -1.50 (0.6457)
Removed: background3 > 0.14 -> Rh L + Ar > -1.66 (0.3364) | Kept: Rh L + Ar > -1.66 -> background3 > 0.14 (0.6766)
Removed: Ca ka > -1.50 -> Si <= 3.71 (0.3514) | Kept: Si <= 3.71 -> Ca ka > -1.50 (0.4122)
Removed: Ca ka > -1.50 -> background3 > -0.62 (0.3301) | Kept: background3 > -0.62 -> Ca ka > -1.50 (0.5905)
Removed: background3 > -0.62 -> K <= -1.46 (0.2131) | Kept: K <= -1.46 -> background3 > -0.62 (0.6300)
Removed: background3 > -1.28 -> K <= -1.46 (0.2622) | Kept: K <= -1.46 -> background3 > -1.28 (0.2725)
Removed: background3 > -0.62 -> Ca ka > 1.77 (0.2251) | Kept: Ca ka > 1.77 -> background3 > -0.62 (0.2331)
Removed: K > 2.15 -> Ca ka > 1.77 (0.2380) | Kept: Ca ka > 1.77 -> K > 2.15 (0.2407)
Removed: Compton scattering > 0.05 -> Compton scattering > -0.40 (0.1992) | Kept: Compton scattering > -0.40 -> Compton scattering > 0.05 (0.9278)
Removed: background3 > -1.28 -> Compton scattering > -0.40 (0.2503) | Kept: Compton scattering > -0.40 -> background3 > -1.28 (0.5180)
Removed: Ca ka > 1.77 -> Compton scattering > -0.40 (0.2133) | Kept: Compton scattering > -0.40 -> Ca ka > 1.77 (0.2356)
Removed: Ca ka > 1.77 -> Compton scattering > 0.05 (0.2151) | Kept: Compton scattering > 0.05 -> Ca ka > 1.77 (0.6859)
Removed: sum Fe > -0.28 -> Ca ka > 1.77 (0.1512) | Kept: Ca ka > 1.77 -> sum Fe > -0.28 (0.1604)
Removed: Fe ka <= 1.10 -> background3 > -1.28 (0.2144) | Kept: background3 > -1.28 -> Fe ka <= 1.10 (0.2171)
Removed: background3 > -1.28 -> Ca kb <= -0.59 (0.2107) | Kept: Ca kb <= -0.59 -> background3 > -1.28 (0.3685)
Removed: Ca kb <= -0.59 -> Fe ka <= 1.10 (0.2042) | Kept: Fe ka <= 1.10 -> Ca kb <= -0.59 (0.2300)
Removed: Compton scattering > -0.88 -> Fe ka <= 1.10 (0.1987) | Kept: Fe ka <= 1.10 -> Compton scattering > -0.88 (0.3953)
Removed: Ca kb <= -0.59 -> Compton scattering > -0.88 (0.2068) | Kept: Compton scattering > -0.88 -> Ca kb <= -0.59 (0.3877)
Removed: sum Fe > -0.28 -> Compton scattering > -0.88 (0.1008) | Kept: Compton scattering > -0.88 -> sum Fe > -0.28 (0.1529)
Removed: Rayleight scattering > -0.25 -> Al > -0.68 (0.1209) | Kept: Al > -0.68 -> Rayleight scattering > -0.25 (0.1365)
Removed: Rayleight scattering > -0.25 -> sum Fe > -0.28 (0.1476) | Kept: sum Fe > -0.28 -> Rayleight scattering > -0.25 (0.1516)
Removed: sum Fe > -0.28 -> Rayleight scattering > 0.03 (0.1648) | Kept: Rayleight scattering > 0.03 -> sum Fe > -0.28 (0.4135)
Removed: Rayleight scattering > 0.03 -> Al > -0.68 (0.1413) | Kept: Al > -0.68 -> Rayleight scattering > 0.03 (0.4124)
Removed: sum Fe > -0.28 -> sum Fe > 0.07 (0.1567) | Kept: sum Fe > 0.07 -> sum Fe > -0.28 (0.3351)
Removed: sum Fe > -0.60 -> sum Fe > 0.07 (0.1263) | Kept: sum Fe > 0.07 -> sum Fe > -0.60 (0.2227)
Removed: sum Fe > 0.07 -> Rayleight scattering > -0.50 (0.1258) | Kept: Rayleight scattering > -0.50 -> sum Fe > 0.07 (0.1280)
Removed: Al > -0.19 -> Ca kb > -0.59 (0.1194) | Kept: Ca kb > -0.59 -> Al > -0.19 (0.2531)
Removed: Ca kb > -0.59 -> Ti kb > -0.32 (0.1272) | Kept: Ti kb > -0.32 -> Ca kb > -0.59 (0.1955)
Removed: Al > -0.68 -> P > -1.23 (0.1399) | Kept: P > -1.23 -> Al > -0.68 (0.2849)
Removed: Rayleight scattering > -0.50 -> P > 0.08 (0.1169) | Kept: P > 0.08 -> Rayleight scattering > -0.50 (0.1406)
Removed: Al > -0.19 -> background2 > 0.35 (0.0978) | Kept: background2 > 0.35 -> Al > -0.19 (0.1218)
Removed: Ti kb > -0.32 -> Al > -0.19 (0.0930) | Kept: Al > -0.19 -> Ti kb > -0.32 (0.1225)
Removed: Ti kb > -0.14 -> P > -0.59 (0.0763) | Kept: P > -0.59 -> Ti kb > -0.14 (0.1177)
Removed: background2 > -0.51 -> background2 > -1.35 (0.0360) | Kept: background2 > -1.35 -> background2 > -0.51 (0.1051)
Removed: background2 > 0.35 -> Al <= 0.62 (0.1019) | Kept: Al <= 0.62 -> background2 > 0.35 (0.1108)
Removed: Ti kb > -0.14 -> Al <= 0.62 (0.0880) | Kept: Al <= 0.62 -> Ti kb > -0.14 (0.2940)
Removed: background2 <= -0.51 -> Ti kb > 0.03 (0.1031) | Kept: Ti kb > 0.03 -> background2 <= -0.51 (0.1633)
Removed: Ti kb > -0.14 -> Mn > 0.23 (0.0658) | Kept: Mn > 0.23 -> Ti kb > -0.14 (0.1018)
Removed: Ti kb > 0.03 -> Ti kb > -0.14 (0.1549) | Kept: Ti kb > -0.14 -> Ti kb > 0.03 (0.2512)
Removed: Ti ka <= 0.53 -> Ni > -0.14 (0.0378) | Kept: Ni > -0.14 -> Ti ka <= 0.53 (0.0402)
Removed: S <= -0.27 -> Ti ka <= 0.53 (0.0355) | Kept: Ti ka <= 0.53 -> S <= -0.27 (0.1055)
Removed: Mn <= 1.01 -> S <= 0.55 (0.0549) | Kept: S <= 0.55 -> Mn <= 1.01 (0.0603)
Removed: S <= 0.55 -> P <= -0.59 (0.0700) | Kept: P <= -0.59 -> S <= 0.55 (0.0719)
Removed: Compton scattering <= -0.40 -> Ni <= 0.13 (0.0708) | Kept: Ni <= 0.13 -> Compton scattering <= -0.40 (0.1009)
Removed: background2 <= 0.35 -> P <= 0.08 (0.0292) | Kept: P <= 0.08 -> background2 <= 0.35 (0.0467)
Removed: P <= 0.08 -> background3 <= 0.14 (0.0494) | Kept: background3 <= 0.14 -> P <= 0.08 (0.0584)
Removed: Ni <= 0.13 -> S <= 0.55 (0.0565) | Kept: S <= 0.55 -> Ni <= 0.13 (0.1017)
Removed: S <= 0.55 -> Mn > -1.22 (0.0407) | Kept: Mn > -1.22 -> S <= 0.55 (0.0457)
Removed: Cu <= -0.12 -> Ni <= 0.13 (0.0304) | Kept: Ni <= 0.13 -> Cu <= -0.12 (0.0533)
Removed: sum Fe <= -0.28 -> Fe kb <= 0.33 (0.0372) | Kept: Fe kb <= 0.33 -> sum Fe <= -0.28 (0.0469)
Removed: Ni <= 0.59 -> Fe kb <= 0.33 (0.0732) | Kept: Fe kb <= 0.33 -> Ni <= 0.59 (0.0814)
Removed: Cu <= -0.12 -> Fe kb <= 0.33 (0.0195) | Kept: Fe kb <= 0.33 -> Cu <= -0.12 (0.0341)
Removed: sum Fe <= -0.28 -> background3 <= 0.14 (0.0261) | Kept: background3 <= 0.14 -> sum Fe <= -0.28 (0.0484)
Removed: S <= 0.09 -> S <= -0.27 (0.0477) | Kept: S <= -0.27 -> S <= 0.09 (0.0707)
Removed: S <= 0.09 -> Cu <= 0.09 (0.0464) | Kept: Cu <= 0.09 -> S <= 0.09 (0.0722)
Removed: Al <= 0.19 -> Al <= -0.19 (0.0193) | Kept: Al <= -0.19 -> Al <= 0.19 (0.0626)
Removed: background1 <= -0.08 -> P <= 1.06 (0.0167) | Kept: P <= 1.06 -> background1 <= -0.08 (0.0480)
Removed: Ti kb <= 0.20 -> Al <= 0.19 (0.0187) | Kept: Al <= 0.19 -> Ti kb <= 0.20 (0.0869)
Removed: background2 <= 0.35 -> Mn > -0.41 (0.0274) | Kept: Mn > -0.41 -> background2 <= 0.35 (0.0656)
Removed: background1 <= 0.30 -> background1 <= -0.08 (0.0189) | Kept: background1 <= -0.08 -> background1 <= 0.30 (0.0404)
Removed: background1 <= 0.30 -> Rh L + Ar <= -0.77 (0.0238) | Kept: Rh L + Ar <= -0.77 -> background1 <= 0.30 (0.0299)
Removed: background3 <= 1.47 -> Cu > -0.12 (0.0133) | Kept: Cu > -0.12 -> background3 <= 1.47 (0.0172)
Removed: Ni > 0.13 -> background3 <= 1.47 (0.0122) | Kept: background3 <= 1.47 -> Ni > 0.13 (0.0179)
Removed: Ni <= -0.14 -> Ni <= 0.59 (0.0121) | Kept: Ni <= 0.59 -> Ni <= -0.14 (0.0210)
Removed: Zn <= 0.10 -> Ni <= -0.14 (0.0129) | Kept: Ni <= -0.14 -> Zn <= 0.10 (0.0455)
Removed: Zn <= 0.34 -> Ni <= -0.14 (0.0275) | Kept: Ni <= -0.14 -> Zn <= 0.34 (0.0288)
Removed: background1 <= 0.11 -> Mn <= -0.41 (0.0129) | Kept: Mn <= -0.41 -> background1 <= 0.11 (0.0224)
Removed: background1 <= 0.11 -> Zn <= -0.11 (0.0153) | Kept: Zn <= -0.11 -> background1 <= 0.11 (0.0230)
Removed: Fe ka <= -2.26 -> background1 <= 0.11 (0.0196) | Kept: background1 <= 0.11 -> Fe ka <= -2.26 (0.0341)
Removed: Cu > -0.12 -> Fe ka <= -3.05 (0.0095) | Kept: Fe ka <= -3.05 -> Cu > -0.12 (0.0109)
Removed: Cu > -0.12 -> sum Fe <= 0.07 (0.0115) | Kept: sum Fe <= 0.07 -> Cu > -0.12 (0.0126)
Removed: Compton scattering <= 0.87 -> background3 <= 0.14 (0.0136) | Kept: background3 <= 0.14 -> Compton scattering <= 0.87 (0.0157)
Removed: Cu <= 0.56 -> Mn <= 0.23 (0.0131) | Kept: Mn <= 0.23 -> Cu <= 0.56 (0.0553)
Removed: Cu <= 0.56 -> Zn > 0.10 (0.0141) | Kept: Zn > 0.10 -> Cu <= 0.56 (0.0155)
Removed: Zn > -0.11 -> sum Fe <= 0.07 (0.0144) | Kept: sum Fe <= 0.07 -> Zn > -0.11 (0.0299)

======================================================================
CONSTRUCTED GRAPH SUMMARY
======================================================================
Initial edges: 862 | Removed: 109
Predicate nodes: 128
Metric: Covariance
Weighting by explained variance: ENABLED

======================================================================
Processando Grafo - Semente: 1
======================================================================


Total bidirectional pairs found: 135
Removed: Fe ka > -2.26 -> Fe ka > -3.74 (5.2898) | Kept: Fe ka > -3.74 -> Fe ka > -2.26 (19.6002)
Removed: Ca ka <= 3.95 -> Si > -1.67 (1.0933) | Kept: Si > -1.67 -> Ca ka <= 3.95 (2.4012)
Removed: Ca ka <= 3.95 -> K > -6.69 (1.1506) | Kept: K > -6.69 -> Ca ka <= 3.95 (3.9490)
Removed: Si > -1.67 -> Si > -2.51 (1.1761) | Kept: Si > -2.51 -> Si > -1.67 (8.6342)
Removed: Si > -1.67 -> K <= 6.26 (1.1549) | Kept: K <= 6.26 -> Si > -1.67 (1.1580)
Removed: Si > -2.51 -> K > -6.69 (2.3176) | Kept: K > -6.69 -> Si > -2.51 (2.4964)
Removed: Ca ka <= 1.77 -> K <= 6.26 (0.9012) | Kept: K <= 6.26 -> Ca ka <= 1.77 (4.0078)
Removed: K <= 6.26 -> K > -1.46 (1.8674) | Kept: K > -1.46 -> K <= 6.26 (1.9024)
Removed: Ca ka > -4.65 -> K <= 6.26 (0.7390) | Kept: K <= 6.26 -> Ca ka > -4.65 (0.9225)
Removed: K > -1.46 -> Ca ka <= 1.77 (0.9452) | Kept: Ca ka <= 1.77 -> K > -1.46 (4.2662)
Removed: Ca ka > -4.65 -> Ca ka <= 1.77 (0.8242) | Kept: Ca ka <= 1.77 -> Ca ka > -4.65 (2.6084)
Removed: Ca ka > -4.65 -> K > -1.46 (0.8132) | Kept: K > -1.46 -> Ca ka > -4.65 (2.5640)
Removed: Si > -0.72 -> K > -1.46 (1.6527) | Kept: K > -1.46 -> Si > -0.72 (2.5169)
Removed: Si > -0.72 -> Ca ka > -4.65 (1.7136) | Kept: Ca ka > -4.65 -> Si > -0.72 (3.1293)
Removed: Rh L + Ar > -0.77 -> Rh L + Ar > -0.16 (0.7756) | Kept: Rh L + Ar > -0.16 -> Rh L + Ar > -0.77 (1.9427)
Removed: Ca kb <= 1.57 -> Rh L + Ar > -0.16 (0.5089) | Kept: Rh L + Ar > -0.16 -> Ca kb <= 1.57 (0.5147)
Removed: Rh L + Ar > -0.16 -> Ca kb > -1.81 (0.3196) | Kept: Ca kb > -1.81 -> Rh L + Ar > -0.16 (0.3469)
Removed: Fe kb > -0.44 -> Rh L + Ar > -0.16 (0.5084) | Kept: Rh L + Ar > -0.16 -> Fe kb > -0.44 (0.5780)
Removed: Ca ka <= -1.50 -> Rh L + Ar > -0.16 (0.4709) | Kept: Rh L + Ar > -0.16 -> Ca ka <= -1.50 (0.4824)
Removed: Ca kb <= 0.62 -> Rh L + Ar > -0.77 (0.3868) | Kept: Rh L + Ar > -0.77 -> Ca kb <= 0.62 (0.4393)
Removed: background3 > 0.14 -> Rh L + Ar > -0.77 (0.3325) | Kept: Rh L + Ar > -0.77 -> background3 > 0.14 (0.7076)
Removed: Si <= 3.71 -> Ca kb <= 1.57 (0.5235) | Kept: Ca kb <= 1.57 -> Si <= 3.71 (0.9919)
Removed: Ca kb <= 1.57 -> Ti ka > -0.52 (0.4835) | Kept: Ti ka > -0.52 -> Ca kb <= 1.57 (0.5380)
Removed: Rh L + Ar > -1.66 -> K <= 2.15 (0.7956) | Kept: K <= 2.15 -> Rh L + Ar > -1.66 (0.9164)
Removed: Ca ka <= -1.50 -> Rh L + Ar > -1.66 (0.4059) | Kept: Rh L + Ar > -1.66 -> Ca ka <= -1.50 (0.4588)
Removed: Ca kb <= 0.62 -> Rh L + Ar > -1.66 (0.3855) | Kept: Rh L + Ar > -1.66 -> Ca kb <= 0.62 (1.2529)
Removed: Rh L + Ar > -1.66 -> Si <= 3.71 (0.3595) | Kept: Si <= 3.71 -> Rh L + Ar > -1.66 (0.4481)
Removed: Ca ka > -1.50 -> K <= 2.15 (0.2828) | Kept: K <= 2.15 -> Ca ka > -1.50 (0.3189)
Removed: K <= 2.15 -> Si <= 3.71 (0.4778) | Kept: Si <= 3.71 -> K <= 2.15 (0.9265)
Removed: Ti ka > -0.86 -> Ti ka > -0.52 (0.5681) | Kept: Ti ka > -0.52 -> Ti ka > -0.86 (1.0789)
Removed: Ti ka > -0.52 -> Fe kb > -0.44 (0.4451) | Kept: Fe kb > -0.44 -> Ti ka > -0.52 (1.6743)
Removed: Ti ka > -0.86 -> Fe kb > -0.63 (0.4496) | Kept: Fe kb > -0.63 -> Ti ka > -0.86 (3.4160)
Removed: Ca kb <= 0.62 -> Ca ka <= -1.50 (0.3900) | Kept: Ca ka <= -1.50 -> Ca kb <= 0.62 (0.8021)
Removed: Fe kb > -0.44 -> Ca ka <= -1.50 (0.4220) | Kept: Ca ka <= -1.50 -> Fe kb > -0.44 (0.4288)
Removed: background3 > 0.14 -> Si <= 3.71 (0.2960) | Kept: Si <= 3.71 -> background3 > 0.14 (0.3674)
Removed: Ca kb <= 0.62 -> Si <= 3.71 (0.3848) | Kept: Si <= 3.71 -> Ca kb <= 0.62 (0.4116)
Removed: Fe kb > -0.44 -> Fe kb > -0.91 (0.9964) | Kept: Fe kb > -0.91 -> Fe kb > -0.44 (1.4801)
Removed: K > 2.15 -> Ca kb <= 0.62 (0.3967) | Kept: Ca kb <= 0.62 -> K > 2.15 (0.4022)
Removed: Ca kb > -1.81 -> background3 > 0.14 (0.6512) | Kept: background3 > 0.14 -> Ca kb > -1.81 (0.9580)
Removed: background3 > 0.14 -> Ca ka > -1.50 (0.5822) | Kept: Ca ka > -1.50 -> background3 > 0.14 (0.6101)
Removed: background3 > 0.14 -> K > 2.15 (0.3182) | Kept: K > 2.15 -> background3 > 0.14 (0.3596)
Removed: background3 > -0.62 -> Ca ka > -1.50 (0.5573) | Kept: Ca ka > -1.50 -> background3 > -0.62 (0.5745)
Removed: Compton scattering > -0.40 -> K <= -1.46 (0.2116) | Kept: K <= -1.46 -> Compton scattering > -0.40 (0.2602)
Removed: Compton scattering > 0.05 -> K <= -1.46 (0.1955) | Kept: K <= -1.46 -> Compton scattering > 0.05 (0.2285)
Removed: K <= -1.46 -> background3 > -1.28 (0.1625) | Kept: background3 > -1.28 -> K <= -1.46 (0.2350)
Removed: Ca kb <= -0.59 -> Fe ka <= 1.10 (0.1884) | Kept: Fe ka <= 1.10 -> Ca kb <= -0.59 (0.2071)

,Predicate_Cov_Seed_0,Predicate_Cov_Seed_1,Predicate_Cov_Seed_2,Predicate_Cov_Seed_3
0,Fe ka > -3.05,Fe ka > -3.05,Fe ka > -3.74,Fe ka > -3.05
1,Fe ka > -3.74,Fe ka > -3.74,Fe ka > -3.05,Fe ka > -2.26
2,Fe ka > -2.26,Ca ka <= 3.95,Fe ka > -2.26,Si > -2.51
3,Ca ka <= 3.95,Fe ka > -2.26,Ca ka <= 3.95,Fe ka > -3.74
4,K <= 6.26,Si > -2.51,K > -6.69,Ca ka <= 3.95
...,...,...,...,...
127,Si <= -1.67,Class_B,Fe kb <= -0.63,Si <= -1.67
128,Class_A,NaN,Rayleight scattering <= 0.53,sum Fe <= 0.07
129,Class_B,NaN,Fe kb <= -0.44,Compton scattering <= 0.87
130,NaN,NaN,Class_A,Class_A
131,NaN,NaN,Class_B,Class_B

In [11]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_cov_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_cov = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_cov = lrc_summed_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_cov = lrc_summed_df_cov.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
#lrc_summed_unique_df_cov = lrc_summed_unique_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_cov

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Fe ka > -3.05,13.808155,Fe ka,-3.05,>
1,Ca ka <= 3.95,7.345147,Ca ka,3.95,<=
2,Si > -2.51,6.678307,Si,-2.51,>
3,K > -6.69,5.803163,K,-6.69,>
4,Ti ka > -0.70,2.647399,Ti ka,-0.70,>
5,Fe kb > -0.63,1.884427,Fe kb,-0.63,>
6,Rh L + Ar > -1.66,1.514639,Rh L + Ar,-1.66,>
7,Ca kb <= 1.57,1.454267,Ca kb,1.57,<=
8,background3 > 0.14,1.048758,background3,0.14,>
9,Compton scattering > -0.40,1.019011,Compton scattering,-0.40,>
10,Rayleight scattering > -0.25,0.656406,Rayleight scattering,-0.25,>
11,Al > -0.68,0.633200,Al,-0.68,>
12,sum Fe > -0.28,0.608054,sum Fe,-0.28,>
13,P > -1.23,0.573764,P,-1.23,>
14,Ti kb > -0.14,0.504139,Ti kb,-0.14,>
15,background2 <= -0.51,0.499733,background2,-0.51,<=
16,Mn > 0.23,0.440488,Mn,0.23,>
17,S <= 0.55,0.377873,S,0.55,<=
18,Cu <= -0.12,0.349278,Cu,-0.12,<=
19,Ni > -0.14,0.339258,Ni,-0.14,>
20,background1 > -0.26,0.313916,background1,-0.26,>
21,Zn <= 0.34,0.298292,Zn,0.34,<=
22,Class_B,0.000000,None,None,None

In [12]:
# Criar zone_sums_df para dados NÃO pré-processados (Xcalclass)
spectral_zones_original = exp.extract_spectral_zones(Xcalclass, spectral_cuts)
zones_original = exp.aggregate_spectral_zones_pca(spectral_zones_original) # apca aggregation

# Aplicar o mapeamento
lrc_summed_df_cov_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_cov,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_cov_natural

Zone 'Al': VE = 95.14%, dim = 12 variables
Zone 'Si': VE = 99.71%, dim = 12 variables
Zone 'P': VE = 97.48%, dim = 16 variables
Zone 'S': VE = 93.90%, dim = 15 variables
Zone 'Rh L + Ar': VE = 96.86%, dim = 34 variables
Zone 'K': VE = 99.17%, dim = 19 variables
Zone 'Ca ka': VE = 93.72%, dim = 21 variables
Zone 'Ca kb': VE = 98.07%, dim = 26 variables
Zone 'Ti ka': VE = 98.49%, dim = 15 variables
Zone 'Ti kb': VE = 76.99%, dim = 22 variables
Zone 'background1': VE = 66.94%, dim = 33 variables
Zone 'Mn': VE = 95.57%, dim = 20 variables
Zone 'Fe ka': VE = 99.73%, dim = 34 variables
Zone 'Fe kb': VE = 94.82%, dim = 23 variables
Zone 'Ni': VE = 79.28%, dim = 25 variables
Zone 'Cu': VE = 84.38%, dim = 39 variables
Zone 'Zn': VE = 82.21%, dim = 19 variables
Zone 'background2': VE = 86.54%, dim = 215 variables
Zone 'sum Fe': VE = 88.64%, dim = 27 variables
Zone 'background3': VE = 87.63%, dim = 219 variables
Zone 'Compton scattering': VE = 89.25%, dim = 85 variables
Zone 'Rayleight scattering': VE = 84.72%, dim = 56 variables

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,Fe ka > -3.05,13.808155,Fe ka,-3.05,>,-11.993967,102.0,0.012499,Fe ka > -11.993967
1,Fe ka > -3.74,10.962825,Fe ka,-3.74,>,-14.394181,68.0,0.017162,Fe ka > -14.394181
2,Fe ka > -2.26,7.516280,Fe ka,-2.26,>,-8.585461,77.0,0.009247,Fe ka > -8.585461
3,Ca ka <= 3.95,7.345147,Ca ka,3.95,<=,24.763583,89.0,0.045885,Ca ka <= 24.763583
4,Si > -2.51,6.678307,Si,-2.51,>,-6.726367,45.0,0.014243,Si > -6.726367
...,...,...,...,...,...,...,...,...,...
129,Si <= -0.72,0.241893,Si,-0.72,<=,-2.087044,129.0,0.038926,Si <= -2.087044
130,Zn <= -0.37,0.227920,Zn,-0.37,<=,-0.825949,38.0,0.000121,Zn <= -0.825949
131,Fe kb <= -0.44,0.131883,Fe kb,-0.44,<=,-1.196874,106.0,0.000033,Fe kb <= -1.196874
132,Class_B,0.000000,None,None,None,NaN,NaN,NaN,None
133,Class_A,0.000000,None,None,None,NaN,NaN,NaN,None

## Reconstrução de Thresholds Multivariados

Agora vamos pegar os thresholds dos predicados mais importantes e reconstruí-los como espectros completos.

In [13]:
import plotly.graph_objects as go

n = 0
zone_name = lrc_summed_df_cov_natural.iloc[n]['Zone']
threshold_score = float(lrc_summed_df_cov_natural.iloc[n]['Threshold_Natural'])  # Corrigido: usa n em vez de 7

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
print(f"  - Range de energias: {threshold_spectrum.index[0]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_cov_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona 'Fe ka':
  - Dimensão: 34 variáveis espectrais
  - Range de energias: 6.1 - 6.76
  - Variância explicada pela PC1: 99.73%

In [14]:
# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_pred_conticted_numeric = pd.Series(y_pred_cont) # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred_conticted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = exp.calculate_predicate_perturbation(
        estimator=pls_model,
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        #perturbation_value=0,
        perturbation_mode='median', # valores entre 'mean' ou 'min'
        stats_source='full', # full indica usar todas as amostras para calcular estatísticas enquanto que 'fold' usa apenas as amostras do fold atual
        #metric='mean_abs_diff',   # Média com sinal (pode ser negativo)
        aim='regression',
        metric='mean_abs_diff', 
        verbose=True
    )

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graph(
        bags_result=all_results_pert[seed]['bags_result'],
        predicate_ranking_dict=all_results_pert[seed]['pert_results_dict'],
        metric_column='Perturbation',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )

    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_2 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_3 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_4 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_5 | Samples: Yes | Predicates: No (All) | Valid: 133 | Discarded: 43
Bag_6 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_7 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_8 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_9 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
Bag_10 | Samples: Yes | Predicates: No (All) | Valid: 132 | Discarded: 44
======================================================================
PERTURBATION IMPORTANCE FOR PREDICATES
======================================================================
Task type (aim): regression
Perturbation mode: median
Statistics source: full
Metric: mean_abs_diff
Total folds: 10


[Bag_1] Processing 132 predicates...
  Predicate: Al > -0.68 (n=87)
    Zone: 12 columns
    Importance: 0.000357
  Predicate: Al <= -0.19 (n=43)
    Zone: 12 columns
    Importance: 0.000355
  Predicate: Al > -0.19 (n=65)
    Zone: 12 columns
    Importance: 0.000403
  Predicate: Al <= 0.19 (n=67)
    Zone: 12 columns
    Importance: 0.000283
  Predicate: Al > 0.19 (n=41)
    Zone: 12 columns
    Importance: 0.000551
  Predicate: Al <= 0.62 (n=87)
    Zone: 12 columns
    Importance: 0.000312
  Predicate: Si > -2.51 (n=83)
    Zone: 12 columns
    Importance: 0.200761
  Predicate: Si <= -1.67 (n=45)
    Zone: 12 columns
    Importance: 0.100917
  Predicate: Si > -1.67 (n=63)
    Zone: 12 columns
    Importance: 0.245000
  Predicate: Si <= -0.72 (n=65)
    Zone: 12 columns
    Importance: 0.074636
  Predicate: Si > -0.72 (n=43)
    Zone: 12 columns
    Importance: 0.351742
  Predicate: Si <= 3.71 (n=85)
    Zone: 12 columns
    Importance: 0.106329
  Predicate: P > -1.23 (n=88)
    Zone: 16 columns
    Importance: 0.005181
  Predicate: P <= -0.59 (n=42)
    Zone: 16 columns
    Importance: 0.003974
  Predicate: P > -0.59 (n=66)
    Zone: 16 columns
    Importance: 0.006228
  Predicate: P <= 0.08 (n=63)
    Zone: 16 columns
    Importance: 0.003234
  Predicate: P > 0.08 (n=45)
    Zone: 16 columns
    Importance: 0.008316
  Predicate: P <= 1.06 (n=84)
    Zone: 16 columns
    Importance: 0.003484
  Predicate: S > -0.55 (n=86)
    Zone: 15 columns
    Importance: 0.003729
  Predicate: S <= -0.27 (n=43)
    Zone: 15 columns
    Importance: 0.003642
  Predicate: S > -0.27 (n=65)
    Zone: 15 columns
    Importance: 0.004274
  Predicate: S <= 0.09 (n=62)
    Zone: 15 columns
    Importance: 0.002738
  Predicate: S > 0.09 (n=46)
    Zone: 15 columns
    Importance: 0.005752
  Predicate: S <= 0.55 (n=84)
    Zone: 15 columns
    Importance: 0.002832
  Predicate: Rh L + Ar > -1.66 (n=90)
    Zone: 34 columns
    Importance: 0.022425
  Predicate: Rh L + Ar <= -0.77 (n=37)
    Zone: 34 columns
    Importance: 0.021767
  Predicate: Rh L + Ar > -0.77 (n=71)
    Zone: 34 columns
    Importance: 0.024973
  Predicate: Rh L + Ar <= -0.16 (n=63)
    Zone: 34 columns
    Importance: 0.014046
  Predicate: Rh L + Ar > -0.16 (n=45)
    Zone: 34 columns
    Importance: 0.037634
  Predicate: Rh L + Ar <= 1.37 (n=89)
    Zone: 34 columns
    Importance: 0.014850
  Predicate: K > -6.69 (n=87)
    Zone: 19 columns
    Importance: 0.011474
  Predicate: K <= -1.46 (n=42)
    Zone: 19 columns
    Importance: 0.015322
  Predicate: K > -1.46 (n=66)
    Zone: 19 columns
    Importance: 0.012206
  Predicate: K <= 2.15 (n=66)
    Zone: 19 columns
    Importance: 0.012772
  Predicate: K > 2.15 (n=42)
    Zone: 19 columns
    Importance: 0.014432
  Predicate: K <= 6.26 (n=86)
    Zone: 19 columns
    Importance: 0.011676
  Predicate: Ca ka > -4.65 (n=86)
    Zone: 21 columns
    Importance: 0.138840
  Predicate: Ca ka <= -1.50 (n=44)
    Zone: 21 columns
    Importance: 0.195041
  Predicate: Ca ka > -1.50 (n=64)
    Zone: 21 columns
    Importance: 0.139570
  Predicate: Ca ka <= 1.77 (n=67)
    Zone: 21 columns
    Importance: 0.143454
  Predicate: Ca ka > 1.77 (n=41)
    Zone: 21 columns
    Importance: 0.192754
  Predicate: Ca ka <= 3.95 (n=87)
    Zone: 21 columns
    Importance: 0.133382
  Predicate: Ca kb > -1.81 (n=86)
    Zone: 26 columns
    Importance: 0.021911
  Predicate: Ca kb <= -0.59 (n=45)
    Zone: 26 columns
    Importance: 0.032699
  Predicate: Ca kb > -0.59 (n=63)
    Zone: 26 columns
    Importance: 0.021776
  Predicate: Ca kb <= 0.62 (n=66)
    Zone: 26 columns
    Importance: 0.023873
  Predicate: Ca kb > 0.62 (n=42)
    Zone: 26 columns
    Importance: 0.030184
  Predicate: Ca kb <= 1.57 (n=87)
    Zone: 26 columns
    Importance: 0.021721
  Predicate: Ti ka > -0.86 (n=87)
    Zone: 15 columns
    Importance: 0.003964
  Predicate: Ti ka <= -0.70 (n=44)
    Zone: 15 columns
    Importance: 0.001505
  Predicate: Ti ka > -0.70 (n=64)
    Zone: 15 columns
    Importance: 0.005080
  Predicate: Ti ka <= -0.52 (n=63)
    Zone: 15 columns
    Importance: 0.001133
  Predicate: Ti ka > -0.52 (n=45)
    Zone: 15 columns
    Importance: 0.007111
  Predicate: Ti ka <= 0.53 (n=87)
    Zone: 15 columns
    Importance: 0.001334
  Predicate: Ti kb > -0.32 (n=88)
    Zone: 22 columns
    Importance: 0.000893
  Predicate: Ti kb <= -0.14 (n=45)
    Zone: 22 columns
    Importance: 0.001063
  Predicate: Ti kb > -0.14 (n=63)
    Zone: 22 columns
    Importance: 0.001017
  Predicate: Ti kb <= 0.03 (n=66)
    Zone: 22 columns
    Importance: 0.000791
  Predicate: Ti kb > 0.03 (n=42)
    Zone: 22 columns
    Importance: 0.001422
  Predicate: Ti kb <= 0.20 (n=86)
    Zone: 22 columns
    Importance: 0.000760
  Predicate: background1 > -0.26 (n=90)
    Zone: 33 columns
    Importance: 0.000458
  Predicate: background1 <= -0.08 (n=43)
    Zone: 33 columns
    Importance: 0.000735
  Predicate: background1 > -0.08 (n=65)
    Zone: 33 columns
    Importance: 0.000482
  Predicate: background1 <= 0.11 (n=70)
    Zone: 33 columns
    Importance: 0.000503
  Predicate: background1 > 0.11 (n=38)
    Zone: 33 columns
    Importance: 0.000731
  Predicate: background1 <= 0.30 (n=91)
    Zone: 33 columns
    Importance: 0.000486
  Predicate: Mn > -1.22 (n=88)
    Zone: 20 columns
    Importance: 0.004110
  Predicate: Mn <= -0.41 (n=43)
    Zone: 20 columns
    Importance: 0.005210
  Predicate: Mn > -0.41 (n=65)
    Zone: 20 columns
    Importance: 0.004529
  Predicate: Mn <= 0.23 (n=67)
    Zone: 20 columns
    Importance: 0.003650
  Predicate: Mn > 0.23 (n=41)
    Zone: 20 columns
    Importance: 0.006681
  Predicate: Mn <= 1.01 (n=90)
    Zone: 20 columns
    Importance: 0.003742
  Predicate: Fe ka > -3.74 (n=86)
    Zone: 34 columns
    Importance: 0.012418
  Predicate: Fe ka <= -3.05 (n=44)
    Zone: 34 columns
    Importance: 0.004048
  Predicate: Fe ka > -3.05 (n=64)
    Zone: 34 columns
    Importance: 0.015935
  Predicate: Fe ka <= -2.26 (n=63)
    Zone: 34 columns
    Importance: 0.003064
  Predicate: Fe ka > -2.26 (n=45)
    Zone: 34 columns
    Importance: 0.022332
  Predicate: Fe ka <= 1.10 (n=87)
    Zone: 34 columns
    Importance: 0.003635
  Predicate: Fe kb > -0.91 (n=87)
    Zone: 23 columns
    Importance: 0.000231
  Predicate: Fe kb <= -0.63 (n=41)
    Zone: 23 columns
    Importance: 0.000140
  Predicate: Fe kb > -0.63 (n=67)
    Zone: 23 columns
    Importance: 0.000267
  Predicate: Fe kb <= -0.44 (n=66)
    Zone: 23 columns
    Importance: 0.000125
  Predicate: Fe kb > -0.44 (n=42)
    Zone: 23 columns
    Importance: 0.000367
  Predicate: Fe kb <= 0.33 (n=87)
    Zone: 23 columns
    Importance: 0.000129
  Predicate: Ni > -0.60 (n=88)
    Zone: 25 columns
    Importance: 0.001473
  Predicate: Ni <= -0.14 (n=44)
    Zone: 25 columns
    Importance: 0.001563
  Predicate: Ni > -0.14 (n=64)
    Zone: 25 columns
    Importance: 0.001487
  Predicate: Ni <= 0.13 (n=64)
    Zone: 25 columns
    Importance: 0.001489
  Predicate: Ni > 0.13 (n=44)
    Zone: 25 columns
    Importance: 0.001561
  Predicate: Ni <= 0.59 (n=90)
    Zone: 25 columns
    Importance: 0.001521
  Predicate: Cu > -0.55 (n=89)
    Zone: 39 columns
    Importance: 0.000209
  Predicate: Cu <= -0.12 (n=44)
    Zone: 39 columns
    Importance: 0.000300
  Predicate: Cu > -0.12 (n=64)
    Zone: 39 columns
    Importance: 0.000226
  Predicate: Cu <= 0.09 (n=64)
    Zone: 39 columns
    Importance: 0.000238
  Predicate: Cu > 0.09 (n=44)
    Zone: 39 columns
    Importance: 0.000283
  Predicate: Cu <= 0.56 (n=92)
    Zone: 39 columns
    Importance: 0.000222
  Predicate: Zn > -0.37 (n=87)
    Zone: 19 columns
    Importance: 0.000578
  Predicate: Zn <= -0.11 (n=41)
    Zone: 19 columns
    Importance: 0.000951
  Predicate: Zn > -0.11 (n=67)
    Zone: 19 columns
    Importance: 0.000598
  Predicate: Zn <= 0.10 (n=66)
    Zone: 19 columns
    Importance: 0.000651
  Predicate: Zn > 0.10 (n=42)
    Zone: 19 columns
    Importance: 0.000859
  Predicate: Zn <= 0.34 (n=90)
    Zone: 19 columns
    Importance: 0.000601
  Predicate: background2 > -1.35 (n=88)
    Zone: 215 columns
    Importance: 0.001034
  Predicate: background2 <= -0.51 (n=45)
    Zone: 215 columns
    Importance: 0.001288
  Predicate: background2 > -0.51 (n=63)
    Zone: 215 columns
    Importance: 0.001137
  Predicate: background2 <= 0.35 (n=67)
    Zone: 215 columns
    Importance: 0.000940
  Predicate: background2 > 0.35 (n=41)
    Zone: 215 columns
    Importance: 0.001624
  Predicate: background2 <= 1.51 (n=89)
    Zone: 215 columns
    Importance: 0.000912
  Predicate: sum Fe > -0.60 (n=89)
    Zone: 27 columns
    Importance: 0.000790
  Predicate: sum Fe <= -0.28 (n=44)
    Zone: 27 columns
    Importance: 0.000909
  Predicate: sum Fe > -0.28 (n=64)
    Zone: 27 columns
    Importance: 0.000911
  Predicate: sum Fe <= 0.07 (n=69)
    Zone: 27 columns
    Importance: 0.000624
  Predicate: sum Fe > 0.07 (n=39)
    Zone: 27 columns
    Importance: 0.001417
  Predicate: sum Fe <= 0.62 (n=89)
    Zone: 27 columns
    Importance: 0.000617
  Predicate: background3 > -1.28 (n=88)
    Zone: 219 columns
    Importance: 0.002293
  Predicate: background3 <= -0.62 (n=42)
    Zone: 219 columns
    Importance: 0.003164
  Predicate: background3 > -0.62 (n=66)
    Zone: 219 columns
    Importance: 0.002540
  Predicate: background3 <= 0.14 (n=67)
    Zone: 219 columns
    Importance: 0.002157
  Predicate: background3 > 0.14 (n=41)
    Zone: 219 columns
    Importance: 0.003805
  Predicate: background3 <= 1.47 (n=90)
    Zone: 219 columns
    Importance: 0.002018
  Predicate: Compton scattering > -0.88 (n=86)
    Zone: 85 columns
    Importance: 0.001893
  Predicate: Compton scattering <= -0.40 (n=42)
    Zone: 85 columns
    Importance: 0.002228
  Predicate: Compton scattering > -0.40 (n=66)
    Zone: 85 columns
    Importance: 0.002092
  Predicate: Compton scattering <= 0.05 (n=68)
    Zone: 85 columns
    Importance: 0.001728
  Predicate: Compton scattering > 0.05 (n=40)
    Zone: 85 columns
    Importance: 0.002853
  Predicate: Compton scattering <= 0.87 (n=88)
    Zone: 85 columns
    Importance: 0.001713
  Predicate: Rayleight scattering > -0.50 (n=86)
    Zone: 56 columns
    Importance: 0.000469
  Predicate: Rayleight scattering <= -0.25 (n=43)
    Zone: 56 columns
    Importance: 0.000572
  Predicate: Rayleight scattering > -0.25 (n=65)
    Zone: 56 columns
    Importance: 0.000521
  Predicate: Rayleight scattering <= 0.03 (n=67)
    Zone: 56 columns
    Importance: 0.000434
  Predicate: Rayleight scattering > 0.03 (n=41)
    Zone: 56 columns
    Importance: 0.000717
  Predicate: Rayleight scattering <= 0.53 (n=89)
    Zone: 56 columns
    Importance: 0.000408

[Bag_2] Processing 132 predicates...
  Predicate: Al > -0.68 (n=84)
    Zone: 12 columns
    Importance: 0.000364
  Predicate: Al <= -0.19 (n=46)
    Zone: 12 columns
    Importance: 0.000361
  Predicate: Al > -0.19 (n=62)
    Zone: 12 columns
    Importance: 0.000415
  Predicate: Al <= 0.19 (n=66)
    Zone: 12 columns
    Importance: 0.000291
  Predicate: Al > 0.19 (n=42)
    Zone: 12 columns
    Importance: 0.000552
  Predicate: Al <= 0.62 (n=86)
    Zone: 12 columns
    Importance: 0.000322
  Predicate: Si > -2.51 (n=83)
    Zone: 12 columns
    Importance: 0.187864
  Predicate: Si <= -1.67 (n=47)
    Zone: 12 columns
    Importance: 0.100169
  Predicate: Si > -1.67 (n=61)
    Zone: 12 columns
    Importance: 0.233085
  Predicate: Si <= -0.72 (n=68)
    Zone: 12 columns
    Importance: 0.073492
  Predicate: Si > -0.72 (n=40)
    Zone: 12 columns
    Importance: 0.348216
  Predicate: Si <= 3.71 (n=87)
    Zone: 12 columns
    Importance: 0.098073
  Predicate: P > -1.23 (n=84)
    Zone: 16 columns
    Importance: 0.005049
  Predicate: P <= -0.59 (n=44)
    Zone: 16 columns
    Importance: 0.004382
  Predicate: P > -0.59 (n=64)
    Zone: 16 columns
    Importance: 0.005897
  Predicate: P <= 0.08 (n=65)
    Zone: 16 columns
    Importance: 0.003494
  Predicate: P > 0.08 (n=43)
    Zone: 16 columns
    Importance: 0.007980
  Predicate: P <= 1.06 (n=87)
    Zone: 16 columns
    Importance: 0.003594
  Predicate: S > -0.55 (n=87)
    Zone: 15 columns
    Importance: 0.003451
  Predicate: S <= -0.27 (n=44)
    Zone: 15 columns
    Importance: 0.003467
  Predicate: S > -0.27 (n=64)
    Zone: 15 columns
    Importance: 0.003941
  Predicate: S <= 0.09 (n=66)
    Zone: 15 columns
    Importance: 0.002547
  Predicate: S > 0.09 (n=42)
    Zone: 15 columns
    Importance: 0.005635
  Predicate: S <= 0.55 (n=87)
    Zone: 15 columns
    Importance: 0.002676
  Predicate: Rh L + Ar > -1.66 (n=88)
    Zone: 34 columns
    Importance: 0.020795
  Predicate: Rh L + Ar <= -0.77 (n=42)
    Zone: 34 columns
    Importance: 0.021019
  Predicate: Rh L + Ar > -0.77 (n=66)
    Zone: 34 columns
    Importance: 0.023255
  Predicate: Rh L + Ar <= -0.16 (n=67)
    Zone: 34 columns
    Importance: 0.014375
  Predicate: Rh L + Ar > -0.16 (n=41)
    Zone: 34 columns
    Importance: 0.035476
  Predicate: Rh L + Ar <= 1.37 (n=90)
    Zone: 34 columns
    Importance: 0.015073
  Predicate: K > -6.69 (n=85)
    Zone: 19 columns
    Importance: 0.011883
  Predicate: K <= -1.46 (n=45)
    Zone: 19 columns
    Importance: 0.016245
  Predicate: K > -1.46 (n=63)
    Zone: 19 columns
    Importance: 0.012456
  Predicate: K <= 2.15 (n=64)
    Zone: 19 columns
    Importance: 0.013501
  Predicate: K > 2.15 (n=44)
    Zone: 19 columns
    Importance: 0.014810
  Predicate: K <= 6.26 (n=87)
    Zone: 19 columns
    Importance: 0.011976
  Predicate: Ca ka > -4.65 (n=89)
    Zone: 21 columns
    Importance: 0.131703
  Predicate: Ca ka <= -1.50 (n=41)
    Zone: 21 columns
    Importance: 0.194156
  Predicate: Ca ka > -1.50 (n=67)
    Zone: 21 columns
    Importance: 0.129169
  Predicate: Ca ka <= 1.77 (n=67)
    Zone: 21 columns
    Importance: 0.135602
  Predicate: Ca ka > 1.77 (n=41)
    Zone: 21 columns
    Importance: 0.183644
  Predicate: Ca ka <= 3.95 (n=87)
    Zone: 21 columns
    Importance: 0.126830
  Predicate: Ca kb > -1.81 (n=89)
    Zone: 26 columns
    Importance: 0.021314
  Predicate: Ca kb <= -0.59 (n=41)
    Zone: 26 columns
    Importance: 0.033298
  Predicate: Ca kb > -0.59 (n=67)
    Zone: 26 columns
    Importance: 0.020527
  Predicate: Ca kb <= 0.62 (n=66)
    Zone: 26 columns
    Importance: 0.022773
  Predicate: Ca kb > 0.62 (n=42)
    Zone: 26 columns
    Importance: 0.029465
  Predicate: Ca kb <= 1.57 (n=87)
    Zone: 26 columns
    Importance: 0.020953
  Predicate: Ti ka > -0.86 (n=84)
    Zone: 15 columns
    Importance: 0.004084
  Predicate: Ti ka <= -0.70 (n=45)
    Zone: 15 columns
    Importance: 0.001594
  Predicate: Ti ka > -0.70 (n=63)
    Zone: 15 columns
    Importance: 0.005146
  Predicate: Ti ka <= -0.52 (n=67)
    Zone: 15 columns
    Importance: 0.001162
  Predicate: Ti ka > -0.52 (n=41)
    Zone: 15 columns
    Importance: 0.007757
  Predicate: Ti ka <= 0.53 (n=88)
    Zone: 15 columns
    Importance: 0.001273
  Predicate: Ti kb > -0.32 (n=84)
    Zone: 22 columns
    Importance: 0.000940
  Predicate: Ti kb <= -0.14 (n=44)
    Zone: 22 columns
    Importance: 0.001167
  Predicate: Ti kb > -0.14 (n=64)
    Zone: 22 columns
    Importance: 0.001052
  Predicate: Ti kb <= 0.03 (n=65)
    Zone: 22 columns
    Importance: 0.000856
  Predicate: Ti kb > 0.03 (n=43)
    Zone: 22 columns
    Importance: 0.001466
  Predicate: Ti kb <= 0.20 (n=86)
    Zone: 22 columns
    Importance: 0.000810
  Predicate: background1 > -0.26 (n=89)
    Zone: 33 columns
    Importance: 0.000527
  Predicate: background1 <= -0.08 (n=44)
    Zone: 33 columns
    Importance: 0.000766
  Predicate: background1 > -0.08 (n=64)
    Zone: 33 columns
    Importance: 0.000577
  Predicate: background1 <= 0.11 (n=65)
    Zone: 33 columns
    Importance: 0.000561
  Predicate: background1 > 0.11 (n=43)
    Zone: 33 columns
    Importance: 0.000794
  Predicate: background1 <= 0.30 (n=84)
    Zone: 33 columns
    Importance: 0.000534
  Predicate: Mn > -1.22 (n=85)
    Zone: 20 columns
    Importance: 0.004664
  Predicate: Mn <= -0.41 (n=42)
    Zone: 20 columns
    Importance: 0.005865
  Predicate: Mn > -0.41 (n=66)
    Zone: 20 columns
    Importance: 0.005098
  Predicate: Mn <= 0.23 (n=66)
    Zone: 20 columns
    Importance: 0.004038
  Predicate: Mn > 0.23 (n=42)
    Zone: 20 columns
    Importance: 0.007531
  Predicate: Mn <= 1.01 (n=86)
    Zone: 20 columns
    Importance: 0.004056
  Predicate: Fe ka > -3.74 (n=85)
    Zone: 34 columns
    Importance: 0.012568
  Predicate: Fe ka <= -3.05 (n=45)
    Zone: 34 columns
    Importance: 0.004136
  Predicate: Fe ka > -3.05 (n=63)
    Zone: 34 columns
    Importance: 0.016214
  Predicate: Fe ka <= -2.26 (n=68)
    Zone: 34 columns
    Importance: 0.003006
  Predicate: Fe ka > -2.26 (n=40)
    Zone: 34 columns
    Importance: 0.025080
  Predicate: Fe ka <= 1.10 (n=89)
    Zone: 34 columns
    Importance: 0.003499
  Predicate: Fe kb > -0.91 (n=87)
    Zone: 23 columns
    Importance: 0.000241
  Predicate: Fe kb <= -0.63 (n=41)
    Zone: 23 columns
    Importance: 0.000147
  Predicate: Fe kb > -0.63 (n=67)
    Zone: 23 columns
    Importance: 0.000275
  Predicate: Fe kb <= -0.44 (n=64)
    Zone: 23 columns
    Importance: 0.000132
  Predicate: Fe kb > -0.44 (n=44)
    Zone: 23 columns
    Importance: 0.000365
  Predicate: Fe kb <= 0.33 (n=89)
    Zone: 23 columns
    Importance: 0.000133
  Predicate: Ni > -0.60 (n=87)
    Zone: 25 columns
    Importance: 0.001474
  Predicate: Ni <= -0.14 (n=42)
    Zone: 25 columns
    Importance: 0.001604
  Predicate: Ni > -0.14 (n=66)
    Zone: 25 columns
    Importance: 0.001472
  Predicate: Ni <= 0.13 (n=62)
    Zone: 25 columns
    Importance: 0.001484
  Predicate: Ni > 0.13 (n=46)
    Zone: 25 columns
    Importance: 0.001577
  Predicate: Ni <= 0.59 (n=86)
    Zone: 25 columns
    Importance: 0.001485
  Predicate: Cu > -0.55 (n=88)
    Zone: 39 columns
    Importance: 0.000219
  Predicate: Cu <= -0.12 (n=41)
    Zone: 39 columns
    Importance: 0.000305
  Predicate: Cu > -0.12 (n=67)
    Zone: 39 columns
    Importance: 0.000239
  Predicate: Cu <= 0.09 (n=61)
    Zone: 39 columns
    Importance: 0.000236
  Predicate: Cu > 0.09 (n=47)
    Zone: 39 columns
    Importance: 0.000300
  Predicate: Cu <= 0.56 (n=87)
    Zone: 39 columns
    Importance: 0.000216
  Predicate: Zn > -0.37 (n=87)
    Zone: 19 columns
    Importance: 0.000632
  Predicate: Zn <= -0.11 (n=42)
    Zone: 19 columns
    Importance: 0.000970
  Predicate: Zn > -0.11 (n=66)
    Zone: 19 columns
    Importance: 0.000677
  Predicate: Zn <= 0.10 (n=62)
    Zone: 19 columns
    Importance: 0.000710
  Predicate: Zn > 0.10 (n=46)
    Zone: 19 columns
    Importance: 0.000900
  Predicate: Zn <= 0.34 (n=87)

,Predicate_pert_Seed_0,Predicate_pert_Seed_1,Predicate_pert_Seed_2,Predicate_pert_Seed_3
0,Si > -0.72,Si > -0.72,Si > -0.72,Si > -0.72
1,Si > -1.67,Si > -1.67,Si > -1.67,Si > -1.67
2,Ca ka <= -1.50,Ca ka <= -1.50,Ca ka <= -1.50,Ca ka <= -1.50
3,Si > -2.51,Si > -2.51,Si > -2.51,Ca ka > 1.77
4,Ca ka > 1.77,Ca ka > 1.77,Ca ka > 1.77,Si > -2.51
...,...,...,...,...
132,Fe kb <= -0.44,Class_A,Fe kb <= -0.44,Fe kb <= -0.91
133,Class_A,Class_B,Class_A,Fe kb <= 0.33
134,Class_B,NaN,Class_B,Fe kb <= -0.44
135,NaN,NaN,NaN,Class_A
136,NaN,NaN,NaN,Class_B

In [15]:
all_results_pert[0]['pert_results_dict']['Bag_1']

          Predicate  Perturbation
0        Si > -0.72      0.351742
1        Si > -1.67      0.245000
2        Si > -2.51      0.200761
3    Ca ka <= -1.50      0.195041
4      Ca ka > 1.77      0.192754
..              ...           ...
127      Cu <= 0.56      0.000222
128      Cu > -0.55      0.000209
129  Fe kb <= -0.63      0.000140
130   Fe kb <= 0.33      0.000129
131  Fe kb <= -0.44      0.000125

[132 rows x 2 columns]

In [16]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_pert_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_pert = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_pert = lrc_summed_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_pert = lrc_summed_df_pert.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_pert = lrc_summed_unique_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_pert

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Si > -0.72,9.827576,Si,-0.72,>
1,Ca ka <= -1.50,5.982351,Ca ka,-1.50,<=
2,Rh L + Ar > -0.16,1.343308,Rh L + Ar,-0.16,>
3,Ca kb <= -0.59,1.039111,Ca kb,-0.59,<=
4,Fe ka > -2.26,0.764955,Fe ka,-2.26,>
5,K <= -1.46,0.472870,K,-1.46,<=
6,Ti ka > -0.52,0.253940,Ti ka,-0.52,>
7,P > 0.08,0.222088,P,0.08,>
8,S > 0.55,0.186147,S,0.55,>
9,Mn > 0.23,0.178655,Mn,0.23,>
10,background3 > 0.14,0.105282,background3,0.14,>
11,Compton scattering > 0.05,0.065192,Compton scattering,0.05,>
12,Ni > 0.13,0.026558,Ni,0.13,>
13,background2 > 0.35,0.026532,background2,0.35,>
14,Ti kb > 0.03,0.025527,Ti kb,0.03,>
15,sum Fe > 0.07,0.025172,sum Fe,0.07,>
16,Zn <= -0.37,0.016721,Zn,-0.37,<=
17,background1 > 0.11,0.010253,background1,0.11,>
18,Rayleight scattering > 0.03,0.009714,Rayleight scattering,0.03,>
19,Al > 0.19,0.005558,Al,0.19,>
20,Fe kb > -0.44,0.003254,Fe kb,-0.44,>
21,Cu > 0.09,0.001631,Cu,0.09,>
22,Class_B,0.000000,None,None,None

In [17]:
# Aplicar o mapeamento
lrc_summed_df_pert_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_pert,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_pert_natural

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,Si > -0.72,9.827576,Si,-0.72,>,-2.087044,129.0,0.038926,Si > -2.087044
1,Si > -1.67,7.101716,Si,-1.67,>,-4.200922,133.0,0.023527,Si > -4.200922
2,Ca ka <= -1.50,5.982351,Ca ka,-1.50,<=,-9.476439,94.0,0.083086,Ca ka <= -9.476439
3,Si > -2.51,5.454311,Si,-2.51,>,-6.726367,45.0,0.014243,Si > -6.726367
4,Ca ka > 1.77,5.036615,Ca ka,1.77,>,11.953266,82.0,0.013408,Ca ka > 11.953266
...,...,...,...,...,...,...,...,...,...
133,Fe kb <= -0.91,0.000342,Fe kb,-0.91,<=,-2.342070,115.0,0.002004,Fe kb <= -2.342070
134,Fe kb <= 0.33,0.000295,Fe kb,0.33,<=,0.821719,11.0,0.005205,Fe kb <= 0.821719
135,Fe kb <= -0.44,0.000147,Fe kb,-0.44,<=,-1.196874,106.0,0.000033,Fe kb <= -1.196874
136,Class_B,0.000000,None,None,None,NaN,NaN,NaN,None
137,Class_A,0.000000,None,None,None,NaN,NaN,NaN,None

In [18]:
import plotly.graph_objects as go

n = 0
zone_name = lrc_summed_df_pert_natural.iloc[n]['Zone'] # o n indica a linha do dataframe lrc_summed_df_pert_natural que queremos acessar para pegar o nome da zona espectral (coluna 'Zone')
threshold_score = float(lrc_summed_df_pert_natural.iloc[n]['Threshold_Natural']) # o iloc acessa a linha n e a coluna 'Threshold_Natural' para pegar o valor do threshold já mapeado para o espaço natural (não pré-processado)

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
#print(f"  - Range de energias: {threshold_spectrum.index[n]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_pert_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona 'Si':
  - Dimensão: 12 variáveis espectrais
  - Variância explicada pela PC1: 99.71%

In [19]:
# Permutation importance baseado em mudança nas predições do modelo PLS
# Medimos a média da diferença absoluta entre as predições originais e as predições
# obtidas após permutar cada variável. Isso fornece uma métrica contínua de importância.
n_repeats = 10
rng = np.random.RandomState(42)
# Predições base do modelo PLS
baseline_pred = pls_model.predict(Xcalclass_prep)
importance_list = []
X_arr = Xcalclass_prep.copy()
for col in Xcalclass_prep.columns:
    diffs = []
    for _ in range(n_repeats):
        X_perm = X_arr.copy()
        X_perm[col] = rng.permutation(X_perm[col].values)
        perm_pred = pls_model.predict(X_perm)
        diffs.append(np.mean(np.abs(baseline_pred - perm_pred)))
    importance_list.append(np.mean(diffs))

permutation_df = pd.DataFrame({
    'energy': Xcalclass_prep.columns,
    'Permutation_importance': importance_list
})
permutation_df.sort_values(by='Permutation_importance', ascending=False, inplace=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in permutation_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
permutation_df['Zone'] = permutation_df['energy'].map(energy_to_zone_vip)
permutation_unique_df = permutation_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
permutation_unique_df = permutation_unique_df.sort_values(by='Permutation_importance', ascending=False)
permutation_unique_df

   energy  Permutation_importance                  Zone
0    1.74                0.048290                    Si
1     3.7                0.044434                 Ca ka
2     3.3                0.011805                     K
3    2.62                0.008049             Rh L + Ar
4       4                0.006293                 Ca kb
5    6.46                0.003731                 Fe ka
6    2.04                0.001391                     P
7    5.92                0.001269                    Mn
8     2.3                0.001210                     S
9     4.5                0.000936                 Ti ka
10   1.62                0.000573                    Al
11   7.52                0.000403                    Ni
12  11.99                0.000223           background2
13   4.92                0.000199                 Ti kb
14  18.85                0.000196    Compton scattering
15   7.08                0.000185                 Fe kb
16  13.39                0.000160                sum Fe
17   8.67                0.000152                    Zn
18  14.11                0.000108           background3
19   8.31                0.000089                    Cu
20  20.33                0.000077  Rayleight scattering
21   5.18                0.000060           background1

In [20]:
import numpy as np

max_len = max(
    len(vip_scores_unique_df['Zone']),
    len(reg_vet_unique_df['Zone']),
    len(shap_unique_df['Zone']),
    len(permutation_unique_df['Zone']),
    len(lrc_summed_unique_df_pert['Zone']),
    len(lrc_summed_unique_df_cov['Zone'])
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'VIP_Score': pad_list(vip_scores_unique_df['Zone'], max_len),
    'Reg_Coefficient' : pad_list(reg_vet_unique_df['Zone'], max_len),
    'Shap': pad_list(shap_unique_df['Zone'], max_len),
    'Permutation' : pad_list(permutation_unique_df['Zone'], max_len),
    'LRC_perturbation' : pad_list(lrc_summed_unique_df_pert['Zone'], max_len),
    'LRC_covariance' : pad_list(lrc_summed_unique_df_cov['Zone'], max_len),
})

features_importance.to_csv('feature_importance.csv', index=False, sep=';')
features_importance

,VIP_Score,Reg_Coefficient,Shap,Permutation,LRC_perturbation,LRC_covariance
0,Fe ka,Si,Si,Si,Si,Fe ka
1,K,Ca ka,Ca ka,Ca ka,Ca ka,Ca ka
2,Si,Rh L + Ar,Rh L + Ar,K,Rh L + Ar,Si
3,Ca ka,Ca kb,K,Rh L + Ar,Ca kb,K
4,Ca kb,P,Ca kb,Ca kb,Fe ka,Ti ka
5,Ti ka,K,Fe ka,Fe ka,K,Fe kb
6,Fe kb,S,background1,P,Ti ka,Rh L + Ar
7,Rh L + Ar,Mn,Cu,Mn,P,Ca kb
8,P,Al,Ni,S,S,background3
9,Al,Ni,Fe kb,Ti ka,Mn,Compton scattering
10,Mn,Fe ka,P,Al,background3,Rayleight scattering
11,S,Ti ka,Mn,Ni,Compton scattering,Al
12,Ti kb,Ti kb,Ti ka,background2,Ni,sum Fe
13,sum Fe,background2,S,Ti kb,background2,P
14,Ni,Zn,Ti kb,Compton scattering,Ti kb,Ti kb
15,Compton scattering,Compton scattering,Al,Fe kb,sum Fe,background2
16,background2,Fe kb,Rayleight scattering,sum Fe,Zn,Mn
17,Rayleight scattering,background1,Compton scattering,Zn,background1,S
18,background3,sum Fe,sum Fe,background3,Rayleight scattering,Cu
19,Zn,Cu,background2,Cu,Al,Ni
20,Cu,background3,background3,Rayleight scattering,Fe kb,background1
21,background1,Rayleight scattering,Zn,background1,Cu,Zn
22,None,None,None,None,None,None

In [21]:
import rbo
rbo_comparison = pd.DataFrame(columns=['Method_1', 'Method_2', 'RBO_Score'])
methods = features_importance.columns.tolist()
for i in range(len(methods)):
    for j in range(i + 1, len(methods)):
        method_1 = methods[i]
        method_2 = methods[j]
        # Remove None values from the lists
        list_1 = [x for x in features_importance[method_1].tolist() if x is not None]
        list_2 = [x for x in features_importance[method_2].tolist() if x is not None]
        # Truncate both lists to the same length (minimum of both)
        min_len = min(len(list_1), len(list_2))
        list_1_trunc = list_1[:min_len]
        list_2_trunc = list_2[:min_len]
        rbo_score = rbo.RankingSimilarity(list_1_trunc, list_2_trunc).rbo(p=0.7, k=10)
        rbo_comparison = pd.concat([rbo_comparison, pd.DataFrame({
            'Method_1': [method_1],
            'Method_2': [method_2],
            'RBO_Score': [rbo_score]
        })], ignore_index=True)
rbo_comparison.sort_values(by='RBO_Score', ascending=False, inplace=True)
rbo_comparison.to_csv('rbo_rank.csv', index=False, sep=';')
rbo_comparison

C:\Users\Usuario\AppData\Local\Temp\ipykernel_16236\3097109587.py:16: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

            Method_1          Method_2  RBO_Score
7    Reg_Coefficient  LRC_perturbation   0.926418
10              Shap  LRC_perturbation   0.909796
9               Shap       Permutation   0.900927
5    Reg_Coefficient              Shap   0.891340
12       Permutation  LRC_perturbation   0.872569
6    Reg_Coefficient       Permutation   0.861745
4          VIP_Score    LRC_covariance   0.785558
11              Shap    LRC_covariance   0.420751
13       Permutation    LRC_covariance   0.420751
14  LRC_perturbation    LRC_covariance   0.405078
8    Reg_Coefficient    LRC_covariance   0.359743
2          VIP_Score       Permutation   0.341693
1          VIP_Score              Shap   0.289561
3          VIP_Score  LRC_perturbation   0.277020
0          VIP_Score   Reg_Coefficient   0.232896

In [22]:
lrc_summed_df_cov_natural.to_csv('lrc_cov_natural.csv', index=False, sep=';')
lrc_summed_df_pert_natural.to_csv('lrc_pert_natural.csv', index=False, sep=';')