In [1]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import kennard_stone as ks
pd.options.plotting.backend = 'plotly'  # setting plotly as the backend for pandas plotting

# Add parent directory to sys.path so local module 'synthetic' can be imported
import sys
from pathlib import Path # for path manipulations
# Move three levels up from current working directory to reach workspace root
workspace_root = Path.cwd().parent.parent.parent.resolve() 
smx_dir = workspace_root / 'smx'  # Path to smx folder
if str(smx_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(smx_dir)) # insert at the start of sys.path to prioritize local modules

# Loading a soil spectral dataset based on X-ray fluorescence (XRF)
data_complete = pd.read_csv(f'{workspace_root}/real_datasets/xrf/milk.csv', sep=';') # local copy of Toledo 2022 dataset
data = data_complete.loc[:, '2.66':'22.62']

# Creating a new column 'Class' based on the condition of the samples in the 'Type' column being 'Authentic'
data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.loc[:, '2.66':'22.62'], test_size=0.30) # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.loc[:, '2.66':'22.62'], test_size=0.30) # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)

Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True) # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0]) # creating the target variable for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0]) # creating the target variable for prediction set

# preprocessings
import preprocessings as prepr # preprocessing methods for XRF data

Xcalclass_prep, mean_calclass, mean_calclass_poisson  = prepr.poisson(Xcalclass, mc=True)
Xpredclass_prep = ((Xpredclass/np.sqrt(mean_calclass)) - mean_calclass_poisson)

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-26 16:34:54,819 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-26 16:34:54,842 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-26 16:34:54,886 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-26 16:34:54,951 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [2]:
from modeling import mlp_optimized

mlp_model = mlp_optimized(Xcalclass_prep, ycalclass, Xpredclass_prep, ypredclass, 
                          aim='classification', 
                          hidden_layer_sizes=(64,32),
                          activation='tanh',
                          learning_rate='adaptive',
                          max_iter=10,
                          random_state=1)
mlp_model[0]

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(

,Model,Accuracy Cal,Sensitivity Cal,Specificity Cal,CM Cal,Accuracy Pred,Sensitivity Pred,Specificity Pred,CM Pred
0,MLP,0.981343,0.970238,1.0,"[[100, 0], [5, 163]]",0.721739,0.625,0.883721,"[[38, 5], [27, 45]]"

## Definição das Zonas Espectrais

In [3]:
# establishing spectral cuts based on expert knowledge of XRF spectra
spectral_cuts = [
('Ag La', 2.66, 3.10),
('Ag Lb', 3.10, 3.46),
('Ca', 3.46, 3.92),
('background', 3.92, 6.12),
('Fe', 6.12, 6.68),
('Cu', 6.70, 8.37),
('Zn', 8.37, 9.10),
('Bremsstrahlung', 9.10, 20.06),
('Ag compton', 20.06, 21.62),
('Ag ka', 21.48, 22.62)
]

## SHAP

In [4]:
shap_global_importance = pd.read_csv('shap_milk.csv', sep=';') # loading previously saved shap_unique_df
# vamos gerar uma nova coluna em shap_global_importance com o nome da zona espectral correspondente de acordo com a lista spectral_cuts
energy_to_zone_shap = {}
for zone_name, start, end in spectral_cuts:
    for i in shap_global_importance['energy']:
        i_float = float(i)
        if start <= i_float <= end:
            energy_to_zone_shap[i] = zone_name
shap_global_importance['Zone'] = shap_global_importance['energy'].map(energy_to_zone_shap)

# agora vamos filtrar shap_global_importance para manter apenas as zonas espectrais únicas com maior SHAP score
shap_unique_df = shap_global_importance.sort_values(by='Mean_Abs_SHAP', ascending=False).reset_index(drop=True)
shap_unique_df = shap_unique_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
shap_unique_df

   energy  Mean_Abs_SHAP            Zone
0    3.17       0.021872           Ag Lb
1    3.02       0.019238           Ag La
2   22.28       0.016172           Ag ka
3    8.73       0.006672              Zn
4   21.18       0.004494      Ag compton
5   16.55       0.003386  Bremsstrahlung
6    6.09       0.001753      background
7    6.86       0.001411              Cu
8    6.40       0.001392              Fe
9    3.58       0.000174              Ca

## Funções de Agregação por PCA

Aqui implementamos as funções para agregar zonas espectrais usando PCA com 1 componente principal.

In [5]:
import explaining as exp

# Extração das zonas espectrais
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_scores_df, pca_info_dict = exp.aggregate_spectral_zones_pca(spectral_zones_class) # apca aggregation
print(f"\nScores DataFrame shape: {zone_scores_df.shape}")

Zone 'Ag La': VE = 84.62%, dim = 18 variables
Zone 'Ag Lb': VE = 86.51%, dim = 15 variables
Zone 'Ca': VE = 21.64%, dim = 19 variables
Zone 'background': VE = 3.44%, dim = 87 variables
Zone 'Fe': VE = 12.88%, dim = 23 variables
Zone 'Cu': VE = 9.26%, dim = 66 variables
Zone 'Zn': VE = 17.17%, dim = 29 variables
Zone 'Bremsstrahlung': VE = 30.64%, dim = 429 variables
Zone 'Ag compton': VE = 52.31%, dim = 62 variables
Zone 'Ag ka': VE = 76.93%, dim = 45 variables

Scores DataFrame shape: (268, 10)

In [6]:
y_pred = mlp_model[4]['MLP'].values # using the continuous predictions from SVM, extracting as 1D array
predicates_quantiles = exp.predicates_by_quantiles(zone_scores_df, [0.2, 0.4, 0.6, 0.8])
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_scores_df,
    y_predicted_numeric=y_pred
)

In [7]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_cov = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE

y_pred = pd.Series(mlp_model[4]['MLP'].values) # using the continuous predictions from SVM, extracting as 1D array

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist
    
    # Calcular MI
    cov_results_dict_seed = exp.calculate_predicate_metrics(
        bags_result=bags_result_seed,
        metric='covariance', # covariance ou mutual_information
        threshold=0.01, # threshold para cortar predicados irrelevantes
        n_neighbors=5
    )
    
    # Salvar no dicionário principal
    all_results_cov[seed] = {
        'bags_result': bags_result_seed,
        'cov_results_dict': cov_results_dict_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graph(
        bags_result=all_results_cov[seed]['bags_result'],
        predicate_ranking_dict=all_results_cov[seed]['cov_results_dict'],
        metric_column='Covariance',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )
    # Armazenar grafo
    graphs_by_seed[seed] = DG

# Calcular LRC usando a função pronta do explaining.py
lrc_cov_by_seed = {}
for seed in random_seeds:
    DG = graphs_by_seed[seed]
    lrc_cov_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_cov_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_cov_by_seed[seed] = lrc_cov_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_cov_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_cov_df_seed = lrc_cov_by_seed[seed].rename(columns={'Node': f'Predicate_Cov_Seed_{seed}'})
    lrc_cov_all_seeds_df = pd.concat([lrc_cov_all_seeds_df, lrc_cov_df_seed[[f'Predicate_Cov_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_cov_unique_by_seed = {}
for seed, lrc_df in lrc_cov_by_seed.items():
    lrc_cov_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_cov_unique_df = lrc_cov_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_cov_unique_by_seed[seed] = lrc_cov_unique_df

lrc_cov_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_2 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_3 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_4 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_5 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_6 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_7 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_8 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_9 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_10 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Computing Covariance for Predicates
Metric: covariance
Threshold: 0.01

======================================================================
Processando semente: 1
======================================================================

Bag_1 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_2 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_3 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_4 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_5 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_6 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_7 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_8 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_9 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_10 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Computing Covariance for Predicates
Metric: covariance
Threshold: 0.01

======================================================================
Processando semente: 2
======================================================================

Bag_1 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_2 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_3 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_4 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_5 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_6 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_7 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_8 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_9 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_10 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Computing Covariance for Predicates
Metric: covariance
Threshold: 0.01

======================================================================
Processando semente: 3
======================================================================

Bag_1 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_2 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_3 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_4 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_5 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_6 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_7 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_8 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_9 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_10 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Computing Covariance for Predicates
Metric: covariance
Threshold: 0.01

======================================================================
Processando Grafo - Semente: 0
======================================================================


Total bidirectional pairs found: 69
Removed: Ag Lb <= 2.36 -> Ag La <= 7.76 (5.6885) | Kept: Ag La <= 7.76 -> Ag Lb <= 2.36 (19.8585)
Removed: Ag Lb <= 6.48 -> Ag Lb <= 2.36 (2.5482) | Kept: Ag Lb <= 2.36 -> Ag Lb <= 6.48 (19.2723)
Removed: Bremsstrahlung <= 4.15 -> Bremsstrahlung <= -1.54 (0.2571) | Kept: Bremsstrahlung <= -1.54 -> Bremsstrahlung <= 4.15 (1.0090)
Removed: Bremsstrahlung <= -1.54 -> Ag ka <= 5.37 (0.6917) | Kept: Ag ka <= 5.37 -> Bremsstrahlung <= -1.54 (0.7465)
Removed: Bremsstrahlung <= -1.54 -> Bremsstrahlung > -9.06 (0.1594) | Kept: Bremsstrahlung > -9.06 -> Bremsstrahlung <= -1.54 (0.1859)
Removed: Bremsstrahlung <= 9.64 -> Bremsstrahlung <= 4.15 (0.4550) | Kept: Bremsstrahlung <= 4.15 -> Bremsstrahlung <= 9.64 (1.1721)
Removed: Bremsstrahlung <= 4.15 -> Ag ka > 5.37 (0.6248) | Kept: Ag ka > 5.37 -> Bremsstrahlung <= 4.15 (0.7066)
Removed: Bremsstrahlung <= 9.64 -> Ag ka > 5.37 (0.4315) | Kept: Ag ka > 5.37 -> Bremsstrahlung <= 9.64 (0.5183)
Removed: Bremsstrahlung <= 9.64 -> Ag ka <= 5.37 (0.3594) | Kept: Ag ka <= 5.37 -> Bremsstrahlung <= 9.64 (0.4668)
Removed: Ag ka > 5.37 -> Ag ka <= 5.37 (0.5959) | Kept: Ag ka <= 5.37 -> Ag ka > 5.37 (1.3356)
Removed: Ag compton <= 6.52 -> Ag ka > 5.37 (0.2417) | Kept: Ag ka > 5.37 -> Ag compton <= 6.52 (0.9051)
Removed: Bremsstrahlung > -1.54 -> Ag compton <= 6.52 (0.1690) | Kept: Ag compton <= 6.52 -> Bremsstrahlung > -1.54 (0.3028)
Removed: Ag compton <= -1.09 -> Ag compton <= 6.52 (0.2633) | Kept: Ag compton <= 6.52 -> Ag compton <= -1.09 (0.7929)
Removed: Bremsstrahlung > -9.06 -> Ag compton <= 6.52 (0.2013) | Kept: Ag compton <= 6.52 -> Bremsstrahlung > -9.06 (0.2822)
Removed: Bremsstrahlung > -9.06 -> Bremsstrahlung > -1.54 (0.1599) | Kept: Bremsstrahlung > -1.54 -> Bremsstrahlung > -9.06 (0.4179)
Removed: Bremsstrahlung > -1.54 -> Ag compton > -6.71 (0.0948) | Kept: Ag compton > -6.71 -> Bremsstrahlung > -1.54 (0.1356)
Removed: Bremsstrahlung > 4.15 -> Bremsstrahlung > -1.54 (0.1712) | Kept: Bremsstrahlung > -1.54 -> Bremsstrahlung > 4.15 (0.5496)
Removed: Ag compton <= -1.09 -> Ag La > -18.52 (0.1781) | Kept: Ag La > -18.52 -> Ag compton <= -1.09 (0.3568)
Removed: Ag La > -18.52 -> Ag compton <= 2.96 (0.2821) | Kept: Ag compton <= 2.96 -> Ag La > -18.52 (0.5304)
Removed: Ag compton <= 2.96 -> Ag Lb > -15.87 (0.1984) | Kept: Ag Lb > -15.87 -> Ag compton <= 2.96 (0.2098)
Removed: Ag compton > -6.71 -> Ag La > -18.52 (0.1100) | Kept: Ag La > -18.52 -> Ag compton > -6.71 (0.2885)
Removed: Ag La > -18.52 -> Ag ka <= 20.95 (0.2612) | Kept: Ag ka <= 20.95 -> Ag La > -18.52 (0.5739)
Removed: Ag compton > -6.71 -> Ag compton > -1.09 (0.2700) | Kept: Ag compton > -1.09 -> Ag compton > -6.71 (0.3529)
Removed: Ag ka <= 20.95 -> Ag ka <= -7.06 (0.1831) | Kept: Ag ka <= -7.06 -> Ag ka <= 20.95 (0.2419)
Removed: Ag ka <= -7.06 -> Ag compton > -1.09 (0.1772) | Kept: Ag compton > -1.09 -> Ag ka <= -7.06 (0.2499)
Removed: Ag ka <= -7.06 -> Ag ka > -7.06 (0.1004) | Kept: Ag ka > -7.06 -> Ag ka <= -7.06 (0.1380)
Removed: Ag Lb > 2.36 -> Ag compton > -1.09 (0.1868) | Kept: Ag compton > -1.09 -> Ag Lb > 2.36 (0.2714)
Removed: Ag Lb > 2.36 -> Ag La > 2.70 (0.5502) | Kept: Ag La > 2.70 -> Ag Lb > 2.36 (0.5691)
Removed: Ag La > 2.70 -> Ag Lb > -15.87 (0.1622) | Kept: Ag Lb > -15.87 -> Ag La > 2.70 (0.2510)
Removed: Cu > 0.32 -> Ca <= -0.68 (0.0127) | Kept: Ca <= -0.68 -> Cu > 0.32 (0.0222)
Removed: Cu > 0.32 -> Ca > -0.68 (0.0163) | Kept: Ca > -0.68 -> Cu > 0.32 (0.0198)
Removed: Cu > 0.32 -> Fe > -1.18 (0.0106) | Kept: Fe > -1.18 -> Cu > 0.32 (0.0117)
Removed: Cu > 0.32 -> Fe > 0.31 (0.0079) | Kept: Fe > 0.31 -> Cu > 0.32 (0.0113)
Removed: Fe > -1.18 -> Ca <= -0.68 (0.0134) | Kept: Ca <= -0.68 -> Fe > -1.18 (0.0212)
Removed: Ca > -1.79 -> Ca <= -0.68 (0.0224) | Kept: Ca <= -0.68 -> Ca > -1.79 (0.0527)
Removed: Ca <= -0.68 -> Ag ka > -11.59 (0.0313) | Kept: Ag ka > -11.59 -> Ca <= -0.68 (0.0859)
Removed: Ca <= -0.68 -> Ca > -0.68 (0.0179) | Kept: Ca > -0.68 -> Ca <= -0.68 (0.0259)
Removed: Fe > 0.31 -> Ca > 0.46 (0.0106) | Kept: Ca > 0.46 -> Fe > 0.31 (0.0233)
Removed: Ca <= 0.46 -> Ca > 0.46 (0.0215) | Kept: Ca > 0.46 -> Ca <= 0.46 (0.0219)
Removed: Zn > 0.56 -> Ag compton > 2.96 (0.0169) | Kept: Ag compton > 2.96 -> Zn > 0.56 (0.1469)
Removed: Fe > -1.18 -> Zn > 0.56 (0.0109) | Kept: Zn > 0.56 -> Fe > -1.18 (0.0155)
Removed: Fe > 0.31 -> Ag Lb > -15.87 (0.0122) | Kept: Ag Lb > -15.87 -> Fe > 0.31 (0.0661)
Removed: Cu > -1.74 -> Ag La > 7.76 (0.0069) | Kept: Ag La > 7.76 -> Cu > -1.74 (0.0157)
Removed: background > 0.40 -> Cu > -1.74 (0.0013) | Kept: Cu > -1.74 -> background > 0.40 (0.0017)
Removed: Cu > -1.74 -> Ag ka > -11.59 (0.0046) | Kept: Ag ka > -11.59 -> Cu > -1.74 (0.0219)
Removed: Fe > 0.31 -> Ca > -1.79 (0.0133) | Kept: Ca > -1.79 -> Fe > 0.31 (0.0390)
Removed: Ca <= 1.81 -> Ca > -1.79 (0.0206) | Kept: Ca > -1.79 -> Ca <= 1.81 (0.0221)
Removed: Fe > 0.31 -> Ag compton > 2.96 (0.0268) | Kept: Ag compton > 2.96 -> Fe > 0.31 (0.0409)
Removed: Fe > 0.31 -> Ca > -0.68 (0.0098) | Kept: Ca > -0.68 -> Fe > 0.31 (0.0235)
Removed: Fe > -1.18 -> Fe > -0.36 (0.0085) | Kept: Fe > -0.36 -> Fe > -1.18 (0.0124)
Removed: Fe > -1.18 -> Ca > -0.68 (0.0119) | Kept: Ca > -0.68 -> Fe > -1.18 (0.0363)
Removed: background > -1.23 -> Cu > -0.64 (0.0004) | Kept: Cu > -0.64 -> background > -1.23 (0.0088)
Removed: Cu > -0.64 -> Fe <= 0.31 (0.0025) | Kept: Fe <= 0.31 -> Cu > -0.64 (0.0092)
Removed: Fe > -0.36 -> Ca <= 1.81 (0.0090) | Kept: Ca <= 1.81 -> Fe > -0.36 (0.0149)
Removed: Ca <= 1.81 -> Ag Lb > 6.48 (0.0167) | Kept: Ag Lb > 6.48 -> Ca <= 1.81 (0.0514)
Removed: Ca <= 1.81 -> Ca <= 0.46 (0.0342) | Kept: Ca <= 0.46 -> Ca <= 1.81 (0.0415)
Removed: Cu <= 1.92 -> Ca <= 0.46 (0.0056) | Kept: Ca <= 0.46 -> Cu <= 1.92 (0.0118)
Removed: background <= -0.46 -> Ag La > 7.76 (0.0007) | Kept: Ag La > 7.76 -> background <= -0.46 (0.0189)
Removed: Zn > -1.47 -> Ca > -0.68 (0.0133) | Kept: Ca > -0.68 -> Zn > -1.47 (0.0136)
Removed: Cu <= -0.64 -> Zn <= 0.56 (0.0018) | Kept: Zn <= 0.56 -> Cu <= -0.64 (0.0053)
Removed: Cu <= 0.32 -> Zn <= 1.56 (0.0034) | Kept: Zn <= 1.56 -> Cu <= 0.32 (0.0045)
Removed: background > -1.23 -> Ag Lb > 6.48 (0.0021) | Kept: Ag Lb > 6.48 -> background > -1.23 (0.0385)
Removed: Zn > -1.47 -> Ag Lb > 6.48 (0.0109) | Kept: Ag Lb > 6.48 -> Zn > -1.47 (0.1222)
Removed: background <= 1.29 -> Ag Lb > 6.48 (0.0020) | Kept: Ag Lb > 6.48 -> background <= 1.29 (0.0502)
Removed: background > -0.46 -> Cu <= 0.32 (0.0007) | Kept: Cu <= 0.32 -> background > -0.46 (0.0036)
Removed: Fe <= 0.31 -> Zn > -0.39 (0.0029) | Kept: Zn > -0.39 -> Fe <= 0.31 (0.0104)
Removed: Fe <= 1.20 -> Zn <= 0.56 (0.0029) | Kept: Zn <= 0.56 -> Fe <= 1.20 (0.0031)
Removed: Fe <= 1.20 -> background <= 0.40 (0.0017) | Kept: background <= 0.40 -> Fe <= 1.20 (0.0037)
Removed: Cu <= 0.32 -> Zn <= -0.39 (0.0023) | Kept: Zn <= -0.39 -> Cu <= 0.32 (0.0068)

======================================================================
CONSTRUCTED GRAPH SUMMARY
======================================================================
Initial edges: 422 | Removed: 69
Predicate nodes: 60
Metric: Covariance
Weighting by explained variance: ENABLED

======================================================================
Processando Grafo - Semente: 1
======================================================================


Total bidirectional pairs found: 65
Removed: Ag Lb <= 6.48 -> Ag Lb <= 2.36 (2.5519) | Kept: Ag Lb <= 2.36 -> Ag Lb <= 6.48 (25.1768)
Removed: Bremsstrahlung <= -1.54 -> Ag ka <= 5.37 (0.2293) | Kept: Ag ka <= 5.37 -> Bremsstrahlung <= -1.54 (3.1058)
Removed: Bremsstrahlung > -9.06 -> Ag ka <= 5.37 (0.1321) | Kept: Ag ka <= 5.37 -> Bremsstrahlung > -9.06 (0.3033)
Removed: Bremsstrahlung <= -1.54 -> Bremsstrahlung > -9.06 (0.1564) | Kept: Bremsstrahlung > -9.06 -> Bremsstrahlung <= -1.54 (0.2140)
Removed: Bremsstrahlung <= 4.15 -> Bremsstrahlung <= -1.54 (0.2413) | Kept: Bremsstrahlung <= -1.54 -> Bremsstrahlung <= 4.15 (0.7696)
Removed: Ag compton > -6.71 -> Ag ka <= -7.06 (0.1341) | Kept: Ag ka <= -7.06 -> Ag compton > -6.71 (0.1731)
Removed: Ag La > -18.52 -> Ag ka <= -7.06 (0.1810) | Kept: Ag ka <= -7.06 -> Ag La > -18.52 (0.3736)
Removed: Bremsstrahlung > 4.15 -> Ag ka <= -7.06 (0.0855) | Kept: Ag ka <= -7.06 -> Bremsstrahlung > 4.15 (0.4004)
Removed: Bremsstrahlung <= 9.64 -> Bremsstrahlung <= 4.15 (0.4341) | Kept: Bremsstrahlung <= 4.15 -> Bremsstrahlung <= 9.64 (0.8395)
Removed: Bremsstrahlung <= 4.15 -> Ag ka > 5.37 (0.4187) | Kept: Ag ka > 5.37 -> Bremsstrahlung <= 4.15 (2.0333)
Removed: Ca <= -0.68 -> Ag ka > -11.59 (0.0249) | Kept: Ag ka > -11.59 -> Ca <= -0.68 (0.1070)
Removed: Bremsstrahlung > -1.54 -> Bremsstrahlung <= 9.64 (0.1947) | Kept: Bremsstrahlung <= 9.64 -> Bremsstrahlung > -1.54 (0.3006)
Removed: Bremsstrahlung <= 9.64 -> Ag ka > 5.37 (0.1965) | Kept: Ag ka > 5.37 -> Bremsstrahlung <= 9.64 (0.6424)
Removed: Bremsstrahlung > 4.15 -> Bremsstrahlung <= 9.64 (0.1501) | Kept: Bremsstrahlung <= 9.64 -> Bremsstrahlung > 4.15 (0.1595)
Removed: Bremsstrahlung > -9.06 -> Bremsstrahlung > -1.54 (0.1104) | Kept: Bremsstrahlung > -1.54 -> Bremsstrahlung > -9.06 (0.2771)
Removed: Bremsstrahlung > -1.54 -> Bremsstrahlung > 4.15 (0.1012) | Kept: Bremsstrahlung > 4.15 -> Bremsstrahlung > -1.54 (0.3002)
Removed: Bremsstrahlung > -9.06 -> Ag La > -18.52 (0.1102) | Kept: Ag La > -18.52 -> Bremsstrahlung > -9.06 (0.2753)
Removed: Bremsstrahlung > -9.06 -> Ag ka > 5.37 (0.1987) | Kept: Ag ka > 5.37 -> Bremsstrahlung > -9.06 (0.5790)
Removed: Bremsstrahlung > 4.15 -> Ag compton <= 6.52 (0.1391) | Kept: Ag compton <= 6.52 -> Bremsstrahlung > 4.15 (0.4927)
Removed: Ag ka <= 20.95 -> Ag compton <= 2.96 (0.1243) | Kept: Ag compton <= 2.96 -> Ag ka <= 20.95 (0.1923)
Removed: Ag compton > -6.71 -> Ag ka <= 20.95 (0.1755) | Kept: Ag ka <= 20.95 -> Ag compton > -6.71 (0.2179)
Removed: Ag compton <= 6.52 -> Ag ka <= 20.95 (0.2502) | Kept: Ag ka <= 20.95 -> Ag compton <= 6.52 (0.3072)
Removed: Ag compton <= -1.09 -> Ag La > -18.52 (0.3482) | Kept: Ag La > -18.52 -> Ag compton <= -1.09 (0.3493)
Removed: Ag compton <= 2.96 -> Ag Lb > 2.36 (0.1295) | Kept: Ag Lb > 2.36 -> Ag compton <= 2.96 (0.1835)
Removed: Ag compton > -1.09 -> Ag Lb > 2.36 (0.1218) | Kept: Ag Lb > 2.36 -> Ag compton > -1.09 (0.3666)
Removed: Ag Lb > 2.36 -> Ag La > 2.70 (0.2309) | Kept: Ag La > 2.70 -> Ag Lb > 2.36 (0.6435)
Removed: Ag Lb > 2.36 -> Ag compton > -6.71 (0.1805) | Kept: Ag compton > -6.71 -> Ag Lb > 2.36 (0.3635)
Removed: Ag La > 2.70 -> Ag compton > -1.09 (0.2034) | Kept: Ag compton > -1.09 -> Ag La > 2.70 (0.2616)
Removed: Ag compton > -6.71 -> Ag compton > -1.09 (0.2438) | Kept: Ag compton > -1.09 -> Ag compton > -6.71 (0.3201)
Removed: Ag La > 2.70 -> Ag Lb > -15.87 (0.1796) | Kept: Ag Lb > -15.87 -> Ag La > 2.70 (0.6551)
Removed: Cu > 0.32 -> Ca > 0.46 (0.0114) | Kept: Ca > 0.46 -> Cu > 0.32 (0.0254)
Removed: Cu > 0.32 -> Ca <= -0.68 (0.0102) | Kept: Ca <= -0.68 -> Cu > 0.32 (0.0249)
Removed: Ca <= -0.68 -> Zn > 0.56 (0.0284) | Kept: Zn > 0.56 -> Ca <= -0.68 (0.0422)
Removed: Ca <= -0.68 -> Ca <= 0.46 (0.0231) | Kept: Ca <= 0.46 -> Ca <= -0.68 (0.0238)
Removed: Zn > 0.56 -> Ca > -1.79 (0.0359) | Kept: Ca > -1.79 -> Zn > 0.56 (0.0686)
Removed: Ca <= 1.81 -> Ca > -1.79 (0.0215) | Kept: Ca > -1.79 -> Ca <= 1.81 (0.0233)
Removed: Fe > 0.31 -> Ca > -1.79 (0.0137) | Kept: Ca > -1.79 -> Fe > 0.31 (0.0402)
Removed: Zn > 0.56 -> Fe > -1.18 (0.0184) | Kept: Fe > -1.18 -> Zn > 0.56 (0.0264)
Removed: Zn > 0.56 -> Ca > -0.68 (0.0179) | Kept: Ca > -0.68 -> Zn > 0.56 (0.0506)
Removed: Cu > 0.32 -> Fe > -1.18 (0.0106) | Kept: Fe > -1.18 -> Cu > 0.32 (0.0138)
Removed: Fe > -1.18 -> Ca <= 0.46 (0.0085) | Kept: Ca <= 0.46 -> Fe > -1.18 (0.0409)
Removed: Fe > -1.18 -> Zn > -1.47 (0.0084) | Kept: Zn > -1.47 -> Fe > -1.18 (0.0139)
Removed: Ca > -0.68 -> Cu > 0.32 (0.0189) | Kept: Cu > 0.32 -> Ca > -0.68 (0.0202)
Removed: Fe > -0.36 -> Ca > -0.68 (0.0119) | Kept: Ca > -0.68 -> Fe > -0.36 (0.0155)
Removed: Fe > -0.36 -> Zn > -1.47 (0.0069) | Kept: Zn > -1.47 -> Fe > -0.36 (0.0146)
Removed: Fe > -0.36 -> Ca <= 1.81 (0.0111) | Kept: Ca <= 1.81 -> Fe > -0.36 (0.0153)
Removed: Ca > -0.68 -> Ca <= 0.46 (0.0179) | Kept: Ca <= 0.46 -> Ca > -0.68 (0.0191)
Removed: Zn > -0.39 -> Ag compton > 2.96 (0.0112) | Kept: Ag compton > 2.96 -> Zn > -0.39 (0.0310)
Removed: background > -1.23 -> Zn > -1.47 (0.0024) | Kept: Zn > -1.47 -> background > -1.23 (0.0121)
Removed: background > -1.23 -> Fe <= 1.20 (0.0021) | Kept: Fe <= 1.20 -> background > -1.23 (0.0040)
Removed: background <= 1.29 -> Ca <= 0.46 (0.0018) | Kept: Ca <= 0.46 -> background <= 1.29 (0.0127)
Removed: Fe <= 1.20 -> Zn > -0.39 (0.0077) | Kept: Zn > -0.39 -> Fe <= 1.20 (0.0146)
Removed: Zn > -0.39 -> Ag Lb > 6.48 (0.0171) | Kept: Ag Lb > 6.48 -> Zn > -0.39 (0.0536)
Removed: background > -0.46 -> Fe <= 1.20 (0.0015) | Kept: Fe <= 1.20 -> background > -0.46 (0.0103)
Removed: Fe <= 1.20 -> Ag La > 7.76 (0.0021) | Kept: Ag La > 7.76 -> Fe <= 1.20 (0.0276)
Removed: Cu <= -0.64 -> Fe <= 1.20 (0.0016) | Kept: Fe <= 1.20 -> Cu <= -0.64 (0.0018)
Removed: Fe <= -0.36 -> Fe <= 1.20 (0.0022) | Kept: Fe <= 1.20 -> Fe <= -0.36 (0.0028)
Removed: background > 0.40 -> background > -0.46 (0.0010) | Kept: background > -0.46 -> background > 0.40 (0.0015)
Removed: background > -0.46 -> background <= 1.29 (0.0022) | Kept: background <= 1.29 -> background > -0.46 (0.0030)
Removed: Zn <= 0.56 -> Ag Lb > 6.48 (0.0065) | Kept: Ag Lb > 6.48 -> Zn <= 0.56 (0.0395)
Removed: Zn <= 0.56 -> Cu <= 1.92 (0.0028) | Kept: Cu <= 1.92 -> Zn <= 0.56 (0.0047)
Removed: background <= 0.40 -> Cu <= -0.64 (0.0007) | Kept: Cu <= -0.64 -> background <= 0.40 (0.0026)
Removed: background <= 0.40 -> Cu > -0.64 (0.0009) | Kept: Cu > -0.64 -> background <= 0.40 (0.0045)
Removed: Cu > -0.64 -> Zn <= -0.39 (0.0061) | Kept: Zn <= -0.39 -> Cu > -0.64 (0.0141)
Removed: background <= -0.46 -> Ag La > 7.76 (0.0015) | Kept: Ag La > 7.76 -> background <= -0.46 (0.0379)

======================================================================
CONSTRUCTED GRAPH SUMMARY
======================================================================
Initial edges: 393 | Removed: 65
Predicate nodes: 60
Metric: Covariance
Weighting by explained variance: ENABLED

======================================================================
Processando Grafo - Semente: 2
======================================================================


Total bidirectional pairs found: 66
Removed: Ag La <= 7.76 -> Ag La <= 2.70 (3.1217) | Kept: Ag La <= 2.70 -> Ag La <= 7.76 (28.2643)
Removed: Ag Lb <= 6.48 -> Ag Lb <= 2.36 (2.6419) | Kept: Ag Lb <= 2.36 -> Ag Lb <= 6.48 (25.1763)
Removed: Bremsstrahlung > -9.06 -> Ag ka > 5.37 (0.2109) | Kept: Ag ka > 5.37 -> Bremsstrahlung > -9.06 (1.2231)
Removed: Bremsstrahlung <= -1.54 -> Ag ka > 5.37 (0.2668) | Kept: Ag ka > 5.37 -> Bremsstrahlung <= -1.54 (1.7909)
Removed: Ag ka <= 5.37 -> Ag ka > 5.37 (0.7255) | Kept: Ag ka > 5.37 -> Ag ka <= 5.37 (0.8103)
Removed: Bremsstrahlung > -1.54 -> Bremsstrahlung > -9.06 (0.1561) | Kept: Bremsstrahlung > -9.06 -> Bremsstrahlung > -1.54 (0.3869)
Removed: Bremsstrahlung > -9.06 -> Bremsstrahlung <= 9.64 (0.1743) | Kept: Bremsstrahlung <= 9.64 -> Bremsstrahlung > -9.06 (0.3513)
Removed: Bremsstrahlung > -9.06 -> Ag compton <= 6.52 (0.1516) | Kept: Ag compton <= 6.52 -> Bremsstrahlung > -9.06 (0.4440)
Removed: Bremsstrahlung > -9.06 -> Ag ka <= 5.37 (0.2201) | Kept: Ag ka <= 5.37 -> Bremsstrahlung > -9.06 (0.2692)
Removed: Ag compton <= 6.52 -> Bremsstrahlung > 4.15 (0.2813) | Kept: Bremsstrahlung > 4.15 -> Ag compton <= 6.52 (0.4011)
Removed: Bremsstrahlung > 4.15 -> Bremsstrahlung <= 4.15 (0.1770) | Kept: Bremsstrahlung <= 4.15 -> Bremsstrahlung > 4.15 (0.2388)
Removed: Bremsstrahlung > 4.15 -> Ag ka <= 20.95 (0.0531) | Kept: Ag ka <= 20.95 -> Bremsstrahlung > 4.15 (0.3964)
Removed: Bremsstrahlung <= -1.54 -> Ag ka <= 5.37 (0.5458) | Kept: Ag ka <= 5.37 -> Bremsstrahlung <= -1.54 (1.4083)

,Predicate_Cov_Seed_0,Predicate_Cov_Seed_1,Predicate_Cov_Seed_2,Predicate_Cov_Seed_3
0,Ag La <= 2.70,Ag La <= 2.70,Ag La <= 2.70,Ag La <= 2.70
1,Ag La <= 7.76,Ag La <= 7.76,Ag La <= 7.76,Ag La <= 7.76
2,Ag Lb <= 2.36,Ag Lb <= 2.36,Ag Lb <= 2.36,Ag Lb <= 2.36
3,Ag Lb <= 6.48,Ag Lb <= 6.48,Ag Lb <= 6.48,Ag Lb <= 6.48
4,Ag La <= 9.01,Ag La <= 9.01,Ag La <= 9.01,Ag La <= 9.01
...,...,...,...,...
57,Cu <= -0.64,Fe <= 0.31,background > 0.40,Cu > -0.64
58,background > -0.46,Ag La > 7.76,background <= 1.29,background <= 0.40
59,Fe <= -0.36,background > 0.40,Fe <= -0.36,background <= -0.46
60,Class_A,Class_A,Class_A,Class_A
61,Class_B,Class_B,Class_B,Class_B

In [8]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_cov_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_cov = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_cov = lrc_summed_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_cov = lrc_summed_df_cov.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
#lrc_summed_unique_df_cov = lrc_summed_unique_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_cov

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Ag La <= 2.70,28.218676,Ag La,2.70,<=
1,Ag Lb <= 2.36,20.990665,Ag Lb,2.36,<=
2,Ag ka <= 5.37,0.817253,Ag ka,5.37,<=
3,Bremsstrahlung <= 4.15,0.720486,Bremsstrahlung,4.15,<=
4,Ag compton <= 6.52,0.605184,Ag compton,6.52,<=
5,Cu > 0.32,0.289875,Cu,0.32,>
6,Ca <= -0.68,0.279436,Ca,-0.68,<=
7,background <= -0.46,0.251596,background,-0.46,<=
8,Fe > -1.18,0.239142,Fe,-1.18,>
9,Zn > 0.56,0.228150,Zn,0.56,>
10,Class_A,0.000000,None,None,None

In [9]:
# Criar zone_sums_df para dados NÃO pré-processados (Xcalclass)
spectral_zones_original = exp.extract_spectral_zones(Xcalclass, spectral_cuts)
zones_original = exp.aggregate_spectral_zones_pca(spectral_zones_original) # apca aggregation

# Aplicar o mapeamento
lrc_summed_df_cov_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_cov,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_cov_natural

Zone 'Ag La': VE = 91.39%, dim = 18 variables
Zone 'Ag Lb': VE = 90.27%, dim = 15 variables
Zone 'Ca': VE = 27.70%, dim = 19 variables
Zone 'background': VE = 3.72%, dim = 87 variables
Zone 'Fe': VE = 14.68%, dim = 23 variables
Zone 'Cu': VE = 15.48%, dim = 66 variables
Zone 'Zn': VE = 21.60%, dim = 29 variables
Zone 'Bremsstrahlung': VE = 38.87%, dim = 429 variables
Zone 'Ag compton': VE = 52.69%, dim = 62 variables
Zone 'Ag ka': VE = 80.83%, dim = 45 variables

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,Ag La <= 2.70,28.218676,Ag La,2.70,<=,34.935039,86.0,0.021418,Ag La <= 34.935039
1,Ag La <= 7.76,24.327379,Ag La,7.76,<=,105.814886,78.0,0.002963,Ag La <= 105.814886
2,Ag Lb <= 2.36,20.990665,Ag Lb,2.36,<=,30.578162,0.0,0.008013,Ag Lb <= 30.578162
3,Ag Lb <= 6.48,16.657994,Ag Lb,6.48,<=,75.496450,98.0,0.013050,Ag Lb <= 75.496450
4,Ag La <= 9.01,10.865589,Ag La,9.01,<=,126.903607,239.0,0.004801,Ag La <= 126.903607
...,...,...,...,...,...,...,...,...,...
57,Cu > -0.64,0.134470,Cu,-0.64,>,-1.435498,17.0,0.000042,Cu > -1.435498
58,background > 0.40,0.128819,background,0.40,>,4.852293,186.0,0.003287,background > 4.852293
59,Fe <= -0.36,0.104788,Fe,-0.36,<=,0.719116,9.0,0.001198,Fe <= 0.719116
60,Class_A,0.000000,None,None,None,NaN,NaN,NaN,None
61,Class_B,0.000000,None,None,None,NaN,NaN,NaN,None

## Reconstrução de Thresholds Multivariados

Agora vamos pegar os thresholds dos predicados mais importantes e reconstruí-los como espectros completos.

In [10]:
import plotly.graph_objects as go

n = 0
zone_name = lrc_summed_df_cov_natural.iloc[n]['Zone']
threshold_score = float(lrc_summed_df_cov_natural.iloc[n]['Threshold_Natural'])  # Corrigido: usa n em vez de 7

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
print(f"  - Range de energias: {threshold_spectrum.index[0]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_cov_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona 'Ag La':
  - Dimensão: 18 variáveis espectrais
  - Range de energias: 2.66 - 3.10
  - Variância explicada pela PC1: 91.39%

In [11]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = exp.calculate_predicate_perturbation(
        estimator=mlp_model[3],
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        #perturbation_value=0,
        perturbation_mode='median', # valores entre 'mean' ou 'min'
        stats_source='full', # full indica usar todas as amostras para calcular estatísticas enquanto que 'fold' usa apenas as amostras do fold atual
        #metric='mean_abs_diff',   # Média com sinal (pode ser negativo)
        aim='classification',
        metric='probability_shift', 
        verbose=True
    )

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graph(
        bags_result=all_results_pert[seed]['bags_result'],
        predicate_ranking_dict=all_results_pert[seed]['pert_results_dict'],
        metric_column='Perturbation',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )

    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_2 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_3 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_4 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_5 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_6 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_7 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_8 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_9 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
Bag_10 | Samples: Yes | Predicates: No (All) | Valid: 60 | Discarded: 20
======================================================================
PERTURBATION IMPORTANCE FOR PREDICATES
======================================================================
Task type (aim): classification
Perturbation mode: median
Statistics source: full
Metric: probability_shift
Total folds: 10


[Bag_1] Processing 60 predicates...
  Predicate: Ag La > -18.52 (n=176)
    Zone: 18 columns
    Importance: 0.046839
  Predicate: Ag La <= 2.70 (n=81)
    Zone: 18 columns
    Importance: 0.218193
  Predicate: Ag La > 2.70 (n=133)
    Zone: 18 columns
    Importance: 0.024039
  Predicate: Ag La <= 7.76 (n=130)
    Zone: 18 columns
    Importance: 0.141935
  Predicate: Ag La > 7.76 (n=84)
    Zone: 18 columns
    Importance: 0.028800
  Predicate: Ag La <= 9.01 (n=171)
    Zone: 18 columns
    Importance: 0.113973
  Predicate: Ag Lb > -15.87 (n=173)
    Zone: 15 columns
    Importance: 0.029933
  Predicate: Ag Lb <= 2.36 (n=82)
    Zone: 15 columns
    Importance: 0.165061
  Predicate: Ag Lb > 2.36 (n=132)
    Zone: 15 columns
    Importance: 0.018581
  Predicate: Ag Lb <= 6.48 (n=129)
    Zone: 15 columns
    Importance: 0.109012
  Predicate: Ag Lb > 6.48 (n=85)
    Zone: 15 columns
    Importance: 0.022649
  Predicate: Ag Lb <= 8.04 (n=170)
    Zone: 15 columns
    Importance: 0.087615
  Predicate: Ca > -1.79 (n=172)
    Zone: 19 columns
    Importance: 0.011000
  Predicate: Ca <= -0.68 (n=85)
    Zone: 19 columns
    Importance: 0.010511
  Predicate: Ca > -0.68 (n=129)
    Zone: 19 columns
    Importance: 0.011332
  Predicate: Ca <= 0.46 (n=128)
    Zone: 19 columns
    Importance: 0.010288
  Predicate: Ca > 0.46 (n=86)
    Zone: 19 columns
    Importance: 0.012075
  Predicate: Ca <= 1.81 (n=175)
    Zone: 19 columns
    Importance: 0.009915
  Predicate: background > -1.23 (n=175)
    Zone: 87 columns
    Importance: 0.030481
  Predicate: background <= -0.46 (n=84)
    Zone: 87 columns
    Importance: 0.026081
  Predicate: background > -0.46 (n=130)
    Zone: 87 columns
    Importance: 0.031033
  Predicate: background <= 0.40 (n=127)
    Zone: 87 columns
    Importance: 0.029050
  Predicate: background > 0.40 (n=87)
    Zone: 87 columns
    Importance: 0.029146
  Predicate: background <= 1.29 (n=172)
    Zone: 87 columns
    Importance: 0.031007
  Predicate: Fe > -1.18 (n=173)
    Zone: 23 columns
    Importance: 0.014033
  Predicate: Fe <= -0.36 (n=81)
    Zone: 23 columns
    Importance: 0.016958
  Predicate: Fe > -0.36 (n=133)
    Zone: 23 columns
    Importance: 0.013439
  Predicate: Fe <= 0.31 (n=122)
    Zone: 23 columns
    Importance: 0.014997
  Predicate: Fe > 0.31 (n=92)
    Zone: 23 columns
    Importance: 0.014471
  Predicate: Fe <= 1.20 (n=167)
    Zone: 23 columns
    Importance: 0.014273
  Predicate: Cu > -1.74 (n=167)
    Zone: 66 columns
    Importance: 0.020876
  Predicate: Cu <= -0.64 (n=86)
    Zone: 66 columns
    Importance: 0.019464
  Predicate: Cu > -0.64 (n=128)
    Zone: 66 columns
    Importance: 0.021251
  Predicate: Cu <= 0.32 (n=125)
    Zone: 66 columns
    Importance: 0.020693
  Predicate: Cu > 0.32 (n=89)
    Zone: 66 columns
    Importance: 0.020308
  Predicate: Cu <= 1.92 (n=167)
    Zone: 66 columns
    Importance: 0.020096
  Predicate: Zn > -1.47 (n=174)
    Zone: 29 columns
    Importance: 0.024488
  Predicate: Zn <= -0.39 (n=82)
    Zone: 29 columns
    Importance: 0.022914
  Predicate: Zn > -0.39 (n=132)
    Zone: 29 columns
    Importance: 0.024530
  Predicate: Zn <= 0.56 (n=130)
    Zone: 29 columns
    Importance: 0.024096
  Predicate: Zn > 0.56 (n=84)
    Zone: 29 columns
    Importance: 0.023625
  Predicate: Zn <= 1.56 (n=171)
    Zone: 29 columns
    Importance: 0.023177
  Predicate: Bremsstrahlung > -9.06 (n=170)
    Zone: 429 columns
    Importance: 0.119050
  Predicate: Bremsstrahlung <= -1.54 (n=84)
    Zone: 429 columns
    Importance: 0.183728
  Predicate: Bremsstrahlung > -1.54 (n=130)
    Zone: 429 columns
    Importance: 0.106085
  Predicate: Bremsstrahlung <= 4.15 (n=127)
    Zone: 429 columns
    Importance: 0.151607
  Predicate: Bremsstrahlung > 4.15 (n=87)
    Zone: 429 columns
    Importance: 0.114600
  Predicate: Bremsstrahlung <= 9.64 (n=166)
    Zone: 429 columns
    Importance: 0.145160
  Predicate: Ag compton > -6.71 (n=174)
    Zone: 62 columns
    Importance: 0.030704
  Predicate: Ag compton <= -1.09 (n=83)
    Zone: 62 columns
    Importance: 0.042341
  Predicate: Ag compton > -1.09 (n=131)
    Zone: 62 columns
    Importance: 0.027992
  Predicate: Ag compton <= 2.96 (n=127)
    Zone: 62 columns
    Importance: 0.036008
  Predicate: Ag compton > 2.96 (n=87)
    Zone: 62 columns
    Importance: 0.029979
  Predicate: Ag compton <= 6.52 (n=168)
    Zone: 62 columns
    Importance: 0.033194
  Predicate: Ag ka > -11.59 (n=174)
    Zone: 45 columns
    Importance: 0.075767
  Predicate: Ag ka <= -7.06 (n=85)
    Zone: 45 columns
    Importance: 0.100687
  Predicate: Ag ka > -7.06 (n=129)
    Zone: 45 columns
    Importance: 0.073546
  Predicate: Ag ka <= 5.37 (n=126)
    Zone: 45 columns
    Importance: 0.078232
  Predicate: Ag ka > 5.37 (n=88)
    Zone: 45 columns
    Importance: 0.093052
  Predicate: Ag ka <= 20.95 (n=168)
    Zone: 45 columns
    Importance: 0.079181

[Bag_2] Processing 60 predicates...
  Predicate: Ag La > -18.52 (n=170)
    Zone: 18 columns
    Importance: 0.046330
  Predicate: Ag La <= 2.70 (n=87)
    Zone: 18 columns
    Importance: 0.221048
  Predicate: Ag La > 2.70 (n=127)
    Zone: 18 columns
    Importance: 0.026358
  Predicate: Ag La <= 7.76 (n=132)
    Zone: 18 columns
    Importance: 0.151037
  Predicate: Ag La > 7.76 (n=82)
    Zone: 18 columns
    Importance: 0.032217
  Predicate: Ag La <= 9.01 (n=175)
    Zone: 18 columns
    Importance: 0.120291
  Predicate: Ag Lb > -15.87 (n=171)
    Zone: 15 columns
    Importance: 0.032481
  Predicate: Ag Lb <= 2.36 (n=87)
    Zone: 15 columns
    Importance: 0.170842
  Predicate: Ag Lb > 2.36 (n=127)
    Zone: 15 columns
    Importance: 0.020041
  Predicate: Ag Lb <= 6.48 (n=131)
    Zone: 15 columns
    Importance: 0.117504
  Predicate: Ag Lb > 6.48 (n=83)
    Zone: 15 columns
    Importance: 0.024283
  Predicate: Ag Lb <= 8.04 (n=174)
    Zone: 15 columns
    Importance: 0.093570
  Predicate: Ca > -1.79 (n=165)
    Zone: 19 columns
    Importance: 0.011358
  Predicate: Ca <= -0.68 (n=83)
    Zone: 19 columns
    Importance: 0.011964
  Predicate: Ca > -0.68 (n=131)
    Zone: 19 columns
    Importance: 0.011101
  Predicate: Ca <= 0.46 (n=128)
    Zone: 19 columns
    Importance: 0.010941
  Predicate: Ca > 0.46 (n=86)
    Zone: 19 columns
    Importance: 0.012172
  Predicate: Ca <= 1.81 (n=173)
    Zone: 19 columns
    Importance: 0.010590
  Predicate: background > -1.23 (n=168)
    Zone: 87 columns
    Importance: 0.033172
  Predicate: background <= -0.46 (n=89)
    Zone: 87 columns
    Importance: 0.028466
  Predicate: background > -0.46 (n=125)
    Zone: 87 columns
    Importance: 0.033287
  Predicate: background <= 0.40 (n=126)
    Zone: 87 columns
    Importance: 0.031088
  Predicate: background > 0.40 (n=88)
    Zone: 87 columns
    Importance: 0.031560
  Predicate: background <= 1.29 (n=172)
    Zone: 87 columns
    Importance: 0.032369
  Predicate: Fe > -1.18 (n=169)
    Zone: 23 columns
    Importance: 0.014512
  Predicate: Fe <= -0.36 (n=87)
    Zone: 23 columns
    Importance: 0.015879
  Predicate: Fe > -0.36 (n=127)
    Zone: 23 columns
    Importance: 0.014002
  Predicate: Fe <= 0.31 (n=127)
    Zone: 23 columns
    Importance: 0.014959
  Predicate: Fe > 0.31 (n=87)
    Zone: 23 columns
    Importance: 0.014482
  Predicate: Fe <= 1.20 (n=169)
    Zone: 23 columns
    Importance: 0.014392
  Predicate: Cu > -1.74 (n=166)
    Zone: 66 columns
    Importance: 0.022331
  Predicate: Cu <= -0.64 (n=90)
    Zone: 66 columns
    Importance: 0.019981
  Predicate: Cu > -0.64 (n=124)
    Zone: 66 columns
    Importance: 0.022990
  Predicate: Cu <= 0.32 (n=129)
    Zone: 66 columns
    Importance: 0.022239
  Predicate: Cu > 0.32 (n=85)
    Zone: 66 columns
    Importance: 0.020944
  Predicate: Cu <= 1.92 (n=170)
    Zone: 66 columns
    Importance: 0.021397
  Predicate: Zn > -1.47 (n=169)
    Zone: 29 columns
    Importance: 0.024394
  Predicate: Zn <= -0.39 (n=86)
    Zone: 29 columns
    Importance: 0.022296
  Predicate: Zn > -0.39 (n=128)
    Zone: 29 columns
    Importance: 0.024821
  Predicate: Zn <= 0.56 (n=132)
    Zone: 29 columns
    Importance: 0.024759
  Predicate: Zn > 0.56 (n=82)
    Zone: 29 columns
    Importance: 0.022272
  Predicate: Zn <= 1.56 (n=169)
    Zone: 29 columns
    Importance: 0.024612
  Predicate: Bremsstrahlung > -9.06 (n=173)
    Zone: 429 columns
    Importance: 0.115294
  Predicate: Bremsstrahlung <= -1.54 (n=87)
    Zone: 429 columns
    Importance: 0.178263
  Predicate: Bremsstrahlung > -1.54 (n=127)
    Zone: 429 columns
    Importance: 0.102325
  Predicate: Bremsstrahlung <= 4.15 (n=134)
    Zone: 429 columns
    Importance: 0.150649
  Predicate: Bremsstrahlung > 4.15 (n=80)
    Zone: 429 columns
    Importance: 0.103964
  Predicate: Bremsstrahlung <= 9.64 (n=170)
    Zone: 429 columns
    Importance: 0.140745
  Predicate: Ag compton > -6.71 (n=171)
    Zone: 62 columns
    Importance: 0.029476
  Predicate: Ag compton <= -1.09 (n=84)
    Zone: 62 columns
    Importance: 0.041046
  Predicate: Ag compton > -1.09 (n=130)
    Zone: 62 columns
    Importance: 0.027430
  Predicate: Ag compton <= 2.96 (n=130)
    Zone: 62 columns
    Importance: 0.034715
  Predicate: Ag compton > 2.96 (n=84)
    Zone: 62 columns
    Importance: 0.029771
  Predicate: Ag compton <= 6.52 (n=173)
    Zone: 62 columns
    Importance: 0.032551
  Predicate: Ag ka > -11.59 (n=169)
    Zone: 45 columns
    Importance: 0.080847
  Predicate: Ag ka <= -7.06 (n=84)
    Zone: 45 columns
    Importance: 0.108678
  Predicate: Ag ka > -7.06 (n=130)
    Zone: 45 columns
    Importance: 0.080051
  Predicate: Ag ka <= 5.37 (n=125)
    Zone: 45 columns
    Importance: 0.086260
  Predicate: Ag ka > 5.37 (n=89)
    Zone: 45 columns
    Importance: 0.098349
  Predicate: Ag ka <= 20.95 (n=166)
    Zone: 45 columns
    Importance: 0.084013

[Bag_3] Processing 60 predicates...
  Predicate: Ag La > -18.52 (n=174)
    Zone: 18 columns
    Importance: 0.046753
  Predicate: Ag La <= 2.70 (n=84)
    Zone: 18 columns
    Importance: 0.196643
  Predicate: Ag La > 2.70 (n=130)
    Zone: 18 columns
    Importance: 0.025531
  Predicate: Ag La <= 7.76 (n=128)
    Zone: 18 columns
    Importance: 0.134628
  Predicate: Ag La > 7.76 (n=86)
    Zone: 18 columns
    Importance: 0.030286
  Predicate: Ag La <= 9.01 (n=169)
    Zone: 18 columns
    Importance: 0.108224
  Predicate: Ag Lb > -15.87 (n=173)
    Zone: 15 columns
    Importance: 0.031244
  Predicate: Ag Lb <= 2.36 (n=84)
    Zone: 15 columns
    Importance: 0.147580
  Predicate: Ag Lb > 2.36 (n=130)
    Zone: 15 columns
    Importance: 0.020380
  Predicate: Ag Lb <= 6.48 (n=127)
    Zone: 15 columns
    Importance: 0.101919
  Predicate: Ag Lb > 6.48 (n=87)
    Zone: 15 columns
    Importance: 0.024165
  Predicate: Ag Lb <= 8.04 (n=169)
    Zone: 15 columns
    Importance: 0.081280
  Predicate: Ca > -1.79 (n=171)
    Zone: 19 columns
    Importance: 0.010625
  Predicate: Ca <= -0.68 (n=79)
    Zone: 19 columns
    Importance: 0.012518
  Predicate: Ca > -0.68 (n=135)
    Zone: 19 columns
    Importance: 0.010126
  Predicate: Ca <= 0.46 (n=126)
    Zone: 19 columns
    Importance: 0.010748
  Predicate: Ca > 0.46 (n=88)
    Zone: 19 columns
    Importance: 0.011382
  Predicate: Ca <= 1.81 (n=170)
    Zone: 19 columns
    Importance: 0.010282
  Predicate: background > -1.23 (n=169)
    Zone: 87 columns
    Importance: 0.030963
  Predicate: background <= -0.46 (n=89)
    Zone: 87 columns
    Importance: 0.026022
  Predicate: background > -0.46 (n=125)
    Zone: 87 columns
    Importance: 0.030645
  Predicate: background <= 0.40 (n=133)
    Zone: 87 columns
    Importance: 0.028431
  Predicate: background > 0.40 (n=81)
    Zone: 87 columns
    Importance: 0.029201
  Predicate: background <= 1.29 (n=174)
    Zone: 87 columns
    Importance: 0.030022
  Predicate: Fe > -1.18 (n=174)
    Zone: 23 columns
    Importance: 0.013542
  Predicate: Fe <= -0.36 (n=76)
    Zone: 23 columns
    Importance: 0.014076
  Predicate: Fe > -0.36 (n=138)
    Zone: 23 columns
    Importance: 0.013513
  Predicate: Fe <= 0.31 (n=124)
    Zone: 23 columns
    Importance: 0.012905
  Predicate: Fe > 0.31 (n=90)
    Zone: 23 columns
    Importance: 0.014826
  Predicate: Fe <= 1.20 (n=170)
    Zone: 23 columns
    Importance: 0.012702
  Predicate: Cu > -1.74 (n=173)
    Zone: 66 columns
    Importance: 0.023567
  Predicate: Cu <= -0.64 (n=84)
    Zone: 66 columns
    Importance: 0.022375
  Predicate: Cu > -0.64 (n=130)
    Zone: 66 columns
    Importance: 0.023882
  Predicate: Cu <= 0.32 (n=125)
    Zone: 66 columns
    Importance: 0.023418
  Predicate: Cu > 0.32 (n=89)
    Zone: 66 columns
    Importance: 0.023111
  Predicate: Cu <= 1.92 (n=171)
    Zone: 66 columns
    Importance: 0.022113
  Predicate: Zn > -1.47 (n=170)
    Zone: 29 columns
    Importance: 0.023587
  Predicate: Zn <= -0.39 (n=89)
    Zone: 29 columns
    Importance: 0.021808
  Predicate: Zn > -0.39 (n=125)
    Zone: 29 columns
    Importance: 0.024466
  Predicate: Zn <= 0.56 (n=130)
    Zone: 29 columns
    Importance: 0.023842
  Predicate: Zn > 0.56 (n=84)
    Zone: 29 columns
    Importance: 0.022614
  Predicate: Zn <= 1.56 (n=173)
    Zone: 29 columns
    Importance: 0.022944
  Predicate: Bremsstrahlung > -9.06 (n=167)
    Zone: 429 columns
    Importance: 0.123802
  Predicate: Bremsstrahlung <= -1.54 (n=84)
    Zone: 429 columns
    Importance: 0.184069
  Predicate: Bremsstrahlung > -1.54 (n=130)
    Zone: 429 columns
    Importance: 0.113473
  Predicate: Bremsstrahlung <= 4.15 (n=129)
    Zone: 429 columns
    Importance: 0.156525
  Predicate: Bremsstrahlung > 4.15 (n=85)
    Zone: 429 columns
    Importance: 0.117901
  Predicate: Bremsstrahlung <= 9.64 (n=173)
    Zone: 429 columns
    Importance: 0.149717
  Predicate: Ag compton > -6.71 (n=170)
    Zone: 62 columns
    Importance: 0.029698
  Predicate: Ag compton <= -1.09 (n=89)
    Zone: 62 columns
    Importance: 0.040559
  Predicate: Ag compton > -1.09 (n=125)
    Zone: 62 columns
    Importance: 0.027530
  Predicate: Ag compton <= 2.96 (n=132)
    Zone: 62 columns
    Importance: 0.034028
  Predicate: Ag compton > 2.96 (n=82)
    Zone: 62 columns
    Importance: 0.031211
  Predicate: Ag compton <= 6.52 (n=172)
    Zone: 62 columns
    Importance: 0.032415
  Predicate: Ag ka > -11.59 (n=168)
    Zone: 45 columns
    Importance: 0.079556
  Predicate: Ag ka <= -7.06 (n=91)
    Zone: 45 columns
    Importance: 0.099685
  Predicate: Ag ka > -7.06 (n=123)
    Zone: 45 columns
    Importance: 0.079991
  Predicate: Ag ka <= 5.37 (n=131)
    Zone: 45 columns
    Importance: 0.079850
  Predicate: Ag ka > 5.37 (n=83)
    Zone: 45 columns
    Importance: 0.101805
  Predicate: Ag ka <= 20.95 (n=173)
    Zone: 45 columns
    Importance: 0.079768

[Bag_4] Processing 60 predicates...
  Predicate: Ag La > -18.52 (n=172)
    Zone: 18 columns
    Importance: 0.047118
  Predicate: Ag La <= 2.70 (n=86)
    Zone: 18 columns
    Importance: 0.213250
  Predicate: Ag La > 2.70 (n=128)
    Zone: 18 columns
    Importance: 0.026544
  Predicate: Ag La <= 7.76 (n=128)
    Zone: 18 columns
    Importance: 0.148749
  Predicate: Ag La > 7.76 (n=86)
    Zone: 18 columns
    Importance: 0.031364
  Predicate: Ag La <= 9.01 (n=172)
    Zone: 18 columns
    Importance: 0.117031
  Predicate: Ag Lb > -15.87 (n=168)
    Zone: 15 columns
    Importance: 0.031364
  Predicate: Ag Lb <= 2.36 (n=88)
    Zone: 15 columns
    Importance: 0.159713
  Predicate: Ag Lb > 2.36 (n=126)
    Zone: 15 columns
    Importance: 0.022378
  Predicate: Ag Lb <= 6.48 (n=128)
    Zone: 15 columns
    Importance: 0.113859
  Predicate: Ag Lb > 6.48 (n=86)
    Zone: 15 columns
    Importance: 0.026748
  Predicate: Ag Lb <= 8.04 (n=167)
    Zone: 15 columns
    Importance: 0.092617
  Predicate: Ca > -1.79 (n=165)
    Zone: 19 columns
    Importance: 0.010965
  Predicate: Ca <= -0.68 (n=90)
    Zone: 19 columns
    Importance: 0.010951
  Predicate: Ca > -0.68 (n=124)
    Zone: 19 columns
    Importance: 0.011222
  Predicate: Ca <= 0.46 (n=129)
    Zone: 19 columns
    Importance: 0.010509
  Predicate: Ca > 0.46 (n=85)
    Zone: 19 columns
    Importance: 0.012017
  Predicate: Ca <= 1.81 (n=171)
    Zone: 19 columns
    Importance: 0.010275
  Predicate: background > -1.23 (n=170)
    Zone: 87 columns
    Importance: 0.031317
  Predicate: background <= -0.46 (n=85)
    Zone: 87 columns
    Importance: 0.025256
  Predicate: background > -0.46 (n=129)
    Zone: 87 columns
    Importance: 0.032445
  Predicate: background <= 0.40 (n=127)
    Zone: 87 columns
    Importance: 0.029037
  Predicate: background > 0.40 (n=87)
    Zone: 87 columns
    Importance: 0.030397
  Predicate: background <= 1.29 (n=171)
    Zone: 87 columns
    Importance: 0.030077
  Predicate: Fe > -1.18 (n=173)
    Zone: 23 columns
    Importance: 0.013651
  Predicate: Fe <= -0.36 (n=82)
    Zone: 23 columns
    Importance: 0.015385
  Predicate: Fe > -0.36 (n=132)
    Zone: 23 columns
    Importance: 0.013628
  Predicate: Fe <= 0.31 (n=128)
    Zone: 23 columns
    Importance: 0.013771
  Predicate: Fe > 0.31 (n=86)
    Zone: 23 columns
    Importance: 0.015090
  Predicate: Fe <= 1.20 (n=169)
    Zone: 23 columns
    Importance: 0.013554
  Predicate: Cu > -1.74 (n=169)
    Zone: 66 columns
    Importance: 0.023691
  Predicate: Cu <= -0.64 (n=89)
    Zone: 66 columns
    Importance: 0.019959
  Predicate: Cu > -0.64 (n=125)
    Zone: 66 columns
    Importance: 0.025121
  Predicate: Cu <= 0.32 (n=128)
    Zone: 66 columns
    Importance: 0.022340
  Predicate: Cu > 0.32 (n=86)
    Zone: 66 columns
    Importance: 0.023917
  Predicate: Cu <= 1.92 (n=170)
    Zone: 66 columns
    Importance: 0.021708
  Predicate: Zn > -1.47 (n=170)
    Zone: 29 columns
    Importance: 0.024548
  Predicate: Zn <= -0.39 (n=86)
    Zone: 29 columns
    Importance: 0.024297
  Predicate: Zn > -0.39 (n=128)
    Zone: 29 columns
    Importance: 0.024072
  Predicate: Zn <= 0.56 (n=132)
    Zone: 29 columns
    Importance: 0.024254
  Predicate: Zn > 0.56 (n=82)
    Zone: 29 columns
    Importance: 0.024017
  Predicate: Zn <= 1.56 (n=172)
    Zone: 29 columns
    Importance: 0.023779
  Predicate: Bremsstrahlung > -9.06 (n=173)
    Zone: 429 columns
    Importance: 0.114572
  Predicate: Bremsstrahlung <= -1.54 (n=84)
    Zone: 429 columns
    Importance: 0.165699
  Predicate: Bremsstrahlung > -1.54 (n=130)
    Zone: 429 columns
    Importance: 0.104798
  Predicate: Bremsstrahlung <= 4.15 (n=130)
    Zone: 429 columns
    Importance: 0.138645
  Predicate: Bremsstrahlung > 4.15 (n=84)
    Zone: 429 columns
    Importance: 0.113317
  Predicate: Bremsstrahlung <= 9.64 (n=174)
    Zone: 429 columns
    Importance: 0.135124
  Predicate: Ag compton > -6.71 (n=171)
    Zone: 62 columns
    Importance: 0.029852

,Predicate_pert_Seed_0,Predicate_pert_Seed_1,Predicate_pert_Seed_2,Predicate_pert_Seed_3
0,Ag La <= 2.70,Ag La <= 2.70,Ag La <= 2.70,Ag La <= 2.70
1,Bremsstrahlung <= -1.54,Bremsstrahlung <= -1.54,Bremsstrahlung <= -1.54,Ag La <= 7.76
2,Ag Lb <= 2.36,Ag Lb <= 2.36,Ag Lb <= 2.36,Bremsstrahlung <= -1.54
3,Bremsstrahlung <= 4.15,Ag La <= 7.76,Bremsstrahlung <= 4.15,Bremsstrahlung <= 4.15
4,Ag La <= 9.01,Ag La <= 9.01,Ag La <= 7.76,Ag Lb <= 2.36
...,...,...,...,...
57,Ca <= -0.68,Ca <= -0.68,Ca > 0.46,Ca > -1.79
58,Ca > -1.79,Ca <= 1.81,Ca > -1.79,Ca <= 0.46
59,Ca <= 1.81,Ca > -0.68,Ca <= 1.81,Ca <= 1.81
60,Class_A,Class_A,Class_A,Class_A
61,Class_B,Class_B,Class_B,Class_B

In [12]:
all_results_pert[0]['pert_results_dict']['Bag_1']

                  Predicate  Perturbation
0             Ag La <= 2.70      0.218193
1   Bremsstrahlung <= -1.54      0.183728
2             Ag Lb <= 2.36      0.165061
3    Bremsstrahlung <= 4.15      0.151607
4    Bremsstrahlung <= 9.64      0.145160
5             Ag La <= 7.76      0.141935
6    Bremsstrahlung > -9.06      0.119050
7     Bremsstrahlung > 4.15      0.114600
8             Ag La <= 9.01      0.113973
9             Ag Lb <= 6.48      0.109012
10   Bremsstrahlung > -1.54      0.106085
11           Ag ka <= -7.06      0.100687
12             Ag ka > 5.37      0.093052
13            Ag Lb <= 8.04      0.087615
14           Ag ka <= 20.95      0.079181
15            Ag ka <= 5.37      0.078232
16           Ag ka > -11.59      0.075767
17            Ag ka > -7.06      0.073546
18           Ag La > -18.52      0.046839
19      Ag compton <= -1.09      0.042341
20       Ag compton <= 2.96      0.036008
21       Ag compton <= 6.52      0.033194
22       background > -0.46      0.031033
23       background <= 1.29      0.031007
24       Ag compton > -6.71      0.030704
25       background > -1.23      0.030481
26        Ag compton > 2.96      0.029979
27           Ag Lb > -15.87      0.029933
28        background > 0.40      0.029146
29       background <= 0.40      0.029050
30             Ag La > 7.76      0.028800
31       Ag compton > -1.09      0.027992
32      background <= -0.46      0.026081
33               Zn > -0.39      0.024530
34               Zn > -1.47      0.024488
35               Zn <= 0.56      0.024096
36             Ag La > 2.70      0.024039
37                Zn > 0.56      0.023625
38               Zn <= 1.56      0.023177
39              Zn <= -0.39      0.022914
40             Ag Lb > 6.48      0.022649
41               Cu > -0.64      0.021251
42               Cu > -1.74      0.020876
43               Cu <= 0.32      0.020693
44                Cu > 0.32      0.020308
45               Cu <= 1.92      0.020096
46              Cu <= -0.64      0.019464
47             Ag Lb > 2.36      0.018581
48              Fe <= -0.36      0.016958
49               Fe <= 0.31      0.014997
50                Fe > 0.31      0.014471
51               Fe <= 1.20      0.014273
52               Fe > -1.18      0.014033
53               Fe > -0.36      0.013439
54                Ca > 0.46      0.012075
55               Ca > -0.68      0.011332
56               Ca > -1.79      0.011000
57              Ca <= -0.68      0.010511
58               Ca <= 0.46      0.010288
59               Ca <= 1.81      0.009915

In [13]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_pert_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_pert = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_pert = lrc_summed_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_pert = lrc_summed_df_pert.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_pert = lrc_summed_unique_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_pert

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Ag La <= 2.70,6.043251,Ag La,2.70,<=
1,Bremsstrahlung <= -1.54,3.741575,Bremsstrahlung,-1.54,<=
2,Ag Lb <= 2.36,3.522829,Ag Lb,2.36,<=
3,Ag ka > 5.37,2.365298,Ag ka,5.37,>
4,Ag compton <= -1.09,0.553964,Ag compton,-1.09,<=
5,background <= 1.29,0.238849,background,1.29,<=
6,Zn <= 0.56,0.121458,Zn,0.56,<=
7,Cu > -1.74,0.107682,Cu,-1.74,>
8,Fe <= -0.36,0.021631,Fe,-0.36,<=
9,Ca > 0.46,0.013500,Ca,0.46,>
10,Class_B,0.000000,None,None,None

In [14]:
# Aplicar o mapeamento
lrc_summed_df_pert_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_pert,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_pert_natural

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,Ag La <= 2.70,6.043251,Ag La,2.70,<=,34.935039,86.0,0.021418,Ag La <= 34.935039
1,Bremsstrahlung <= -1.54,3.741575,Bremsstrahlung,-1.54,<=,-72.079168,60.0,0.037184,Bremsstrahlung <= -72.079168
2,Ag Lb <= 2.36,3.522829,Ag Lb,2.36,<=,30.578162,0.0,0.008013,Ag Lb <= 30.578162
3,Ag La <= 7.76,3.153507,Ag La,7.76,<=,105.814886,78.0,0.002963,Ag La <= 105.814886
4,Bremsstrahlung <= 4.15,3.063384,Bremsstrahlung,4.15,<=,83.677742,106.0,0.010264,Bremsstrahlung <= 83.677742
...,...,...,...,...,...,...,...,...,...
57,Ca > -1.79,0.009745,Ca,-1.79,>,-9.483856,153.0,0.012409,Ca > -9.483856
58,Ca > -0.68,0.008865,Ca,-0.68,>,-8.742470,9.0,0.004755,Ca > -8.742470
59,Ca <= 1.81,0.007141,Ca,1.81,<=,-2.575534,222.0,0.044016,Ca <= -2.575534
60,Class_B,0.000000,None,None,None,NaN,NaN,NaN,None
61,Class_A,0.000000,None,None,None,NaN,NaN,NaN,None

In [15]:
import plotly.graph_objects as go

n = 0
zone_name = lrc_summed_df_pert_natural.iloc[n]['Zone'] # o n indica a linha do dataframe lrc_summed_df_pert_natural que queremos acessar para pegar o nome da zona espectral (coluna 'Zone')
threshold_score = float(lrc_summed_df_pert_natural.iloc[n]['Threshold_Natural']) # o iloc acessa a linha n e a coluna 'Threshold_Natural' para pegar o valor do threshold já mapeado para o espaço natural (não pré-processado)

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
#print(f"  - Range de energias: {threshold_spectrum.index[n]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_pert_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona 'Ag La':
  - Dimensão: 18 variáveis espectrais
  - Variância explicada pela PC1: 91.39%

In [16]:
# Permutation importance baseado em mudança nas probabilidades previstas (predict_proba)
# Medimos a média da diferença absoluta entre as probabilidades originais e as probabilidades
# obtidas após permutar cada variável. Isso fornece uma métrica contínua de importância.
n_repeats = 10
rng = np.random.RandomState(42)
# Probabilidades base (classe 'B' mapeada para 1)
baseline_proba = mlp_model[3].predict_proba(Xcalclass_prep)[:, 1]
importance_list = []
X_arr = Xcalclass_prep.copy()
for col in Xcalclass_prep.columns:
    diffs = []
    for _ in range(n_repeats):
        X_perm = X_arr.copy()
        X_perm[col] = rng.permutation(X_perm[col].values)
        perm_proba = mlp_model[3].predict_proba(X_perm)[:, 1]
        diffs.append(np.mean(np.abs(baseline_proba - perm_proba)))
    importance_list.append(np.mean(diffs))

permutation_df = pd.DataFrame({
    'energy': Xcalclass_prep.columns,
    'Permutation_importance_proba': importance_list
})
permutation_df.sort_values(by='Permutation_importance_proba', ascending=False, inplace=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in permutation_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
permutation_df['Zone'] = permutation_df['energy'].map(energy_to_zone_vip)
permutation_unique_df = permutation_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
permutation_unique_df = permutation_unique_df.sort_values(by='Permutation_importance_proba', ascending=False)
permutation_unique_df

  energy  Permutation_importance_proba            Zone
0  22.31                      0.032329           Ag ka
1   3.02                      0.022214           Ag La
2   3.17                      0.021363           Ag Lb
3  20.70                      0.011740      Ag compton
4   8.73                      0.010901              Zn
5  19.50                      0.008636  Bremsstrahlung
6   6.86                      0.006604              Cu
7   5.89                      0.006122      background
8   6.40                      0.005054              Fe
9   3.74                      0.004203              Ca

In [17]:
import numpy as np

max_len = max(
    len(shap_unique_df['Zone']),
    len(permutation_unique_df['Zone']),
    len(lrc_summed_unique_df_pert['Zone']),
    len(lrc_summed_unique_df_cov['Zone'])
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'Shap': pad_list(shap_unique_df['Zone'], max_len),
    'Permutation' : pad_list(permutation_unique_df['Zone'], max_len),
    'LRC_perturbation' : pad_list(lrc_summed_unique_df_pert['Zone'], max_len),
    'LRC_covariance' : pad_list(lrc_summed_unique_df_cov['Zone'], max_len),
})

features_importance.to_csv('feature_importance.csv', index=False, sep=';')
features_importance

              Shap     Permutation LRC_perturbation  LRC_covariance
0            Ag Lb           Ag ka            Ag La           Ag La
1            Ag La           Ag La   Bremsstrahlung           Ag Lb
2            Ag ka           Ag Lb            Ag Lb           Ag ka
3               Zn      Ag compton            Ag ka  Bremsstrahlung
4       Ag compton              Zn       Ag compton      Ag compton
5   Bremsstrahlung  Bremsstrahlung       background              Cu
6       background              Cu               Zn              Ca
7               Cu      background               Cu      background
8               Fe              Fe               Fe              Fe
9               Ca              Ca               Ca              Zn
10            None            None             None            None

In [18]:
import rbo
rbo_comparison = pd.DataFrame(columns=['Method_1', 'Method_2', 'RBO_Score'])
methods = features_importance.columns.tolist()
for i in range(len(methods)):
    for j in range(i + 1, len(methods)):
        method_1 = methods[i]
        method_2 = methods[j]
        # Remove None values from the lists
        list_1 = [x for x in features_importance[method_1].tolist() if x is not None]
        list_2 = [x for x in features_importance[method_2].tolist() if x is not None]
        # Truncate both lists to the same length (minimum of both)
        min_len = min(len(list_1), len(list_2))
        list_1_trunc = list_1[:min_len]
        list_2_trunc = list_2[:min_len]
        rbo_score = rbo.RankingSimilarity(list_1_trunc, list_2_trunc).rbo(p=0.7, k=10)
        rbo_comparison = pd.concat([rbo_comparison, pd.DataFrame({
            'Method_1': [method_1],
            'Method_2': [method_2],
            'RBO_Score': [rbo_score]
        })], ignore_index=True)
rbo_comparison.sort_values(by='RBO_Score', ascending=False, inplace=True)
rbo_comparison.to_csv('rbo_rank.csv', index=False, sep=';')
rbo_comparison

C:\Users\Usuario\AppData\Local\Temp\ipykernel_16960\3097109587.py:16: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

           Method_1          Method_2  RBO_Score
5  LRC_perturbation    LRC_covariance   0.794255
2              Shap    LRC_covariance   0.608124
0              Shap       Permutation   0.535985
4       Permutation    LRC_covariance   0.508166
1              Shap  LRC_perturbation   0.469218
3       Permutation  LRC_perturbation   0.464176

In [19]:
lrc_summed_df_cov_natural.to_csv('lrc_cov_natural.csv', index=False, sep=';')
lrc_summed_df_pert_natural.to_csv('lrc_pert_natural.csv', index=False, sep=';')