In [1]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import kennard_stone as ks
pd.options.plotting.backend = 'plotly'  # setting plotly as the backend for pandas plotting

# Add parent directory to sys.path so local module 'synthetic' can be imported
import sys
from pathlib import Path # for path manipulations
# Move three levels up from current working directory to reach workspace root
workspace_root = Path.cwd().parent.parent.parent.resolve() 
smx_dir = workspace_root / 'smx'  # Path to smx folder
if str(smx_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(smx_dir)) # insert at the start of sys.path to prioritize local modules

# Loading a soil spectral dataset based on X-ray fluorescence (XRF)
data_complete = pd.read_csv(f'{workspace_root}/real_datasets/xrf/soil.csv', sep=';') # local copy of Toledo 2022 dataset (os ... indica para omitir o caminho longo)
data = data_complete.loc[:, '1.32':'13.1']

# Split dataset by class and create calibration/prediction sets using Kennard-Stone (as in original pipeline)
data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.loc[:, '1.32':'13.1'], test_size=0.30)  # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.loc[:, '1.32':'13.1'], test_size=0.30)  # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)

Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True)  # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0])  # target for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0])  # target for prediction set

# preprocessings
import preprocessings as prepr  # preprocessing methods for XRF data

Xcalclass_prep, mean_calclass, mean_calclass_poisson  = prepr.poisson(Xcalclass, mc=True)
Xpredclass_prep = ((Xpredclass/np.sqrt(mean_calclass)) - mean_calclass_poisson)

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-26 15:03:15,359 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-26 15:03:15,374 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-26 15:03:15,409 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-26 15:03:15,422 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [2]:
from modeling import svm_optimized

svm_model = svm_optimized(Xcalclass_prep, ycalclass, Xpredclass_prep, ypredclass, aim='classification', kernel='rbf')
svm_model[0]

,Model,Accuracy Cal,Sensitivity Cal,Specificity Cal,CM Cal,Accuracy Pred,Sensitivity Pred,Specificity Pred,CM Pred
0,SVC,0.925676,0.943662,0.909091,"[[70, 7], [4, 67]]",0.875,0.967742,0.787879,"[[26, 7], [1, 30]]"

## Definição das Zonas Espectrais

In [3]:
# establishing spectral cuts based on expert knowledge of XRF spectra
spectral_cuts = [
('Al', 1.33, 1.63),
('Si', 1.63, 1.86),
('P', 1.86, 2.19),
('S', 2.19, 2.55),
('Rh L + Ar', 2.55, 3.21),
('K', 3.21, 3.53),
('Ca ka', 3.53, 3.84),
('Ca kb', 3.84, 4.37),
('Ti ka', 4.37, 4.75),
('Ti kb', 4.75, 5.12),
('Cr', 5.12, 5.77),
('Mn', 5.77, 6.13),
('Fe ka', 6.13, 6.80),
('Fe kb', 6.80, 7.30),
('background1', 7.30, 7.91),
('Cu', 7.91, 8.20),
('background2', 8.20, 10.69),
('Fe ka + Ti ka', 10.69, 11.14),
('background3', 11.14, 12.55),
('sum Fe' , 12.55, 13.1)
]

## Pvector and SHAP

In [4]:
X_sv = svm_model[3].support_vectors_            # shape (n_SV, n_features)
alpha_dual = svm_model[3].dual_coef_.ravel()    # shape (n_SV,)

# Calculando os coeficientes p usando os vetores de suporte e os multiplicadores de Lagrange
pvetor = pd.DataFrame({'energia' : Xcalclass.columns,
                       'importance': (X_sv.T) @ alpha_dual})
pvetor['importance'] = np.abs(pvetor['importance'])
pvector_df = pd.DataFrame({
    'energy': pvetor['energia'],
    'Pvector': pvetor['importance'].values
})
pvector_df = pvector_df.sort_values(by='Pvector', ascending=False).reset_index(drop=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in pvector_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
pvector_df['Zone'] = pvector_df['energy'].map(energy_to_zone_vip)
pvector_unique_df = pvector_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
pvector_unique_df

   energy    Pvector           Zone
0     3.7  23.449350          Ca ka
1     6.4  10.480949          Fe ka
2       4   5.267717          Ca kb
3    7.04   4.266787          Fe kb
4    1.74   4.020145             Si
5    4.58   2.573184          Ti ka
6    5.86   2.320523             Mn
7    12.8   2.051473         sum Fe
8    1.46   1.852539             Al
9    5.22   1.845806             Cr
10   12.4   1.711950    background3
11   2.02   1.658364              P
12   9.84   1.390433    background2
13   7.54   1.355642    background1
14   2.32   1.341812              S
15   4.88   1.292012          Ti kb
16   8.04   1.281862             Cu
17    3.2   1.255061      Rh L + Ar
18  10.96   1.092165  Fe ka + Ti ka
19   3.28   0.897477              K
20   1.32   0.595286            NaN

In [5]:
shap_global_importance = pd.read_csv('shap_soil.csv', sep=';') # loading previously saved shap_unique_df
# vamos gerar uma nova coluna em shap_global_importance com o nome da zona espectral correspondente de acordo com a lista spectral_cuts
energy_to_zone_shap = {}
for zone_name, start, end in spectral_cuts:
    for i in shap_global_importance['energy']:
        i_float = float(i)
        if start <= i_float <= end:
            energy_to_zone_shap[i] = zone_name
shap_global_importance['Zone'] = shap_global_importance['energy'].map(energy_to_zone_shap)

# agora vamos filtrar shap_global_importance para manter apenas as zonas espectrais únicas com maior SHAP score
shap_unique_df = shap_global_importance.sort_values(by='Mean_Abs_SHAP', ascending=False).reset_index(drop=True)
shap_unique_df = shap_unique_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
shap_unique_df

    energy  Mean_Abs_SHAP           Zone
0     3.70       0.049862          Ca ka
1     6.44       0.012383          Fe ka
2     4.52       0.005719          Ti ka
3     1.74       0.002200             Si
4     5.92       0.001246             Mn
5     5.60       0.000197             Cr
6    10.24       0.000180    background2
7     4.00       0.000147          Ca kb
8     7.12       0.000120          Fe kb
9     4.96       0.000013          Ti kb
10    2.06       0.000009              P
11    7.84       0.000007    background1
12    8.18       0.000000             Cu
13    1.32       0.000000            NaN
14   12.38       0.000000    background3
15   12.80       0.000000         sum Fe
16   10.70       0.000000  Fe ka + Ti ka
17    3.14       0.000000      Rh L + Ar
18    3.42       0.000000              K
19    1.62       0.000000             Al
20    2.54       0.000000              S

## Funções de Agregação por PCA

Aqui implementamos as funções para agregar zonas espectrais usando PCA com 1 componente principal.

In [6]:
import explaining as exp

# Extração das zonas espectrais
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_scores_df, pca_info_dict = exp.aggregate_spectral_zones_pca(spectral_zones_class) # apca aggregation
print(f"\nScores DataFrame shape: {zone_scores_df.shape}")

Zone 'Al': VE = 79.34%, dim = 15 variables
Zone 'Si': VE = 91.83%, dim = 12 variables
Zone 'P': VE = 62.02%, dim = 17 variables
Zone 'S': VE = 36.84%, dim = 18 variables
Zone 'Rh L + Ar': VE = 42.17%, dim = 33 variables
Zone 'K': VE = 83.48%, dim = 16 variables
Zone 'Ca ka': VE = 99.02%, dim = 16 variables
Zone 'Ca kb': VE = 74.05%, dim = 27 variables
Zone 'Ti ka': VE = 89.48%, dim = 19 variables
Zone 'Ti kb': VE = 82.21%, dim = 19 variables
Zone 'Cr': VE = 53.41%, dim = 33 variables
Zone 'Mn': VE = 91.12%, dim = 18 variables
Zone 'Fe ka': VE = 56.98%, dim = 34 variables
Zone 'Fe kb': VE = 55.98%, dim = 26 variables
Zone 'background1': VE = 32.70%, dim = 31 variables
Zone 'Cu': VE = 53.86%, dim = 15 variables
Zone 'background2': VE = 26.43%, dim = 125 variables
Zone 'Fe ka + Ti ka': VE = 34.74%, dim = 23 variables
Zone 'background3': VE = 18.96%, dim = 71 variables
Zone 'sum Fe': VE = 55.82%, dim = 28 variables

Scores DataFrame shape: (148, 20)

In [7]:
y_pred = svm_model[4]['SVC'].values # using the continuous predictions from SVM, extracting as 1D array
predicates_quantiles = exp.predicates_by_quantiles(zone_scores_df, [0.2, 0.4, 0.6, 0.8])
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_scores_df,
    y_predicted_numeric=y_pred
)

In [8]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_cov = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE

y_pred = pd.Series(svm_model[4]['SVC'].values) # using the continuous predictions from SVM, extracting as 1D array

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist
    
    # Calcular MI
    cov_results_dict_seed = exp.calculate_predicate_metrics(
        bags_result=bags_result_seed,
        metric='covariance', # covariance ou mutual_information
        threshold=0.01, # threshold para cortar predicados irrelevantes
        n_neighbors=5
    )
    
    # Salvar no dicionário principal
    all_results_cov[seed] = {
        'bags_result': bags_result_seed,
        'cov_results_dict': cov_results_dict_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graph(
        bags_result=all_results_cov[seed]['bags_result'],
        predicate_ranking_dict=all_results_cov[seed]['cov_results_dict'],
        metric_column='Covariance',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )
    # Armazenar grafo
    graphs_by_seed[seed] = DG

# Calcular LRC usando a função pronta do explaining.py
lrc_cov_by_seed = {}
for seed in random_seeds:
    DG = graphs_by_seed[seed]
    lrc_cov_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_cov_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_cov_by_seed[seed] = lrc_cov_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_cov_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_cov_df_seed = lrc_cov_by_seed[seed].rename(columns={'Node': f'Predicate_Cov_Seed_{seed}'})
    lrc_cov_all_seeds_df = pd.concat([lrc_cov_all_seeds_df, lrc_cov_df_seed[[f'Predicate_Cov_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_cov_unique_by_seed = {}
for seed, lrc_df in lrc_cov_by_seed.items():
    lrc_cov_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_cov_unique_df = lrc_cov_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_cov_unique_by_seed[seed] = lrc_cov_unique_df

lrc_cov_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Samples: Yes | Predicates: No (All) | Valid: 123 | Discarded: 37
Bag_2 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_3 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_4 | Samples: Yes | Predicates: No (All) | Valid: 122 | Discarded: 38
Bag_5 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_6 | Samples: Yes | Predicates: No (All) | Valid: 121 | Discarded: 39
Bag_7 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_8 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_9 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_10 | Samples: Yes | Predicates: No (All) | Valid: 121 | Discarded: 39
Computing Covariance for Predicates
Metric: covariance
Threshold: 0.01

======================================================================
Processando semente: 1
======================================================================

Bag_1 | Samples: Yes | Predicates: No (All) | Valid: 121 | Discarded: 39
Bag_2 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_3 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_4 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_5 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_6 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_7 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_8 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_9 | Samples: Yes | Predicates: No (All) | Valid: 121 | Discarded: 39
Bag_10 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Computing Covariance for Predicates
Metric: covariance
Threshold: 0.01

======================================================================
Processando semente: 2
======================================================================

Bag_1 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_2 | Samples: Yes | Predicates: No (All) | Valid: 121 | Discarded: 39
Bag_3 | Samples: Yes | Predicates: No (All) | Valid: 121 | Discarded: 39
Bag_4 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_5 | Samples: Yes | Predicates: No (All) | Valid: 123 | Discarded: 37
Bag_6 | Samples: Yes | Predicates: No (All) | Valid: 121 | Discarded: 39
Bag_7 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_8 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_9 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_10 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Computing Covariance for Predicates
Metric: covariance
Threshold: 0.01

======================================================================
Processando semente: 3
======================================================================

Bag_1 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_2 | Samples: Yes | Predicates: No (All) | Valid: 121 | Discarded: 39
Bag_3 | Samples: Yes | Predicates: No (All) | Valid: 122 | Discarded: 38
Bag_4 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_5 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_6 | Samples: Yes | Predicates: No (All) | Valid: 121 | Discarded: 39
Bag_7 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_8 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_9 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_10 | Samples: Yes | Predicates: No (All) | Valid: 121 | Discarded: 39
Computing Covariance for Predicates
Metric: covariance
Threshold: 0.01

======================================================================
Processando Grafo - Semente: 0
======================================================================


Total bidirectional pairs found: 75
Removed: Fe ka > 0.86 -> Ca ka > -1.02 (0.4187) | Kept: Ca ka > -1.02 -> Fe ka > 0.86 (1.8515)
Removed: Fe ka > 0.86 -> Ca ka <= 1.21 (0.3474) | Kept: Ca ka <= 1.21 -> Fe ka > 0.86 (0.5698)
Removed: Ti ka > 0.93 -> Fe ka > 0.86 (0.1940) | Kept: Fe ka > 0.86 -> Ti ka > 0.93 (0.6751)
Removed: Ca ka <= 1.21 -> Fe ka > -0.43 (0.2833) | Kept: Fe ka > -0.43 -> Ca ka <= 1.21 (0.6421)
Removed: Fe ka > -0.43 -> Ti ka > 0.93 (0.1377) | Kept: Ti ka > 0.93 -> Fe ka > -0.43 (1.1530)
Removed: Fe ka > -2.66 -> Ti ka > 0.93 (0.1455) | Kept: Ti ka > 0.93 -> Fe ka > -2.66 (0.4324)
Removed: Fe ka > -0.43 -> Ti ka > -1.78 (0.1408) | Kept: Ti ka > -1.78 -> Fe ka > -0.43 (0.1653)
Removed: Fe ka > -2.66 -> Fe ka > -0.43 (0.0826) | Kept: Fe ka > -0.43 -> Fe ka > -2.66 (0.2522)
Removed: Fe ka > -2.66 -> Ti ka > -1.78 (0.2366) | Kept: Ti ka > -1.78 -> Fe ka > -2.66 (0.3273)
Removed: Ca kb > -0.37 -> Ti ka > -1.78 (0.0918) | Kept: Ti ka > -1.78 -> Ca kb > -0.37 (0.1245)
Removed: Mn > -0.65 -> Ti ka > -1.78 (0.1319) | Kept: Ti ka > -1.78 -> Mn > -0.65 (0.1604)
Removed: Ti ka > -1.78 -> Ti ka > -0.57 (0.2876) | Kept: Ti ka > -0.57 -> Ti ka > -1.78 (0.7963)
Removed: Mn > -0.65 -> Ti ka > -0.57 (0.2905) | Kept: Ti ka > -0.57 -> Mn > -0.65 (0.5719)
Removed: Ti ka <= -0.57 -> Ti kb > -0.16 (0.0774) | Kept: Ti kb > -0.16 -> Ti ka <= -0.57 (0.0991)
Removed: Ca kb > -0.37 -> Mn > -0.38 (0.0957) | Kept: Mn > -0.38 -> Ca kb > -0.37 (0.1038)
Removed: Si > -0.66 -> Ca kb > -0.37 (0.1114) | Kept: Ca kb > -0.37 -> Si > -0.66 (0.2685)
Removed: Ca kb > -0.37 -> Ca ka > -0.36 (0.1696) | Kept: Ca ka > -0.36 -> Ca kb > -0.37 (0.2543)
Removed: Fe kb > 0.40 -> Si > -0.66 (0.0640) | Kept: Si > -0.66 -> Fe kb > 0.40 (0.0959)
Removed: Fe kb > 0.40 -> Al <= 0.37 (0.0425) | Kept: Al <= 0.37 -> Fe kb > 0.40 (0.0466)
Removed: Si > 0.13 -> Si > -0.66 (0.1169) | Kept: Si > -0.66 -> Si > 0.13 (0.2057)
Removed: Ca ka > -0.36 -> Si > -0.66 (0.1075) | Kept: Si > -0.66 -> Ca ka > -0.36 (0.2199)
Removed: Si > -0.66 -> Mn > -0.38 (0.1085) | Kept: Mn > -0.38 -> Si > -0.66 (0.1126)
Removed: Mn > -0.38 -> K > -0.38 (0.0862) | Kept: K > -0.38 -> Mn > -0.38 (0.1435)
Removed: Ca kb > -0.23 -> Ca ka <= -0.36 (0.1376) | Kept: Ca ka <= -0.36 -> Ca kb > -0.23 (0.2867)
Removed: K > -0.38 -> Ca ka <= -0.36 (0.0782) | Kept: Ca ka <= -0.36 -> K > -0.38 (0.0834)
Removed: Fe kb > -0.07 -> Ti ka <= 1.88 (0.0412) | Kept: Ti ka <= 1.88 -> Fe kb > -0.07 (0.0856)
Removed: Ti ka <= 1.88 -> K > -0.20 (0.0679) | Kept: K > -0.20 -> Ti ka <= 1.88 (0.0694)
Removed: Fe kb > -0.07 -> Fe ka <= -0.43 (0.0413) | Kept: Fe ka <= -0.43 -> Fe kb > -0.07 (0.0860)
Removed: Ti kb > 0.26 -> K > -0.20 (0.0627) | Kept: K > -0.20 -> Ti kb > 0.26 (0.1143)
Removed: Fe ka <= -0.43 -> Ti kb > 0.26 (0.0416) | Kept: Ti kb > 0.26 -> Fe ka <= -0.43 (0.0559)
Removed: K > -0.20 -> Ti ka <= 0.93 (0.0604) | Kept: Ti ka <= 0.93 -> K > -0.20 (0.0671)
Removed: Ti kb > -0.16 -> K > -0.20 (0.0682) | Kept: K > -0.20 -> Ti kb > -0.16 (0.1220)
Removed: Ti kb > -0.63 -> Mn > -0.15 (0.0300) | Kept: Mn > -0.15 -> Ti kb > -0.63 (0.1238)
Removed: Al <= 0.37 -> Ti kb > -0.16 (0.0983) | Kept: Ti kb > -0.16 -> Al <= 0.37 (0.1114)
Removed: Ca kb <= 0.29 -> Ti kb > -0.16 (0.0763) | Kept: Ti kb > -0.16 -> Ca kb <= 0.29 (0.0848)
Removed: Ca kb <= 0.29 -> Al > -0.33 (0.0380) | Kept: Al > -0.33 -> Ca kb <= 0.29 (0.0781)
Removed: Fe ka <= 2.21 -> Ca kb <= 0.29 (0.0307) | Kept: Ca kb <= 0.29 -> Fe ka <= 2.21 (0.0415)
Removed: P > -0.24 -> sum Fe <= 0.31 (0.0299) | Kept: sum Fe <= 0.31 -> P > -0.24 (0.0499)
Removed: Al > -0.33 -> P > -0.24 (0.0400) | Kept: P > -0.24 -> Al > -0.33 (0.0598)
Removed: Ti kb > -0.63 -> Al > -0.33 (0.0430) | Kept: Al > -0.33 -> Ti kb > -0.63 (0.0736)
Removed: P > -0.24 -> Ti kb > -0.63 (0.0307) | Kept: Ti kb > -0.63 -> P > -0.24 (0.0718)
Removed: sum Fe <= 0.13 -> P > -0.24 (0.0231) | Kept: P > -0.24 -> sum Fe <= 0.13 (0.0543)
Removed: Fe kb > -1.03 -> K > 0.02 (0.0292) | Kept: K > 0.02 -> Fe kb > -1.03 (0.0451)
Removed: sum Fe <= 0.13 -> Ca kb > -0.04 (0.0216) | Kept: Ca kb > -0.04 -> sum Fe <= 0.13 (0.0606)
Removed: P > -0.17 -> sum Fe <= 0.13 (0.0251) | Kept: sum Fe <= 0.13 -> P > -0.17 (0.0449)
Removed: Al > -0.09 -> K <= 0.39 (0.0277) | Kept: K <= 0.39 -> Al > -0.09 (0.0628)
Removed: P > -0.17 -> K <= 0.39 (0.0168) | Kept: K <= 0.39 -> P > -0.17 (0.0286)
Removed: Al <= 0.16 -> Ti kb <= 0.26 (0.0205) | Kept: Ti kb <= 0.26 -> Al <= 0.16 (0.0278)
Removed: background1 <= -0.03 -> Ti kb <= 0.26 (0.0080) | Kept: Ti kb <= 0.26 -> background1 <= -0.03 (0.0242)
Removed: Mn <= -0.38 -> Ti kb <= -0.16 (0.0336) | Kept: Ti kb <= -0.16 -> Mn <= -0.38 (0.0368)
Removed: Ti kb <= -0.16 -> Fe kb <= 0.95 (0.0124) | Kept: Fe kb <= 0.95 -> Ti kb <= -0.16 (0.0197)
Removed: Cr <= 0.04 -> Si <= 0.13 (0.0111) | Kept: Si <= 0.13 -> Cr <= 0.04 (0.0218)
Removed: Al <= 0.16 -> Al > -0.09 (0.0286) | Kept: Al > -0.09 -> Al <= 0.16 (0.0292)
Removed: Cr > -0.28 -> sum Fe > -0.31 (0.0127) | Kept: sum Fe > -0.31 -> Cr > -0.28 (0.0321)
Removed: Ca kb > -0.04 -> P > -0.17 (0.0220) | Kept: P > -0.17 -> Ca kb > -0.04 (0.0230)
Removed: background2 <= 0.12 -> Ca kb > -0.04 (0.0070) | Kept: Ca kb > -0.04 -> background2 <= 0.12 (0.0257)
Removed: Cr <= 0.28 -> S > -0.06 (0.0165) | Kept: S > -0.06 -> Cr <= 0.28 (0.0214)
Removed: background2 > 0.12 -> S > 0.03 (0.0060) | Kept: S > 0.03 -> background2 > 0.12 (0.0095)
Removed: background2 <= 0.25 -> sum Fe <= -0.04 (0.0066) | Kept: sum Fe <= -0.04 -> background2 <= 0.25 (0.0119)
Removed: Cr <= 0.04 -> S > -0.06 (0.0147) | Kept: S > -0.06 -> Cr <= 0.04 (0.0211)
Removed: background2 <= 0.12 -> sum Fe <= -0.04 (0.0068) | Kept: sum Fe <= -0.04 -> background2 <= 0.12 (0.0122)
Removed: background2 > -0.06 -> sum Fe <= -0.04 (0.0104) | Kept: sum Fe <= -0.04 -> background2 > -0.06 (0.0138)
Removed: background2 > -0.06 -> background1 <= 0.05 (0.0054) | Kept: background1 <= 0.05 -> background2 > -0.06 (0.0070)
Removed: background1 <= -0.03 -> Cr > 0.04 (0.0073) | Kept: Cr > 0.04 -> background1 <= -0.03 (0.0096)
Removed: background2 > -0.29 -> Al <= -0.09 (0.0042) | Kept: Al <= -0.09 -> background2 > -0.29 (0.0406)
Removed: background3 <= 0.18 -> S > 0.03 (0.0038) | Kept: S > 0.03 -> background3 <= 0.18 (0.0089)
Removed: background2 <= -0.06 -> P <= 0.28 (0.0055) | Kept: P <= 0.28 -> background2 <= -0.06 (0.0124)
Removed: background1 <= 0.05 -> Ca kb <= -0.04 (0.0059) | Kept: Ca kb <= -0.04 -> background1 <= 0.05 (0.0144)
Removed: background1 <= 0.05 -> background1 <= 0.16 (0.0063) | Kept: background1 <= 0.16 -> background1 <= 0.05 (0.0072)
Removed: K <= 0.02 -> Al > 0.16 (0.0115) | Kept: Al > 0.16 -> K <= 0.02 (0.0141)
Removed: Ca kb <= -0.04 -> Al > 0.16 (0.0076) | Kept: Al > 0.16 -> Ca kb <= -0.04 (0.0105)
Removed: background1 > -0.16 -> sum Fe > -0.04 (0.0079) | Kept: sum Fe > -0.04 -> background1 > -0.16 (0.0082)
Removed: background1 > -0.16 -> P > 0.01 (0.0047) | Kept: P > 0.01 -> background1 > -0.16 (0.0080)
Removed: P > 0.01 -> Al > 0.16 (0.0080) | Kept: Al > 0.16 -> P > 0.01 (0.0080)
Removed: background3 > -0.04 -> Mn <= -0.15 (0.0022) | Kept: Mn <= -0.15 -> background3 > -0.04 (0.0096)

======================================================================
CONSTRUCTED GRAPH SUMMARY
======================================================================
Initial edges: 691 | Removed: 75
Predicate nodes: 100
Metric: Covariance
Weighting by explained variance: ENABLED

======================================================================
Processando Grafo - Semente: 1
======================================================================


Total bidirectional pairs found: 93
Removed: Fe ka > 0.86 -> Ca ka > -1.02 (0.1942) | Kept: Ca ka > -1.02 -> Fe ka > 0.86 (2.1178)
Removed: Fe ka > 0.86 -> Ti ka > 0.93 (0.1662) | Kept: Ti ka > 0.93 -> Fe ka > 0.86 (0.2830)
Removed: Ca ka <= 1.21 -> Fe ka > 0.86 (0.2629) | Kept: Fe ka > 0.86 -> Ca ka <= 1.21 (0.7403)
Removed: Ti ka > 0.93 -> Ca ka <= 1.21 (0.4937) | Kept: Ca ka <= 1.21 -> Ti ka > 0.93 (0.5149)
Removed: Ti ka > 0.93 -> Fe ka > -2.66 (0.3670) | Kept: Fe ka > -2.66 -> Ti ka > 0.93 (0.3697)
Removed: Fe ka > -0.43 -> Ca ka <= 1.21 (0.6049) | Kept: Ca ka <= 1.21 -> Fe ka > -0.43 (0.7574)
Removed: Ti ka > -0.57 -> Mn > -0.65 (0.3516) | Kept: Mn > -0.65 -> Ti ka > -0.57 (0.5324)
Removed: Fe ka > -2.66 -> Mn > -0.65 (0.1092) | Kept: Mn > -0.65 -> Fe ka > -2.66 (0.3068)
Removed: Mn > -0.65 -> Ti ka > -1.78 (0.1669) | Kept: Ti ka > -1.78 -> Mn > -0.65 (0.4410)
Removed: Ti ka <= -0.57 -> Mn > -0.65 (0.1272) | Kept: Mn > -0.65 -> Ti ka <= -0.57 (0.1406)
Removed: Fe ka > -2.66 -> Ti ka > -0.57 (0.1160) | Kept: Ti ka > -0.57 -> Fe ka > -2.66 (0.1477)
Removed: Ti ka > -0.57 -> Ti ka > -1.78 (0.1450) | Kept: Ti ka > -1.78 -> Ti ka > -0.57 (0.5129)
Removed: Ca kb > -0.37 -> Ti ka > -1.78 (0.0782) | Kept: Ti ka > -1.78 -> Ca kb > -0.37 (0.1302)
Removed: Ca kb > -0.37 -> Ca ka > -0.36 (0.1612) | Kept: Ca ka > -0.36 -> Ca kb > -0.37 (0.2134)
Removed: Ca kb > -0.37 -> Si > 0.13 (0.0955) | Kept: Si > 0.13 -> Ca kb > -0.37 (0.2099)
Removed: Ca kb > -0.37 -> Ti ka <= -0.57 (0.0850) | Kept: Ti ka <= -0.57 -> Ca kb > -0.37 (0.2157)
Removed: Ca kb > -0.37 -> Mn > -0.38 (0.0769) | Kept: Mn > -0.38 -> Ca kb > -0.37 (0.1167)
Removed: Si > -0.66 -> Mn > -0.38 (0.1090) | Kept: Mn > -0.38 -> Si > -0.66 (0.1246)
Removed: Ca ka > -0.36 -> Si > -0.66 (0.2098) | Kept: Si > -0.66 -> Ca ka > -0.36 (0.2173)
Removed: Si > 0.13 -> Ca ka > -0.36 (0.1115) | Kept: Ca ka > -0.36 -> Si > 0.13 (0.1164)
Removed: Si > -0.20 -> Si > 0.13 (0.1101) | Kept: Si > 0.13 -> Si > -0.20 (0.2105)
Removed: Mn > -0.38 -> Si > 0.13 (0.0797) | Kept: Si > 0.13 -> Mn > -0.38 (0.1100)
Removed: Ca ka > -0.36 -> Ti ka <= 0.93 (0.0965) | Kept: Ti ka <= 0.93 -> Ca ka > -0.36 (0.1005)
Removed: Fe kb > 0.40 -> Ca ka > -0.36 (0.0579) | Kept: Ca ka > -0.36 -> Fe kb > 0.40 (0.2009)
Removed: Mn > -0.38 -> Si > -0.20 (0.1052) | Kept: Si > -0.20 -> Mn > -0.38 (0.1692)
Removed: Mn > -0.38 -> Ti ka <= -0.57 (0.1049) | Kept: Ti ka <= -0.57 -> Mn > -0.38 (0.1305)
Removed: Ca ka <= -0.36 -> Si > -0.20 (0.1004) | Kept: Si > -0.20 -> Ca ka <= -0.36 (0.2602)
Removed: Ca kb > -0.23 -> Ca ka <= -0.36 (0.0623) | Kept: Ca ka <= -0.36 -> Ca kb > -0.23 (0.3671)
Removed: Fe kb > -0.07 -> Ca ka <= -0.36 (0.0513) | Kept: Ca ka <= -0.36 -> Fe kb > -0.07 (0.0992)
Removed: K > -0.20 -> Ca kb > -0.23 (0.0587) | Kept: Ca kb > -0.23 -> K > -0.20 (0.1785)
Removed: Fe kb > -0.07 -> K > -0.38 (0.0966) | Kept: K > -0.38 -> Fe kb > -0.07 (0.2027)
Removed: Fe kb > -0.07 -> K > -0.20 (0.0483) | Kept: K > -0.20 -> Fe kb > -0.07 (0.0750)
Removed: Ti kb > 0.26 -> Mn > -0.15 (0.0518) | Kept: Mn > -0.15 -> Ti kb > 0.26 (0.0639)
Removed: Mn > -0.15 -> Ti ka <= 1.88 (0.0303) | Kept: Ti ka <= 1.88 -> Mn > -0.15 (0.0781)
Removed: K > 0.02 -> Mn > -0.15 (0.0503) | Kept: Mn > -0.15 -> K > 0.02 (0.1000)
Removed: Ti kb > 0.26 -> Al > -0.33 (0.0367) | Kept: Al > -0.33 -> Ti kb > 0.26 (0.0410)
Removed: Ti kb > 0.26 -> sum Fe <= 0.31 (0.0417) | Kept: sum Fe <= 0.31 -> Ti kb > 0.26 (0.0519)
Removed: sum Fe <= 0.13 -> Ti kb > 0.26 (0.0269) | Kept: Ti kb > 0.26 -> sum Fe <= 0.13 (0.0385)
Removed: Al <= 0.37 -> Ti ka <= 1.88 (0.0505) | Kept: Ti ka <= 1.88 -> Al <= 0.37 (0.0698)
Removed: K > 0.02 -> Al <= 0.37 (0.0544) | Kept: Al <= 0.37 -> K > 0.02 (0.1507)
Removed: Fe ka <= -0.43 -> K > 0.02 (0.0367) | Kept: K > 0.02 -> Fe ka <= -0.43 (0.0446)
Removed: Fe ka <= 2.21 -> Ti kb > -0.63 (0.0332) | Kept: Ti kb > -0.63 -> Fe ka <= 2.21 (0.0443)
Removed: Fe ka <= 2.21 -> Ca kb > -0.04 (0.0168) | Kept: Ca kb > -0.04 -> Fe ka <= 2.21 (0.0493)
Removed: sum Fe <= 0.31 -> Al > -0.33 (0.0556) | Kept: Al > -0.33 -> sum Fe <= 0.31 (0.1166)
Removed: Ti kb <= 0.72 -> Al > -0.33 (0.0410) | Kept: Al > -0.33 -> Ti kb <= 0.72 (0.0783)
Removed: P > -0.24 -> Al > -0.33 (0.0309) | Kept: Al > -0.33 -> P > -0.24 (0.0329)
Removed: Ca kb <= 0.29 -> Al > -0.33 (0.0364) | Kept: Al > -0.33 -> Ca kb <= 0.29 (0.0393)
Removed: P > -0.24 -> Ti kb <= 0.26 (0.0239) | Kept: Ti kb <= 0.26 -> P > -0.24 (0.0743)
Removed: Ca kb <= 0.29 -> Ti kb > -0.63 (0.0356) | Kept: Ti kb > -0.63 -> Ca kb <= 0.29 (0.0387)
Removed: Ca kb <= 0.29 -> Ti kb <= 0.72 (0.0398) | Kept: Ti kb <= 0.72 -> Ca kb <= 0.29 (0.0441)
Removed: Fe kb <= -0.07 -> Mn <= 0.64 (0.0341) | Kept: Mn <= 0.64 -> Fe kb <= -0.07 (0.0870)
Removed: sum Fe <= 0.13 -> background2 <= -0.06 (0.0206) | Kept: background2 <= -0.06 -> sum Fe <= 0.13 (0.0214)
Removed: sum Fe <= 0.13 -> P > -0.17 (0.0230) | Kept: P > -0.17 -> sum Fe <= 0.13 (0.0728)
Removed: sum Fe <= 0.13 -> Ti kb <= 0.72 (0.0244) | Kept: Ti kb <= 0.72 -> sum Fe <= 0.13 (0.0398)
Removed: Ca kb > -0.04 -> Ti kb <= -0.16 (0.0211) | Kept: Ti kb <= -0.16 -> Ca kb > -0.04 (0.0276)
Removed: Ca kb > -0.04 -> Al > -0.09 (0.0213) | Kept: Al > -0.09 -> Ca kb > -0.04 (0.0316)
Removed: P > -0.17 -> Ti kb <= 0.72 (0.0233) | Kept: Ti kb <= 0.72 -> P > -0.17 (0.0323)
Removed: background2 <= 0.12 -> Fe ka <= -0.43 (0.0067) | Kept: Fe ka <= -0.43 -> background2 <= 0.12 (0.0394)
Removed: background2 <= 0.12 -> Cr <= 0.28 (0.0090) | Kept: Cr <= 0.28 -> background2 <= 0.12 (0.0192)
Removed: Al > -0.09 -> Al <= 0.16 (0.0263) | Kept: Al <= 0.16 -> Al > -0.09 (0.0264)
Removed: sum Fe > -0.31 -> Al <= 0.16 (0.0183) | Kept: Al <= 0.16 -> sum Fe > -0.31 (0.0279)
Removed: Al > -0.09 -> Ti kb <= -0.16 (0.0228) | Kept: Ti kb <= -0.16 -> Al > -0.09 (0.0282)
Removed: background2 <= 0.25 -> Mn <= -0.38 (0.0093) | Kept: Mn <= -0.38 -> background2 <= 0.25 (0.0524)
Removed: Cr > -0.28 -> Ca ka <= -1.02 (0.0140) | Kept: Ca ka <= -1.02 -> Cr > -0.28 (0.0566)
Removed: Cr <= 0.04 -> Ca ka <= -1.02 (0.0171) | Kept: Ca ka <= -1.02 -> Cr <= 0.04 (0.0243)
Removed: Al <= -0.09 -> Ca ka <= -1.02 (0.0232) | Kept: Ca ka <= -1.02 -> Al <= -0.09 (0.0247)
Removed: Cr > -0.28 -> sum Fe > -0.31 (0.0121) | Kept: sum Fe > -0.31 -> Cr > -0.28 (0.0152)
Removed: S > -0.06 -> Cr <= 0.04 (0.0098) | Kept: Cr <= 0.04 -> S > -0.06 (0.0130)
Removed: background1 <= -0.03 -> S > -0.06 (0.0087) | Kept: S > -0.06 -> background1 <= -0.03 (0.0091)
Removed: background2 <= 0.25 -> Cr <= 0.04 (0.0073) | Kept: Cr <= 0.04 -> background2 <= 0.25 (0.0142)
Removed: background1 <= -0.03 -> Cr <= 0.04 (0.0078) | Kept: Cr <= 0.04 -> background1 <= -0.03 (0.0480)
Removed: background3 <= 0.18 -> S > -0.13 (0.0035) | Kept: S > -0.13 -> background3 <= 0.18 (0.0169)
Removed: S > -0.13 -> sum Fe <= -0.04 (0.0075) | Kept: sum Fe <= -0.04 -> S > -0.13 (0.0122)
Removed: S > -0.13 -> S > 0.03 (0.0089) | Kept: S > 0.03 -> S > -0.13 (0.0194)
Removed: background2 <= -0.06 -> background1 <= -0.03 (0.0067) | Kept: background1 <= -0.03 -> background2 <= -0.06 (0.0076)
Removed: background2 > -0.06 -> Cr > -0.12 (0.0042) | Kept: Cr > -0.12 -> background2 > -0.06 (0.0065)
Removed: background2 > -0.06 -> background1 <= 0.16 (0.0055) | Kept: background1 <= 0.16 -> background2 > -0.06 (0.0066)
Removed: background1 <= 0.16 -> Ti kb <= -0.16 (0.0074) | Kept: Ti kb <= -0.16 -> background1 <= 0.16 (0.0135)
Removed: Al <= -0.09 -> sum Fe <= -0.04 (0.0236) | Kept: sum Fe <= -0.04 -> Al <= -0.09 (0.0262)
Removed: background2 > -0.29 -> Fe kb <= -0.07 (0.0059) | Kept: Fe kb <= -0.07 -> background2 > -0.29 (0.0069)
Removed: background2 > -0.29 -> P <= 0.28 (0.0084) | Kept: P <= 0.28 -> background2 > -0.29 (0.0103)
Removed: background3 <= -0.04 -> Cu > 0.06 (0.0037) | Kept: Cu > 0.06 -> background3 <= -0.04 (0.0103)
Removed: background1 <= 0.05 -> P <= 0.28 (0.0071) | Kept: P <= 0.28 -> background1 <= 0.05 (0.0110)
Removed: Rh L + Ar <= -0.05 -> Ca kb <= -0.04 (0.0074) | Kept: Ca kb <= -0.04 -> Rh L + Ar <= -0.05 (0.0198)
Removed: background1 <= 0.16 -> Ca kb <= -0.04 (0.0059) | Kept: Ca kb <= -0.04 -> background1 <= 0.16 (0.0119)
Removed: Ca kb <= -0.04 -> Mn <= -0.15 (0.0128) | Kept: Mn <= -0.15 -> Ca kb <= -0.04 (0.0138)

,Predicate_Cov_Seed_0,Predicate_Cov_Seed_1,Predicate_Cov_Seed_2,Predicate_Cov_Seed_3
0,Ca ka > -1.73,Ca ka > -1.73,Ca ka > -1.73,Ca ka > -1.73
1,Ca ka > -1.02,Ca ka > -1.02,Ca ka <= 1.21,Ca ka > -1.02
2,Ca ka <= 1.21,Fe ka > 0.86,Ca ka > -1.02,Ca ka <= 1.21
3,Fe ka > 0.86,Ti ka > 0.93,Ti ka > 0.93,Ti ka > 0.93
4,Fe ka > -0.43,Ca ka <= 1.21,Fe ka > 0.86,Fe ka > -2.66
...,...,...,...,...
102,NaN,P <= 0.01,Rh L + Ar <= 0.09,NaN
103,NaN,Class_A,Cu <= 0.06,NaN
104,NaN,Class_B,background3 > -0.17,NaN
105,NaN,NaN,Class_A,NaN
106,NaN,NaN,Class_B,NaN

In [9]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_cov_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_cov = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_cov = lrc_summed_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_cov = lrc_summed_df_cov.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
#lrc_summed_unique_df_cov = lrc_summed_unique_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_cov

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Ca ka > -1.73,14.158535,Ca ka,-1.73,>
1,Fe ka > 0.86,4.127752,Fe ka,0.86,>
2,Ti ka > 0.93,3.996832,Ti ka,0.93,>
3,Mn > -0.65,2.389461,Mn,-0.65,>
4,Si > -0.66,2.147667,Si,-0.66,>
5,Ca kb > -0.37,1.816538,Ca kb,-0.37,>
6,Fe kb > 0.40,1.502563,Fe kb,0.40,>
7,K > -0.38,1.373818,K,-0.38,>
8,Ti kb > -0.16,1.169004,Ti kb,-0.16,>
9,Al <= 0.37,1.145165,Al,0.37,<=
10,sum Fe <= 0.31,0.906964,sum Fe,0.31,<=
11,P > -0.24,0.881383,P,-0.24,>
12,Cu <= 0.15,0.756720,Cu,0.15,<=
13,Cr <= 0.28,0.726707,Cr,0.28,<=
14,background2 <= -0.06,0.725257,background2,-0.06,<=
15,background3 > -0.17,0.699077,background3,-0.17,>
16,S > 0.03,0.695474,S,0.03,>
17,background1 <= 0.05,0.683355,background1,0.05,<=
18,Rh L + Ar > 0.09,0.579740,Rh L + Ar,0.09,>
19,Fe ka + Ti ka <= 0.16,0.280946,Fe ka + Ti ka,0.16,<=
20,Class_B,0.000000,None,None,None

In [10]:
# Criar zone_sums_df para dados NÃO pré-processados (Xcalclass)
spectral_zones_original = exp.extract_spectral_zones(Xcalclass, spectral_cuts)
zones_original = exp.aggregate_spectral_zones_pca(spectral_zones_original) # apca aggregation

# Aplicar o mapeamento
lrc_summed_df_cov_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_cov,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_cov_natural

Zone 'Al': VE = 89.82%, dim = 15 variables
Zone 'Si': VE = 95.22%, dim = 12 variables
Zone 'P': VE = 61.00%, dim = 17 variables
Zone 'S': VE = 42.01%, dim = 18 variables
Zone 'Rh L + Ar': VE = 51.54%, dim = 33 variables
Zone 'K': VE = 88.55%, dim = 16 variables
Zone 'Ca ka': VE = 99.40%, dim = 16 variables
Zone 'Ca kb': VE = 72.71%, dim = 27 variables
Zone 'Ti ka': VE = 93.59%, dim = 19 variables
Zone 'Ti kb': VE = 88.32%, dim = 19 variables
Zone 'Cr': VE = 56.23%, dim = 33 variables
Zone 'Mn': VE = 93.26%, dim = 18 variables
Zone 'Fe ka': VE = 58.12%, dim = 34 variables
Zone 'Fe kb': VE = 55.52%, dim = 26 variables
Zone 'background1': VE = 34.82%, dim = 31 variables
Zone 'Cu': VE = 55.93%, dim = 15 variables
Zone 'background2': VE = 26.61%, dim = 125 variables
Zone 'Fe ka + Ti ka': VE = 39.81%, dim = 23 variables
Zone 'background3': VE = 19.45%, dim = 71 variables
Zone 'sum Fe': VE = 69.07%, dim = 28 variables

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,Ca ka > -1.73,14.158535,Ca ka,-1.73,>,-2.806273,140.0,0.001954,Ca ka > -2.806273
1,Ca ka > -1.02,6.133361,Ca ka,-1.02,>,-1.635267,143.0,0.000757,Ca ka > -1.635267
2,Ca ka <= 1.21,4.791394,Ca ka,1.21,<=,2.034067,2.0,0.019671,Ca ka <= 2.034067
3,Fe ka > 0.86,4.127752,Fe ka,0.86,>,55.595005,114.0,0.001174,Fe ka > 55.595005
4,Ti ka > 0.93,3.996832,Ti ka,0.93,>,6.770758,113.0,0.010621,Ti ka > 6.770758
...,...,...,...,...,...,...,...,...,...
109,Fe ka + Ti ka <= 0.06,0.002204,Fe ka + Ti ka,0.06,<=,0.049667,10.0,0.000571,Fe ka + Ti ka <= 0.049667
110,S <= -0.06,0.001321,S,-0.06,<=,-0.052921,96.0,0.001041,S <= -0.052921
111,P <= 0.01,0.000947,P,0.01,<=,-0.008542,69.0,0.002267,P <= -0.008542
112,Class_B,0.000000,None,None,None,NaN,NaN,NaN,None
113,Class_A,0.000000,None,None,None,NaN,NaN,NaN,None

## Reconstrução de Thresholds Multivariados

Agora vamos pegar os thresholds dos predicados mais importantes e reconstruí-los como espectros completos.

In [11]:
import plotly.graph_objects as go

n = 0
zone_name = lrc_summed_df_cov_natural.iloc[n]['Zone']
threshold_score = float(lrc_summed_df_cov_natural.iloc[n]['Threshold_Natural'])  # Corrigido: usa n em vez de 7

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
print(f"  - Range de energias: {threshold_spectrum.index[0]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_cov_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona 'Ca ka':
  - Dimensão: 16 variáveis espectrais
  - Range de energias: 3.54 - 3.84
  - Variância explicada pela PC1: 99.40%

In [12]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = exp.calculate_predicate_perturbation(
        estimator=svm_model[3],
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        #perturbation_value=0,
        perturbation_mode='median', # valores entre 'mean' ou 'min'
        stats_source='full', # full indica usar todas as amostras para calcular estatísticas enquanto que 'fold' usa apenas as amostras do fold atual
        #metric='mean_abs_diff',   # Média com sinal (pode ser negativo)
        aim='classification',
        metric='probability_shift', 
        verbose=True
    )

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graph(
        bags_result=all_results_pert[seed]['bags_result'],
        predicate_ranking_dict=all_results_pert[seed]['pert_results_dict'],
        metric_column='Perturbation',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )

    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Samples: Yes | Predicates: No (All) | Valid: 123 | Discarded: 37
Bag_2 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_3 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_4 | Samples: Yes | Predicates: No (All) | Valid: 122 | Discarded: 38
Bag_5 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_6 | Samples: Yes | Predicates: No (All) | Valid: 121 | Discarded: 39
Bag_7 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_8 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_9 | Samples: Yes | Predicates: No (All) | Valid: 120 | Discarded: 40
Bag_10 | Samples: Yes | Predicates: No (All) | Valid: 121 | Discarded: 39
======================================================================
PERTURBATION IMPORTANCE FOR PREDICATES
======================================================================
Task type (aim): classification
Perturbation mode: median
Statistics source: full
Metric: probability_shift
Total folds: 10


[Bag_1] Processing 123 predicates...
  Predicate: Al > -0.33 (n=93)
    Zone: 15 columns
    Importance: 0.002035
  Predicate: Al <= -0.09 (n=49)
    Zone: 15 columns
    Importance: 0.002559
  Predicate: Al > -0.09 (n=69)
    Zone: 15 columns
    Importance: 0.002207
  Predicate: Al <= 0.16 (n=71)
    Zone: 15 columns
    Importance: 0.001951
  Predicate: Al > 0.16 (n=47)
    Zone: 15 columns
    Importance: 0.002962
  Predicate: Al <= 0.37 (n=96)
    Zone: 15 columns
    Importance: 0.001926
  Predicate: Si > -0.66 (n=94)
    Zone: 12 columns
    Importance: 0.015360
  Predicate: Si <= -0.20 (n=44)
    Zone: 12 columns
    Importance: 0.011138
  Predicate: Si > -0.20 (n=74)
    Zone: 12 columns
    Importance: 0.017902
  Predicate: Si <= 0.13 (n=66)
    Zone: 12 columns
    Importance: 0.007930
  Predicate: Si > 0.13 (n=52)
    Zone: 12 columns
    Importance: 0.024836
  Predicate: Si <= 0.69 (n=94)
    Zone: 12 columns
    Importance: 0.010188
  Predicate: P <= -0.24 (n=29)
    Zone: 17 columns
    Importance: 0.003555
  Predicate: P > -0.24 (n=89)
    Zone: 17 columns
    Importance: 0.002203
  Predicate: P <= -0.17 (n=52)
    Zone: 17 columns
    Importance: 0.002604
  Predicate: P > -0.17 (n=66)
    Zone: 17 columns
    Importance: 0.002481
  Predicate: P <= 0.01 (n=71)
    Zone: 17 columns
    Importance: 0.002165
  Predicate: P > 0.01 (n=47)
    Zone: 17 columns
    Importance: 0.003096
  Predicate: P <= 0.28 (n=94)
    Zone: 17 columns
    Importance: 0.001923
  Predicate: S <= -0.13 (n=29)
    Zone: 18 columns
    Importance: 0.003540
  Predicate: S > -0.13 (n=89)
    Zone: 18 columns
    Importance: 0.000758
  Predicate: S <= -0.06 (n=51)
    Zone: 18 columns
    Importance: 0.002317
  Predicate: S > -0.06 (n=67)
    Zone: 18 columns
    Importance: 0.000776
  Predicate: S <= 0.03 (n=73)
    Zone: 18 columns
    Importance: 0.001783
  Predicate: S > 0.03 (n=45)
    Zone: 18 columns
    Importance: 0.000887
  Predicate: S <= 0.12 (n=93)
    Zone: 18 columns
    Importance: 0.001608
  Predicate: Rh L + Ar > -0.25 (n=95)
    Zone: 33 columns
    Importance: 0.001285
  Predicate: Rh L + Ar <= -0.05 (n=45)
    Zone: 33 columns
    Importance: 0.002018
  Predicate: Rh L + Ar > -0.05 (n=73)
    Zone: 33 columns
    Importance: 0.001346
  Predicate: Rh L + Ar <= 0.09 (n=73)
    Zone: 33 columns
    Importance: 0.001718
  Predicate: Rh L + Ar > 0.09 (n=45)
    Zone: 33 columns
    Importance: 0.001415
  Predicate: Rh L + Ar <= 0.23 (n=96)
    Zone: 33 columns
    Importance: 0.001625
  Predicate: K > -0.38 (n=94)
    Zone: 16 columns
    Importance: 0.000972
  Predicate: K <= -0.20 (n=50)
    Zone: 16 columns
    Importance: 0.001005
  Predicate: K > -0.20 (n=68)
    Zone: 16 columns
    Importance: 0.001023
  Predicate: K <= 0.02 (n=72)
    Zone: 16 columns
    Importance: 0.000847
  Predicate: K > 0.02 (n=46)
    Zone: 16 columns
    Importance: 0.001280
  Predicate: K <= 0.39 (n=96)
    Zone: 16 columns
    Importance: 0.000963
  Predicate: Ca ka > -1.73 (n=94)
    Zone: 16 columns
    Importance: 0.187820
  Predicate: Ca ka <= -1.02 (n=49)
    Zone: 16 columns
    Importance: 0.162082
  Predicate: Ca ka > -1.02 (n=69)
    Zone: 16 columns
    Importance: 0.214587
  Predicate: Ca ka <= -0.36 (n=69)
    Zone: 16 columns
    Importance: 0.124185
  Predicate: Ca ka > -0.36 (n=49)
    Zone: 16 columns
    Importance: 0.289381
  Predicate: Ca ka <= 1.21 (n=92)
    Zone: 16 columns
    Importance: 0.151767
  Predicate: Ca kb > -0.37 (n=93)
    Zone: 27 columns
    Importance: 0.004963
  Predicate: Ca kb <= -0.23 (n=48)
    Zone: 27 columns
    Importance: 0.005380
  Predicate: Ca kb > -0.23 (n=70)
    Zone: 27 columns
    Importance: 0.004933
  Predicate: Ca kb <= -0.04 (n=71)
    Zone: 27 columns
    Importance: 0.004348
  Predicate: Ca kb > -0.04 (n=47)
    Zone: 27 columns
    Importance: 0.006273
  Predicate: Ca kb <= 0.29 (n=92)
    Zone: 27 columns
    Importance: 0.005289
  Predicate: Ti ka > -1.78 (n=94)
    Zone: 19 columns
    Importance: 0.033219
  Predicate: Ti ka <= -0.57 (n=52)
    Zone: 19 columns
    Importance: 0.031429
  Predicate: Ti ka > -0.57 (n=66)
    Zone: 19 columns
    Importance: 0.043069
  Predicate: Ti ka <= 0.93 (n=74)
    Zone: 19 columns
    Importance: 0.023732
  Predicate: Ti ka > 0.93 (n=44)
    Zone: 19 columns
    Importance: 0.061833
  Predicate: Ti ka <= 1.88 (n=97)
    Zone: 19 columns
    Importance: 0.027610
  Predicate: Ti kb > -0.63 (n=94)
    Zone: 19 columns
    Importance: 0.003907
  Predicate: Ti kb <= -0.16 (n=53)
    Zone: 19 columns
    Importance: 0.005578
  Predicate: Ti kb > -0.16 (n=65)
    Zone: 19 columns
    Importance: 0.004916
  Predicate: Ti kb <= 0.26 (n=76)
    Zone: 19 columns
    Importance: 0.004391
  Predicate: Ti kb > 0.26 (n=42)
    Zone: 19 columns
    Importance: 0.006701
  Predicate: Ti kb <= 0.72 (n=97)
    Zone: 19 columns
    Importance: 0.004614
  Predicate: Cr > -0.28 (n=92)
    Zone: 33 columns
    Importance: 0.002151
  Predicate: Cr <= -0.12 (n=48)
    Zone: 33 columns
    Importance: 0.002944
  Predicate: Cr > -0.12 (n=70)
    Zone: 33 columns
    Importance: 0.002105
  Predicate: Cr <= 0.04 (n=73)
    Zone: 33 columns
    Importance: 0.002256
  Predicate: Cr > 0.04 (n=45)
    Zone: 33 columns
    Importance: 0.002756
  Predicate: Cr <= 0.28 (n=94)
    Zone: 33 columns
    Importance: 0.002056
  Predicate: Mn > -0.65 (n=99)
    Zone: 18 columns
    Importance: 0.011894
  Predicate: Mn <= -0.38 (n=45)
    Zone: 18 columns
    Importance: 0.005263
  Predicate: Mn > -0.38 (n=73)
    Zone: 18 columns
    Importance: 0.014479
  Predicate: Mn <= -0.15 (n=68)
    Zone: 18 columns
    Importance: 0.003995
  Predicate: Mn > -0.15 (n=50)
    Zone: 18 columns
    Importance: 0.020443
  Predicate: Mn <= 0.64 (n=94)
    Zone: 18 columns
    Importance: 0.005028
  Predicate: Fe ka > -2.66 (n=92)
    Zone: 34 columns
    Importance: 0.082057
  Predicate: Fe ka <= -0.43 (n=50)
    Zone: 34 columns
    Importance: 0.073010
  Predicate: Fe ka > -0.43 (n=68)
    Zone: 34 columns
    Importance: 0.077190
  Predicate: Fe ka <= 0.86 (n=73)
    Zone: 34 columns
    Importance: 0.065757
  Predicate: Fe ka > 0.86 (n=45)
    Zone: 34 columns
    Importance: 0.091092
  Predicate: Fe ka <= 2.21 (n=91)
    Zone: 34 columns
    Importance: 0.068925
  Predicate: Fe kb > -1.03 (n=92)
    Zone: 26 columns
    Importance: 0.012078
  Predicate: Fe kb <= -0.07 (n=49)
    Zone: 26 columns
    Importance: 0.013894
  Predicate: Fe kb > -0.07 (n=69)
    Zone: 26 columns
    Importance: 0.012769
  Predicate: Fe kb <= 0.40 (n=75)
    Zone: 26 columns
    Importance: 0.011284
  Predicate: Fe kb > 0.40 (n=43)
    Zone: 26 columns
    Importance: 0.016643
  Predicate: Fe kb <= 0.95 (n=91)
    Zone: 26 columns
    Importance: 0.011399
  Predicate: background1 <= -0.16 (n=29)
    Zone: 31 columns
    Importance: 0.002375
  Predicate: background1 > -0.16 (n=89)
    Zone: 31 columns
    Importance: 0.000947
  Predicate: background1 <= -0.03 (n=47)
    Zone: 31 columns
    Importance: 0.001861
  Predicate: background1 > -0.03 (n=71)
    Zone: 31 columns
    Importance: 0.000926
  Predicate: background1 <= 0.05 (n=70)
    Zone: 31 columns
    Importance: 0.001454
  Predicate: background1 > 0.05 (n=48)
    Zone: 31 columns
    Importance: 0.001072
  Predicate: background1 <= 0.16 (n=95)
    Zone: 31 columns
    Importance: 0.001341
  Predicate: Cu > -0.18 (n=93)
    Zone: 15 columns
    Importance: 0.001219
  Predicate: Cu <= -0.06 (n=46)
    Zone: 15 columns
    Importance: 0.001622
  Predicate: Cu > -0.06 (n=72)
    Zone: 15 columns
    Importance: 0.001348
  Predicate: Cu <= 0.06 (n=68)
    Zone: 15 columns
    Importance: 0.001282
  Predicate: Cu > 0.06 (n=50)
    Zone: 15 columns
    Importance: 0.001691
  Predicate: Cu <= 0.15 (n=91)
    Zone: 15 columns
    Importance: 0.001099
  Predicate: background2 > -0.29 (n=91)
    Zone: 125 columns
    Importance: 0.002982
  Predicate: background2 <= -0.06 (n=47)
    Zone: 125 columns
    Importance: 0.004482
  Predicate: background2 > -0.06 (n=71)
    Zone: 125 columns
    Importance: 0.002996
  Predicate: background2 <= 0.12 (n=71)
    Zone: 125 columns
    Importance: 0.004076
  Predicate: background2 > 0.12 (n=47)
    Zone: 125 columns
    Importance: 0.002851
  Predicate: background2 <= 0.25 (n=95)
    Zone: 125 columns
    Importance: 0.003914
  Predicate: Fe ka + Ti ka > -0.15 (n=94)
    Zone: 23 columns
    Importance: 0.000551
  Predicate: Fe ka + Ti ka <= -0.04 (n=48)
    Zone: 23 columns
    Importance: 0.000747
  Predicate: Fe ka + Ti ka > -0.04 (n=70)
    Zone: 23 columns
    Importance: 0.000572
  Predicate: Fe ka + Ti ka <= 0.06 (n=70)
    Zone: 23 columns
    Importance: 0.000654
  Predicate: Fe ka + Ti ka > 0.06 (n=48)
    Zone: 23 columns
    Importance: 0.000628
  Predicate: Fe ka + Ti ka <= 0.16 (n=98)
    Zone: 23 columns
    Importance: 0.000620
  Predicate: background3 > -0.17 (n=91)
    Zone: 71 columns
    Importance: 0.002001
  Predicate: background3 <= -0.04 (n=50)
    Zone: 71 columns
    Importance: 0.002802
  Predicate: background3 > -0.04 (n=68)
    Zone: 71 columns
    Importance: 0.002017
  Predicate: background3 <= 0.04 (n=70)
    Zone: 71 columns
    Importance: 0.002500
  Predicate: background3 > 0.04 (n=48)
    Zone: 71 columns
    Importance: 0.002130
  Predicate: background3 <= 0.18 (n=96)
    Zone: 71 columns
    Importance: 0.002207
  Predicate: sum Fe > -0.31 (n=94)
    Zone: 28 columns
    Importance: 0.001332
  Predicate: sum Fe <= -0.04 (n=48)
    Zone: 28 columns
    Importance: 0.002718
  Predicate: sum Fe > -0.04 (n=70)
    Zone: 28 columns
    Importance: 0.001043
  Predicate: sum Fe <= 0.13 (n=74)
    Zone: 28 columns
    Importance: 0.002135
  Predicate: sum Fe > 0.13 (n=44)
    Zone: 28 columns
    Importance: 0.001035
  Predicate: sum Fe <= 0.31 (n=97)
    Zone: 28 columns
    Importance: 0.001835

[Bag_2] Processing 120 predicates...
  Predicate: Al > -0.33 (n=95)
    Zone: 15 columns
    Importance: 0.002463
  Predicate: Al <= -0.09 (n=49)
    Zone: 15 columns
    Importance: 0.002816
  Predicate: Al > -0.09 (n=69)
    Zone: 15 columns
    Importance: 0.002749
  Predicate: Al <= 0.16 (n=71)
    Zone: 15 columns
    Importance: 0.002136
  Predicate: Al > 0.16 (n=47)
    Zone: 15 columns
    Importance: 0.003745
  Predicate: Al <= 0.37 (n=93)
    Zone: 15 columns
    Importance: 0.002067
  Predicate: Si > -0.66 (n=96)
    Zone: 12 columns
    Importance: 0.015909
  Predicate: Si <= -0.20 (n=48)
    Zone: 12 columns
    Importance: 0.014750
  Predicate: Si > -0.20 (n=70)
    Zone: 12 columns
    Importance: 0.018712
  Predicate: Si <= 0.13 (n=73)
    Zone: 12 columns
    Importance: 0.010249
  Predicate: Si > 0.13 (n=45)
    Zone: 12 columns
    Importance: 0.028214
  Predicate: Si <= 0.69 (n=93)
    Zone: 12 columns
    Importance: 0.011222
  Predicate: P > -0.24 (n=95)
    Zone: 17 columns
    Importance: 0.002140
  Predicate: P <= -0.17 (n=45)
    Zone: 17 columns
    Importance: 0.002939
  Predicate: P > -0.17 (n=73)
    Zone: 17 columns
    Importance: 0.002270
  Predicate: P <= 0.01 (n=72)
    Zone: 17 columns
    Importance: 0.002241
  Predicate: P > 0.01 (n=46)
    Zone: 17 columns
    Importance: 0.002969
  Predicate: P <= 0.28 (n=91)
    Zone: 17 columns
    Importance: 0.002113
  Predicate: S > -0.13 (n=91)
    Zone: 18 columns
    Importance: 0.000681
  Predicate: S <= -0.06 (n=50)
    Zone: 18 columns
    Importance: 0.002716
  Predicate: S > -0.06 (n=68)
    Zone: 18 columns
    Importance: 0.000628
  Predicate: S <= 0.03 (n=73)
    Zone: 18 columns
    Importance: 0.002040
  Predicate: S > 0.03 (n=45)
    Zone: 18 columns
    Importance: 0.000658
  Predicate: S <= 0.12 (n=91)
    Zone: 18 columns
    Importance: 0.001747
  Predicate: Rh L + Ar > -0.25 (n=97)
    Zone: 33 columns
    Importance: 0.001279
  Predicate: Rh L + Ar <= -0.05 (n=42)
    Zone: 33 columns
    Importance: 0.002083
  Predicate: Rh L + Ar > -0.05 (n=76)
    Zone: 33 columns
    Importance: 0.001294
  Predicate: Rh L + Ar <= 0.09 (n=68)
    Zone: 33 columns
    Importance: 0.001736
  Predicate: Rh L + Ar > 0.09 (n=50)
    Zone: 33 columns
    Importance: 0.001356
  Predicate: Rh L + Ar <= 0.23 (n=93)
    Zone: 33 columns
    Importance: 0.001680
  Predicate: K > -0.38 (n=94)
    Zone: 16 columns
    Importance: 0.001182
  Predicate: K <= -0.20 (n=45)
    Zone: 16 columns
    Importance: 0.001178
  Predicate: K > -0.20 (n=73)
    Zone: 16 columns
    Importance: 0.001191
  Predicate: K <= 0.02 (n=69)
    Zone: 16 columns
    Importance: 0.000890
  Predicate: K > 0.02 (n=49)
    Zone: 16 columns
    Importance: 0.001603
  Predicate: K <= 0.39 (n=93)
    Zone: 16 columns
    Importance: 0.001048
  Predicate: Ca ka > -1.73 (n=92)
    Zone: 16 columns
    Importance: 0.180310
  Predicate: Ca ka <= -1.02 (n=48)
    Zone: 16 columns
    Importance: 0.160135
  Predicate: Ca ka > -1.02 (n=70)
    Zone: 16 columns
    Importance: 0.204098
  Predicate: Ca ka <= -0.36 (n=71)
    Zone: 16 columns
    Importance: 0.119818
  Predicate: Ca ka > -0.36 (n=47)
    Zone: 16 columns
    Importance: 0.286515
  Predicate: Ca ka <= 1.21 (n=91)
    Zone: 16 columns
    Importance: 0.141225
  Predicate: Ca kb > -0.37 (n=94)
    Zone: 27 columns
    Importance: 0.005135
  Predicate: Ca kb <= -0.23 (n=48)
    Zone: 27 columns
    Importance: 0.005772
  Predicate: Ca kb > -0.23 (n=70)
    Zone: 27 columns
    Importance: 0.005045
  Predicate: Ca kb <= -0.04 (n=71)
    Zone: 27 columns
    Importance: 0.004483
  Predicate: Ca kb > -0.04 (n=47)
    Zone: 27 columns
    Importance: 0.006636
  Predicate: Ca kb <= 0.29 (n=90)
    Zone: 27 columns
    Importance: 0.005630
  Predicate: Ti ka > -1.78 (n=99)
    Zone: 19 columns
    Importance: 0.036056
  Predicate: Ti ka <= -0.57 (n=42)
    Zone: 19 columns
    Importance: 0.033189
  Predicate: Ti ka > -0.57 (n=76)
    Zone: 19 columns
    Importance: 0.043804
  Predicate: Ti ka <= 0.93 (n=67)
    Zone: 19 columns
    Importance: 0.022580
  Predicate: Ti ka > 0.93 (n=51)
    Zone: 19 columns
    Importance: 0.062943
  Predicate: Ti ka <= 1.88 (n=91)
    Zone: 19 columns
    Importance: 0.026224
  Predicate: Ti kb > -0.63 (n=97)
    Zone: 19 columns
    Importance: 0.004429
  Predicate: Ti kb <= -0.16 (n=44)
    Zone: 19 columns
    Importance: 0.005512
  Predicate: Ti kb > -0.16 (n=74)
    Zone: 19 columns
    Importance: 0.005309
  Predicate: Ti kb <= 0.26 (n=68)
    Zone: 19 columns
    Importance: 0.004114
  Predicate: Ti kb > 0.26 (n=50)
    Zone: 19 columns
    Importance: 0.007112
  Predicate: Ti kb <= 0.72 (n=92)
    Zone: 19 columns
    Importance: 0.004391
  Predicate: Cr > -0.28 (n=94)
    Zone: 33 columns
    Importance: 0.001904
  Predicate: Cr <= -0.12 (n=47)
    Zone: 33 columns
    Importance: 0.003136
  Predicate: Cr > -0.12 (n=71)
    Zone: 33 columns
    Importance: 0.001755
  Predicate: Cr <= 0.04 (n=73)
    Zone: 33 columns
    Importance: 0.002327
  Predicate: Cr > 0.04 (n=45)
    Zone: 33 columns
    Importance: 0.002270
  Predicate: Cr <= 0.28 (n=98)
    Zone: 33 columns
    Importance: 0.001983
  Predicate: Mn > -0.65 (n=93)
    Zone: 18 columns
    Importance: 0.012480
  Predicate: Mn <= -0.38 (n=47)
    Zone: 18 columns
    Importance: 0.008929
  Predicate: Mn > -0.38 (n=71)
    Zone: 18 columns
    Importance: 0.014885
  Predicate: Mn <= -0.15 (n=72)
    Zone: 18 columns
    Importance: 0.006370
  Predicate: Mn > -0.15 (n=46)
    Zone: 18 columns
    Importance: 0.022128
  Predicate: Mn <= 0.64 (n=95)
    Zone: 18 columns
    Importance: 0.007263
  Predicate: Fe ka > -2.66 (n=93)
    Zone: 34 columns
    Importance: 0.078077
  Predicate: Fe ka <= -0.43 (n=45)
    Zone: 34 columns
    Importance: 0.055655
  Predicate: Fe ka > -0.43 (n=73)
    Zone: 34 columns
    Importance: 0.080154
  Predicate: Fe ka <= 0.86 (n=68)
    Zone: 34 columns
    Importance: 0.055354
  Predicate: Fe ka > 0.86 (n=50)
    Zone: 34 columns
    Importance: 0.091832
  Predicate: Fe ka <= 2.21 (n=93)
    Zone: 34 columns
    Importance: 0.059754
  Predicate: Fe kb > -1.03 (n=94)
    Zone: 26 columns
    Importance: 0.013059
  Predicate: Fe kb <= -0.07 (n=45)
    Zone: 26 columns
    Importance: 0.012733
  Predicate: Fe kb > -0.07 (n=73)
    Zone: 26 columns
    Importance: 0.014371
  Predicate: Fe kb <= 0.40 (n=69)
    Zone: 26 columns
    Importance: 0.011059
  Predicate: Fe kb > 0.40 (n=49)
    Zone: 26 columns
    Importance: 0.017530
  Predicate: Fe kb <= 0.95 (n=93)
    Zone: 26 columns
    Importance: 0.011075
  Predicate: background1 > -0.16 (n=91)
    Zone: 31 columns
    Importance: 0.000992
  Predicate: background1 <= -0.03 (n=50)
    Zone: 31 columns
    Importance: 0.001951
  Predicate: background1 > -0.03 (n=68)
    Zone: 31 columns
    Importance: 0.000973
  Predicate: background1 <= 0.05 (n=76)
    Zone: 31 columns
    Importance: 0.001472
  Predicate: background1 > 0.05 (n=42)
    Zone: 31 columns
    Importance: 0.001233
  Predicate: background1 <= 0.16 (n=96)
    Zone: 31 columns
    Importance: 0.001352
  Predicate: Cu > -0.18 (n=93)
    Zone: 15 columns
    Importance: 0.001223
  Predicate: Cu <= -0.06 (n=49)
    Zone: 15 columns
    Importance: 0.001715
  Predicate: Cu > -0.06 (n=69)
    Zone: 15 columns
    Importance: 0.001405
  Predicate: Cu <= 0.06 (n=72)
    Zone: 15 columns
    Importance: 0.001291
  Predicate: Cu > 0.06 (n=46)
    Zone: 15 columns
    Importance: 0.001913
  Predicate: Cu <= 0.15 (n=95)
    Zone: 15 columns
    Importance: 0.001140
  Predicate: background2 > -0.29 (n=93)
    Zone: 125 columns
    Importance: 0.003323
  Predicate: background2 <= -0.06 (n=50)
    Zone: 125 columns
    Importance: 0.005001
  Predicate: background2 > -0.06 (n=68)
    Zone: 125 columns
    Importance: 0.003345
  Predicate: background2 <= 0.12 (n=73)
    Zone: 125 columns
    Importance: 0.004481
  Predicate: background2 > 0.12 (n=45)
    Zone: 125 columns
    Importance: 0.003341
  Predicate: background2 <= 0.25 (n=94)
    Zone: 125 columns
    Importance: 0.004227
  Predicate: Fe ka + Ti ka > -0.15 (n=96)
    Zone: 23 columns
    Importance: 0.000618
  Predicate: Fe ka + Ti ka <= -0.04 (n=44)
    Zone: 23 columns
    Importance: 0.000735
  Predicate: Fe ka + Ti ka > -0.04 (n=74)
    Zone: 23 columns
    Importance: 0.000658
  Predicate: Fe ka + Ti ka <= 0.06 (n=68)
    Zone: 23 columns
    Importance: 0.000647
  Predicate: Fe ka + Ti ka > 0.06 (n=50)
    Zone: 23 columns
    Importance: 0.000741
  Predicate: Fe ka + Ti ka <= 0.16 (n=92)
    Zone: 23 columns
    Importance: 0.000608
  Predicate: background3 > -0.17 (n=91)
    Zone: 71 columns
    Importance: 0.002088
  Predicate: background3 <= -0.04 (n=49)
    Zone: 71 columns
    Importance: 0.002928

,Predicate_pert_Seed_0,Predicate_pert_Seed_1,Predicate_pert_Seed_2,Predicate_pert_Seed_3
0,Ca ka > -0.36,Ca ka > -0.36,Ca ka > -0.36,Ca ka > -0.36
1,Ca ka > -1.02,Ca ka > -1.02,Ca ka > -1.02,Ca ka > -1.02
2,Ca ka > -1.73,Ca ka > -1.73,Ca ka > -1.73,Ca ka > -1.73
3,Ca ka <= -1.02,Ca ka <= -1.02,Ca ka <= -1.02,Ca ka <= -1.02
4,Ca ka <= 1.21,Ca ka <= 1.21,Ca ka <= 1.21,Ca ka <= 1.21
...,...,...,...,...
124,Fe ka + Ti ka > -0.04,NaN,Fe ka + Ti ka > -0.15,Fe ka + Ti ka <= 0.16
125,Fe ka + Ti ka <= 0.16,NaN,Class_A,Class_A
126,Fe ka + Ti ka > -0.15,NaN,Class_B,Class_B
127,Class_A,NaN,NaN,NaN
128,Class_B,NaN,NaN,NaN

In [13]:
all_results_pert[0]['pert_results_dict']['Bag_1']

                 Predicate  Perturbation
0            Ca ka > -0.36      0.289381
1            Ca ka > -1.02      0.214587
2            Ca ka > -1.73      0.187820
3           Ca ka <= -1.02      0.162082
4            Ca ka <= 1.21      0.151767
..                     ...           ...
118  Fe ka + Ti ka <= 0.06      0.000654
119   Fe ka + Ti ka > 0.06      0.000628
120  Fe ka + Ti ka <= 0.16      0.000620
121  Fe ka + Ti ka > -0.04      0.000572
122  Fe ka + Ti ka > -0.15      0.000551

[123 rows x 2 columns]

In [14]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_pert_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_pert = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_pert = lrc_summed_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_pert = lrc_summed_df_pert.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_pert = lrc_summed_unique_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_pert

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Ca ka > -0.36,20.512111,Ca ka,-0.36,>
1,Fe ka > 0.86,2.848046,Fe ka,0.86,>
2,Ti ka > 0.93,2.290338,Ti ka,0.93,>
3,Mn > 0.64,1.130747,Mn,0.64,>
4,Si > 0.13,1.087170,Si,0.13,>
5,Fe kb <= -0.07,0.502463,Fe kb,-0.07,<=
6,Ti kb <= -0.63,0.398855,Ti kb,-0.63,<=
7,Ca kb <= -0.23,0.206218,Ca kb,-0.23,<=
8,background2 <= -0.29,0.193309,background2,-0.29,<=
9,S <= -0.13,0.096174,S,-0.13,<=
10,Al > 0.16,0.093736,Al,0.16,>
11,P > 0.01,0.083394,P,0.01,>
12,Cr <= -0.12,0.081936,Cr,-0.12,<=
13,sum Fe <= -0.04,0.074149,sum Fe,-0.04,<=
14,background3 <= -0.04,0.066068,background3,-0.04,<=
15,K > 0.02,0.059461,K,0.02,>
16,Rh L + Ar <= -0.05,0.058982,Rh L + Ar,-0.05,<=
17,Cu > 0.06,0.058011,Cu,0.06,>
18,background1 <= -0.16,0.053841,background1,-0.16,<=
19,Fe ka + Ti ka <= -0.04,0.008083,Fe ka + Ti ka,-0.04,<=
20,Class_B,0.000000,None,None,None

In [15]:
# Aplicar o mapeamento
lrc_summed_df_pert_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_pert,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_pert_natural

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,Ca ka > -0.36,20.512111,Ca ka,-0.36,>,-0.641296,49.0,0.004141,Ca ka > -0.641296
1,Ca ka > -1.02,15.992136,Ca ka,-1.02,>,-1.635267,143.0,0.000757,Ca ka > -1.635267
2,Ca ka > -1.73,12.989248,Ca ka,-1.73,>,-2.806273,140.0,0.001954,Ca ka > -2.806273
3,Ca ka <= -1.02,10.449417,Ca ka,-1.02,<=,-1.635267,143.0,0.000757,Ca ka <= -1.635267
4,Ca ka <= 1.21,8.036128,Ca ka,1.21,<=,2.034067,2.0,0.019671,Ca ka <= 2.034067
...,...,...,...,...,...,...,...,...,...
131,Fe ka + Ti ka > -0.04,0.001336,Fe ka + Ti ka,-0.04,>,-0.040286,48.0,0.000022,Fe ka + Ti ka > -0.040286
132,Fe ka + Ti ka > -0.15,0.000736,Fe ka + Ti ka,-0.15,>,-0.137035,129.0,0.007042,Fe ka + Ti ka > -0.137035
133,Fe ka + Ti ka <= 0.16,0.000682,Fe ka + Ti ka,0.16,<=,0.163402,23.0,0.000909,Fe ka + Ti ka <= 0.163402
134,Class_B,0.000000,None,None,None,NaN,NaN,NaN,None
135,Class_A,0.000000,None,None,None,NaN,NaN,NaN,None

In [16]:
import plotly.graph_objects as go

n = 0
zone_name = lrc_summed_df_pert_natural.iloc[n]['Zone'] # o n indica a linha do dataframe lrc_summed_df_pert_natural que queremos acessar para pegar o nome da zona espectral (coluna 'Zone')
threshold_score = float(lrc_summed_df_pert_natural.iloc[n]['Threshold_Natural']) # o iloc acessa a linha n e a coluna 'Threshold_Natural' para pegar o valor do threshold já mapeado para o espaço natural (não pré-processado)

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
#print(f"  - Range de energias: {threshold_spectrum.index[n]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_pert_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona 'Ca ka':
  - Dimensão: 16 variáveis espectrais
  - Variância explicada pela PC1: 99.40%

In [17]:
# Permutation importance baseado em mudança nas probabilidades previstas (predict_proba)
# Medimos a média da diferença absoluta entre as probabilidades originais e as probabilidades
# obtidas após permutar cada variável. Isso fornece uma métrica contínua de importância.
n_repeats = 10
rng = np.random.RandomState(42)
# Probabilidades base (classe 'B' mapeada para 1)
baseline_proba = svm_model[3].predict_proba(Xcalclass_prep)[:, 1]
importance_list = []
X_arr = Xcalclass_prep.copy()
for col in Xcalclass_prep.columns:
    diffs = []
    for _ in range(n_repeats):
        X_perm = X_arr.copy()
        X_perm[col] = rng.permutation(X_perm[col].values)
        perm_proba = svm_model[3].predict_proba(X_perm)[:, 1]
        diffs.append(np.mean(np.abs(baseline_proba - perm_proba)))
    importance_list.append(np.mean(diffs))

permutation_df = pd.DataFrame({
    'energy': Xcalclass_prep.columns,
    'Permutation_importance_proba': importance_list
})
permutation_df.sort_values(by='Permutation_importance_proba', ascending=False, inplace=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in permutation_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
permutation_df['Zone'] = permutation_df['energy'].map(energy_to_zone_vip)
permutation_unique_df = permutation_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
permutation_unique_df = permutation_unique_df.sort_values(by='Permutation_importance_proba', ascending=False)
permutation_unique_df

   energy  Permutation_importance_proba           Zone
0     3.7                      0.043557          Ca ka
1    6.48                      0.017673          Fe ka
2    4.52                      0.010735          Ti ka
3    1.74                      0.005132             Si
4     5.9                      0.003679             Mn
5    7.14                      0.003100          Fe kb
6    4.02                      0.002621          Ca kb
7    4.96                      0.001283          Ti kb
8    2.02                      0.001207              P
9    1.54                      0.001110             Al
10   5.46                      0.000674             Cr
11  12.84                      0.000650         sum Fe
12   3.28                      0.000645              K
13   2.32                      0.000625              S
14   8.04                      0.000462             Cu
15   8.34                      0.000346    background2
16   7.54                      0.000327    background1
17    2.9                      0.000327      Rh L + Ar
18   11.4                      0.000309    background3
19  11.06                      0.000255  Fe ka + Ti ka
20   1.32                      0.000120            NaN

In [18]:
import numpy as np

max_len = max(
    len(pvector_unique_df['Zone']),
    len(shap_unique_df['Zone']),
    len(permutation_unique_df['Zone']),
    len(lrc_summed_unique_df_pert['Zone']),
    len(lrc_summed_unique_df_cov['Zone'])
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'SVM_pvector': pad_list(pvector_unique_df['Zone'], max_len),
    'Shap': pad_list(shap_unique_df['Zone'], max_len),
    'Permutation' : pad_list(permutation_unique_df['Zone'], max_len),
    'LRC_perturbation' : pad_list(lrc_summed_unique_df_pert['Zone'], max_len),
    'LRC_covariance' : pad_list(lrc_summed_unique_df_cov['Zone'], max_len),
})

features_importance.to_csv('feature_importance.csv', index=False, sep=';')
features_importance

,SVM_pvector,Shap,Permutation,LRC_perturbation,LRC_covariance
0,Ca ka,Ca ka,Ca ka,Ca ka,Ca ka
1,Fe ka,Fe ka,Fe ka,Fe ka,Fe ka
2,Ca kb,Ti ka,Ti ka,Ti ka,Ti ka
3,Fe kb,Si,Si,Mn,Mn
4,Si,Mn,Mn,Si,Si
5,Ti ka,Cr,Fe kb,Fe kb,Ca kb
6,Mn,background2,Ca kb,Ti kb,Fe kb
7,sum Fe,Ca kb,Ti kb,Ca kb,K
8,Al,Fe kb,P,background2,Ti kb
9,Cr,Ti kb,Al,S,Al
10,background3,P,Cr,Al,sum Fe
11,P,background1,sum Fe,P,P
12,background2,Cu,K,Cr,Cu
13,background1,NaN,S,sum Fe,Cr
14,S,background3,Cu,background3,background2
15,Ti kb,sum Fe,background2,K,background3
16,Cu,Fe ka + Ti ka,background1,Rh L + Ar,S
17,Rh L + Ar,Rh L + Ar,Rh L + Ar,Cu,background1
18,Fe ka + Ti ka,K,background3,background1,Rh L + Ar
19,K,Al,Fe ka + Ti ka,Fe ka + Ti ka,Fe ka + Ti ka
20,NaN,S,NaN,None,None

In [19]:
import rbo
rbo_comparison = pd.DataFrame(columns=['Method_1', 'Method_2', 'RBO_Score'])
methods = features_importance.columns.tolist()
for i in range(len(methods)):
    for j in range(i + 1, len(methods)):
        method_1 = methods[i]
        method_2 = methods[j]
        # Remove None values from the lists
        list_1 = [x for x in features_importance[method_1].tolist() if x is not None]
        list_2 = [x for x in features_importance[method_2].tolist() if x is not None]
        # Truncate both lists to the same length (minimum of both)
        min_len = min(len(list_1), len(list_2))
        list_1_trunc = list_1[:min_len]
        list_2_trunc = list_2[:min_len]
        rbo_score = rbo.RankingSimilarity(list_1_trunc, list_2_trunc).rbo(p=0.7, k=10)
        rbo_comparison = pd.concat([rbo_comparison, pd.DataFrame({
            'Method_1': [method_1],
            'Method_2': [method_2],
            'RBO_Score': [rbo_score]
        })], ignore_index=True)
rbo_comparison.sort_values(by='RBO_Score', ascending=False, inplace=True)
rbo_comparison.to_csv('rbo_rank.csv', index=False, sep=';')
rbo_comparison

C:\Users\Usuario\AppData\Local\Temp\ipykernel_13528\3097109587.py:16: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

           Method_1          Method_2  RBO_Score
9  LRC_perturbation    LRC_covariance   0.950876
4              Shap       Permutation   0.940824
7       Permutation  LRC_perturbation   0.936643
8       Permutation    LRC_covariance   0.931403
5              Shap  LRC_perturbation   0.918231
6              Shap    LRC_covariance   0.915099
1       SVM_pvector       Permutation   0.824734
3       SVM_pvector    LRC_covariance   0.824734
2       SVM_pvector  LRC_perturbation   0.818482
0       SVM_pvector              Shap   0.803158

In [20]:
lrc_summed_df_cov_natural.to_csv('lrc_cov_natural.csv', index=False, sep=';')
lrc_summed_df_pert_natural.to_csv('lrc_pert_natural.csv', index=False, sep=';')